package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Mar 08 16:13:46 PST 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "Service1HttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Service1HttpGet {

    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "SetTenantInfo")
    public boolean setTenantInfo(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "csUnit", name = "csUnit", targetNamespace = "")
        java.lang.String csUnit,
        @WebParam(partName = "csAddress", name = "csAddress", targetNamespace = "")
        java.lang.String csAddress,
        @WebParam(partName = "csZip", name = "csZip", targetNamespace = "")
        java.lang.String csZip,
        @WebParam(partName = "csCity", name = "csCity", targetNamespace = "")
        java.lang.String csCity,
        @WebParam(partName = "csEmail", name = "csEmail", targetNamespace = "")
        java.lang.String csEmail,
        @WebParam(partName = "csWorkPhone", name = "csWorkPhone", targetNamespace = "")
        java.lang.String csWorkPhone,
        @WebParam(partName = "csHomePhone", name = "csHomePhone", targetNamespace = "")
        java.lang.String csHomePhone,
        @WebParam(partName = "csCellPhone", name = "csCellPhone", targetNamespace = "")
        java.lang.String csCellPhone
    );

    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "MoveInSource")
    public boolean moveInSource(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "csUnitID", name = "csUnitID", targetNamespace = "")
        java.lang.String csUnitID,
        @WebParam(partName = "csSource", name = "csSource", targetNamespace = "")
        java.lang.String csSource
    );

    @WebResult(name = "ArrayOfAvailableInsurance_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AvailableInsurance")
    public ArrayOfAvailableInsuranceST availableInsurance(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "HelloWorld")
    public java.lang.String helloWorld();

    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GoPaperless")
    public boolean goPaperless(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "sUnit", name = "sUnit", targetNamespace = "")
        java.lang.String sUnit
    );

    @WebResult(name = "ArrayOfPaymentHistory_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "PaymentHistory")
    public ArrayOfPaymentHistoryST paymentHistory(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iCustomerID", name = "iCustomerID", targetNamespace = "")
        java.lang.String iCustomerID
    );

    @WebResult(name = "ArrayOfListCustomerUnits_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "ListCustomerUnits")
    public ArrayOfListCustomerUnitsST listCustomerUnits(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iCustomerID", name = "iCustomerID", targetNamespace = "")
        java.lang.String iCustomerID
    );

    @WebResult(name = "ArrayOfAvailableUnitTypesSpecial_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "JustAvailableUnitTypesSpecial")
    public ArrayOfAvailableUnitTypesSpecialST justAvailableUnitTypesSpecial(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "ArrayOfAnyType", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "FacilityInfo2")
    public ArrayOfAnyType facilityInfo2(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetMoveIncostSpecial")
    public java.lang.String getMoveIncostSpecial(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "sSpecial", name = "sSpecial", targetNamespace = "")
        java.lang.String sSpecial,
        @WebParam(partName = "sMoveInParam", name = "sMoveInParam", targetNamespace = "")
        java.lang.String sMoveInParam
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "HelloWorldPassword")
    public java.lang.String helloWorldPassword(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "ArrayOfCharge_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "MoveInCost2")
    public ArrayOfChargeST moveInCost2(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iUnitTypeId", name = "iUnitTypeId", targetNamespace = "")
        java.lang.String iUnitTypeId,
        @WebParam(partName = "tMoveInDate", name = "tMoveInDate", targetNamespace = "")
        java.lang.String tMoveInDate,
        @WebParam(partName = "csCoupon", name = "csCoupon", targetNamespace = "")
        java.lang.String csCoupon,
        @WebParam(partName = "dInsurance", name = "dInsurance", targetNamespace = "")
        java.lang.String dInsurance
    );

    @WebResult(name = "ArrayOfAvailableUnitTypes_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "JustAvailableUnitTypes")
    public ArrayOfAvailableUnitTypesST justAvailableUnitTypes(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UnitList")
    public ArrayOfString unitList(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "ArrayOfAvailableInventory", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetAvailableInventory")
    public ArrayOfAvailableInventory getAvailableInventory(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AssembliesVersion")
    public java.lang.String assembliesVersion();

    @WebResult(name = "ArrayOfAvailableUnitTypes_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AvailableUnitTypes")
    public ArrayOfAvailableUnitTypesST availableUnitTypes(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "IsPartialPaymentAllowed")
    public boolean isPartialPaymentAllowed(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AddAccountMoveInSpecial")
    public java.lang.String addAccountMoveInSpecial(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "sSpecialOrMoveInXML", name = "sSpecialOrMoveInXML", targetNamespace = "")
        java.lang.String sSpecialOrMoveInXML,
        @WebParam(partName = "sPaymentST", name = "sPaymentST", targetNamespace = "")
        java.lang.String sPaymentST,
        @WebParam(partName = "sTenantInfo", name = "sTenantInfo", targetNamespace = "")
        java.lang.String sTenantInfo,
        @WebParam(partName = "sMoveInParams", name = "sMoveInParams", targetNamespace = "")
        java.lang.String sMoveInParams
    );

    @WebResult(name = "UnitTypeInfo_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UnitTypeInfo")
    public UnitTypeInfoST unitTypeInfo(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "itypeId", name = "itypeId", targetNamespace = "")
        java.lang.String itypeId
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "SpecialDetails")
    public java.lang.String specialDetails(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "sSpecialID", name = "sSpecialID", targetNamespace = "")
        java.lang.String sSpecialID
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetOnlinePassword")
    public java.lang.String getOnlinePassword(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "csUnitID", name = "csUnitID", targetNamespace = "")
        java.lang.String csUnitID,
        @WebParam(partName = "csEmail", name = "csEmail", targetNamespace = "")
        java.lang.String csEmail
    );

    @WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "OccupiedUnitList")
    public ArrayOfString occupiedUnitList(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "ArrayOfAnyType", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetUnitSpecialCoupon")
    public ArrayOfAnyType getUnitSpecialCoupon(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iTypeId", name = "iTypeId", targetNamespace = "")
        java.lang.String iTypeId,
        @WebParam(partName = "sSpecialID", name = "sSpecialID", targetNamespace = "")
        java.lang.String sSpecialID
    );

    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "OnlineMoveInReconciliation")
    public boolean onlineMoveInReconciliation(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "sProcessor", name = "sProcessor", targetNamespace = "")
        java.lang.String sProcessor,
        @WebParam(partName = "sUnitID", name = "sUnitID", targetNamespace = "")
        java.lang.String sUnitID,
        @WebParam(partName = "dAmount", name = "dAmount", targetNamespace = "")
        java.lang.String dAmount,
        @WebParam(partName = "dfee", name = "dfee", targetNamespace = "")
        java.lang.String dfee
    );

    @WebResult(name = "ArrayOfGetCustomerAccountBalance_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetCustomerAccountBalance")
    public ArrayOfGetCustomerAccountBalanceST getCustomerAccountBalance(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iCustomerID", name = "iCustomerID", targetNamespace = "")
        java.lang.String iCustomerID,
        @WebParam(partName = "iMonth", name = "iMonth", targetNamespace = "")
        java.lang.String iMonth,
        @WebParam(partName = "csUnitID", name = "csUnitID", targetNamespace = "")
        java.lang.String csUnitID
    );

    @WebResult(name = "unsignedInt", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "CheckAccessCodeValidation")
    public long checkAccessCodeValidation(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "csUnitID", name = "csUnitID", targetNamespace = "")
        java.lang.String csUnitID,
        @WebParam(partName = "csAccessCode", name = "csAccessCode", targetNamespace = "")
        java.lang.String csAccessCode
    );

    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "CreateOrUpdatePassword")
    public boolean createOrUpdatePassword(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "sUnitID", name = "sUnitID", targetNamespace = "")
        java.lang.String sUnitID,
        @WebParam(partName = "sEmailAddress", name = "sEmailAddress", targetNamespace = "")
        java.lang.String sEmailAddress,
        @WebParam(partName = "sOldPass", name = "sOldPass", targetNamespace = "")
        java.lang.String sOldPass,
        @WebParam(partName = "sNewPass", name = "sNewPass", targetNamespace = "")
        java.lang.String sNewPass
    );

    @WebResult(name = "Charge_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "ReserveInCost")
    public ChargeST reserveInCost(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iUnitTypeId", name = "iUnitTypeId", targetNamespace = "")
        java.lang.String iUnitTypeId
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetUnitActiveSpecials")
    public java.lang.String getUnitActiveSpecials(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iTypeId", name = "iTypeId", targetNamespace = "")
        java.lang.String iTypeId
    );

    @WebResult(name = "ArrayOfAnyType", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "MoveInSourceList")
    public ArrayOfAnyType moveInSourceList(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "UserShortInfo_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetUnitEmail")
    public UserShortInfoST getUnitEmail(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "csUnitId", name = "csUnitId", targetNamespace = "")
        java.lang.String csUnitId
    );

    @WebResult(name = "UserAccount_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AccessExistingAccount")
    public UserAccountST accessExistingAccount(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "csUnitID", name = "csUnitID", targetNamespace = "")
        java.lang.String csUnitID,
        @WebParam(partName = "csAccessCode", name = "csAccessCode", targetNamespace = "")
        java.lang.String csAccessCode
    );

    @WebResult(name = "ArrayOfCharge_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "MoveInCost")
    public ArrayOfChargeST moveInCost(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iUnitTypeId", name = "iUnitTypeId", targetNamespace = "")
        java.lang.String iUnitTypeId,
        @WebParam(partName = "tMoveInDate", name = "tMoveInDate", targetNamespace = "")
        java.lang.String tMoveInDate
    );

    @WebResult(name = "ArrayOfAnyType", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod
    public ArrayOfAnyType eComCardTypes(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "FacilityInfo_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "FacilityInfo")
    public FacilityInfoST facilityInfo(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName
    );

    @WebResult(name = "ArrayOfAvailableUnits_ST", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AvailableUnits")
    public ArrayOfAvailableUnitsST availableUnits(
        @WebParam(partName = "csUser", name = "csUser", targetNamespace = "")
        java.lang.String csUser,
        @WebParam(partName = "csPassword", name = "csPassword", targetNamespace = "")
        java.lang.String csPassword,
        @WebParam(partName = "csSiteName", name = "csSiteName", targetNamespace = "")
        java.lang.String csSiteName,
        @WebParam(partName = "iTypeID", name = "iTypeID", targetNamespace = "")
        java.lang.String iTypeID
    );
}
