package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Mar 08 16:13:45 PST 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "Service1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Service1Soap {

    @WebResult(name = "SetTenantInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetTenantInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetTenantInfo")
    @WebMethod(operationName = "SetTenantInfo", action = "http://tempuri.org/SetTenantInfo")
    @ResponseWrapper(localName = "SetTenantInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetTenantInfoResponse")
    public boolean setTenantInfo(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnit", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnit,
        @WebParam(name = "csAddress", targetNamespace = "http://tempuri.org/")
        java.lang.String csAddress,
        @WebParam(name = "csZip", targetNamespace = "http://tempuri.org/")
        java.lang.String csZip,
        @WebParam(name = "csCity", targetNamespace = "http://tempuri.org/")
        java.lang.String csCity,
        @WebParam(name = "csEmail", targetNamespace = "http://tempuri.org/")
        java.lang.String csEmail,
        @WebParam(name = "csWorkPhone", targetNamespace = "http://tempuri.org/")
        java.lang.String csWorkPhone,
        @WebParam(name = "csHomePhone", targetNamespace = "http://tempuri.org/")
        java.lang.String csHomePhone,
        @WebParam(name = "csCellPhone", targetNamespace = "http://tempuri.org/")
        java.lang.String csCellPhone
    );

    @WebResult(name = "MoveInSourceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MoveInSource", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveInSource")
    @WebMethod(operationName = "MoveInSource", action = "http://tempuri.org/MoveInSource")
    @ResponseWrapper(localName = "MoveInSourceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveInSourceResponse")
    public boolean moveInSource(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "csSource", targetNamespace = "http://tempuri.org/")
        java.lang.String csSource
    );

    @WebResult(name = "AddAccountMoveInResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddAccountMoveIn", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddAccountMoveIn")
    @WebMethod(operationName = "AddAccountMoveIn", action = "http://tempuri.org/AddAccountMoveIn")
    @ResponseWrapper(localName = "AddAccountMoveInResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddAccountMoveInResponse")
    public org.tempuri.NewAccountResult addAccountMoveIn(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "PST", targetNamespace = "http://tempuri.org/")
        org.tempuri.PaymentST pst,
        @WebParam(name = "UST", targetNamespace = "http://tempuri.org/")
        org.tempuri.UserAccountST ust,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "iCustomerID", targetNamespace = "http://tempuri.org/")
        long iCustomerID
    );

    @WebResult(name = "AddAccountMoveIn2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddAccountMoveIn2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddAccountMoveIn2")
    @WebMethod(operationName = "AddAccountMoveIn2", action = "http://tempuri.org/AddAccountMoveIn2")
    @ResponseWrapper(localName = "AddAccountMoveIn2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddAccountMoveIn2Response")
    public org.tempuri.NewAccountResult addAccountMoveIn2(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "PST", targetNamespace = "http://tempuri.org/")
        org.tempuri.PaymentST pst,
        @WebParam(name = "UST", targetNamespace = "http://tempuri.org/")
        org.tempuri.UserAccountST ust,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "iCustomerID", targetNamespace = "http://tempuri.org/")
        long iCustomerID,
        @WebParam(name = "dInsurance", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal dInsurance,
        @WebParam(name = "iUnitTypeID", targetNamespace = "http://tempuri.org/")
        long iUnitTypeID,
        @WebParam(name = "csCoupon", targetNamespace = "http://tempuri.org/")
        java.lang.String csCoupon
    );

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    public java.lang.String helloWorld();

    @WebResult(name = "AvailableInsuranceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AvailableInsurance", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AvailableInsurance")
    @WebMethod(operationName = "AvailableInsurance", action = "http://tempuri.org/AvailableInsurance")
    @ResponseWrapper(localName = "AvailableInsuranceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AvailableInsuranceResponse")
    public org.tempuri.ArrayOfAvailableInsuranceST availableInsurance(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "GoPaperlessResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GoPaperless", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GoPaperless")
    @WebMethod(operationName = "GoPaperless", action = "http://tempuri.org/GoPaperless")
    @ResponseWrapper(localName = "GoPaperlessResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GoPaperlessResponse")
    public boolean goPaperless(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "sUnit", targetNamespace = "http://tempuri.org/")
        java.lang.String sUnit
    );

    @WebResult(name = "PaymentHistoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PaymentHistory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PaymentHistory")
    @WebMethod(operationName = "PaymentHistory", action = "http://tempuri.org/PaymentHistory")
    @ResponseWrapper(localName = "PaymentHistoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PaymentHistoryResponse")
    public org.tempuri.ArrayOfPaymentHistoryST paymentHistory(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iCustomerID", targetNamespace = "http://tempuri.org/")
        long iCustomerID
    );

    @WebResult(name = "ListCustomerUnitsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListCustomerUnits", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListCustomerUnits")
    @WebMethod(operationName = "ListCustomerUnits", action = "http://tempuri.org/ListCustomerUnits")
    @ResponseWrapper(localName = "ListCustomerUnitsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListCustomerUnitsResponse")
    public org.tempuri.ArrayOfListCustomerUnitsST listCustomerUnits(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iCustomerID", targetNamespace = "http://tempuri.org/")
        long iCustomerID
    );

    @WebResult(name = "JustAvailableUnitTypesSpecialResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JustAvailableUnitTypesSpecial", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JustAvailableUnitTypesSpecial")
    @WebMethod(operationName = "JustAvailableUnitTypesSpecial", action = "http://tempuri.org/JustAvailableUnitTypesSpecial")
    @ResponseWrapper(localName = "JustAvailableUnitTypesSpecialResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JustAvailableUnitTypesSpecialResponse")
    public org.tempuri.ArrayOfAvailableUnitTypesSpecialST justAvailableUnitTypesSpecial(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "FacilityInfo2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FacilityInfo2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FacilityInfo2")
    @WebMethod(operationName = "FacilityInfo2", action = "http://tempuri.org/FacilityInfo2")
    @ResponseWrapper(localName = "FacilityInfo2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FacilityInfo2Response")
    public org.tempuri.ArrayOfAnyType facilityInfo2(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "GetMoveIncostSpecialResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMoveIncostSpecial", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMoveIncostSpecial")
    @WebMethod(operationName = "GetMoveIncostSpecial", action = "http://tempuri.org/GetMoveIncostSpecial")
    @ResponseWrapper(localName = "GetMoveIncostSpecialResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMoveIncostSpecialResponse")
    public java.lang.String getMoveIncostSpecial(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "sSpecial", targetNamespace = "http://tempuri.org/")
        java.lang.String sSpecial,
        @WebParam(name = "sMoveInParam", targetNamespace = "http://tempuri.org/")
        java.lang.String sMoveInParam
    );

    @WebResult(name = "HelloWorldPasswordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorldPassword", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldPassword")
    @WebMethod(operationName = "HelloWorldPassword", action = "http://tempuri.org/HelloWorldPassword")
    @ResponseWrapper(localName = "HelloWorldPasswordResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldPasswordResponse")
    public java.lang.String helloWorldPassword(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "MoveInCost2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MoveInCost2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveInCost2")
    @WebMethod(operationName = "MoveInCost2", action = "http://tempuri.org/MoveInCost2")
    @ResponseWrapper(localName = "MoveInCost2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveInCost2Response")
    public org.tempuri.ArrayOfChargeST moveInCost2(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iUnitTypeId", targetNamespace = "http://tempuri.org/")
        long iUnitTypeId,
        @WebParam(name = "tMoveInDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar tMoveInDate,
        @WebParam(name = "csCoupon", targetNamespace = "http://tempuri.org/")
        java.lang.String csCoupon,
        @WebParam(name = "dInsurance", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal dInsurance
    );

    @WebResult(name = "JustAvailableUnitTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JustAvailableUnitTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JustAvailableUnitTypes")
    @WebMethod(operationName = "JustAvailableUnitTypes", action = "http://tempuri.org/JustAvailableUnitTypes")
    @ResponseWrapper(localName = "JustAvailableUnitTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JustAvailableUnitTypesResponse")
    public org.tempuri.ArrayOfAvailableUnitTypesST justAvailableUnitTypes(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "UnitListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UnitList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnitList")
    @WebMethod(operationName = "UnitList", action = "http://tempuri.org/UnitList")
    @ResponseWrapper(localName = "UnitListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnitListResponse")
    public org.tempuri.ArrayOfString unitList(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "GetAvailableInventoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAvailableInventory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAvailableInventory")
    @WebMethod(operationName = "GetAvailableInventory", action = "http://tempuri.org/GetAvailableInventory")
    @ResponseWrapper(localName = "GetAvailableInventoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAvailableInventoryResponse")
    public org.tempuri.ArrayOfAvailableInventory getAvailableInventory(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "AssembliesVersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AssembliesVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AssembliesVersion")
    @WebMethod(operationName = "AssembliesVersion", action = "http://tempuri.org/AssembliesVersion")
    @ResponseWrapper(localName = "AssembliesVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AssembliesVersionResponse")
    public java.lang.String assembliesVersion();

    @WebResult(name = "AvailableUnitTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AvailableUnitTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AvailableUnitTypes")
    @WebMethod(operationName = "AvailableUnitTypes", action = "http://tempuri.org/AvailableUnitTypes")
    @ResponseWrapper(localName = "AvailableUnitTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AvailableUnitTypesResponse")
    public org.tempuri.ArrayOfAvailableUnitTypesST availableUnitTypes(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "IsPartialPaymentAllowedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsPartialPaymentAllowed", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsPartialPaymentAllowed")
    @WebMethod(operationName = "IsPartialPaymentAllowed", action = "http://tempuri.org/IsPartialPaymentAllowed")
    @ResponseWrapper(localName = "IsPartialPaymentAllowedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsPartialPaymentAllowedResponse")
    public boolean isPartialPaymentAllowed(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "ProcessCustomeYapstonCCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessCustomeYapstonCC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessCustomeYapstonCC")
    @WebMethod(operationName = "ProcessCustomeYapstonCC", action = "http://tempuri.org/ProcessCustomeYapstonCC")
    @ResponseWrapper(localName = "ProcessCustomeYapstonCCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessCustomeYapstonCCResponse")
    public java.lang.String processCustomeYapstonCC(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "STT", targetNamespace = "http://tempuri.org/")
        org.tempuri.PaymentST stt
    );

    @WebResult(name = "AddAccountMoveInSpecialResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddAccountMoveInSpecial", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddAccountMoveInSpecial")
    @WebMethod(operationName = "AddAccountMoveInSpecial", action = "http://tempuri.org/AddAccountMoveInSpecial")
    @ResponseWrapper(localName = "AddAccountMoveInSpecialResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddAccountMoveInSpecialResponse")
    public java.lang.String addAccountMoveInSpecial(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "sSpecialOrMoveInXML", targetNamespace = "http://tempuri.org/")
        java.lang.String sSpecialOrMoveInXML,
        @WebParam(name = "sPaymentST", targetNamespace = "http://tempuri.org/")
        java.lang.String sPaymentST,
        @WebParam(name = "sTenantInfo", targetNamespace = "http://tempuri.org/")
        java.lang.String sTenantInfo,
        @WebParam(name = "sMoveInParams", targetNamespace = "http://tempuri.org/")
        java.lang.String sMoveInParams
    );

    @WebResult(name = "SetTenantInfoExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetTenantInfoEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetTenantInfoEx")
    @WebMethod(operationName = "SetTenantInfoEx", action = "http://tempuri.org/SetTenantInfoEx")
    @ResponseWrapper(localName = "SetTenantInfoExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetTenantInfoExResponse")
    public int setTenantInfoEx(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnit", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnit,
        @WebParam(name = "Params", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfAnyType params
    );

    @WebResult(name = "UnitTypeInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UnitTypeInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnitTypeInfo")
    @WebMethod(operationName = "UnitTypeInfo", action = "http://tempuri.org/UnitTypeInfo")
    @ResponseWrapper(localName = "UnitTypeInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnitTypeInfoResponse")
    public org.tempuri.UnitTypeInfoST unitTypeInfo(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "itypeId", targetNamespace = "http://tempuri.org/")
        long itypeId
    );

    @WebResult(name = "SpecialDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SpecialDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SpecialDetails")
    @WebMethod(operationName = "SpecialDetails", action = "http://tempuri.org/SpecialDetails")
    @ResponseWrapper(localName = "SpecialDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SpecialDetailsResponse")
    public java.lang.String specialDetails(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "sSpecialID", targetNamespace = "http://tempuri.org/")
        java.lang.String sSpecialID
    );

    @WebResult(name = "GetOnlinePasswordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOnlinePassword", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOnlinePassword")
    @WebMethod(operationName = "GetOnlinePassword", action = "http://tempuri.org/GetOnlinePassword")
    @ResponseWrapper(localName = "GetOnlinePasswordResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOnlinePasswordResponse")
    public java.lang.String getOnlinePassword(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "csEmail", targetNamespace = "http://tempuri.org/")
        java.lang.String csEmail
    );

    @WebResult(name = "OccupiedUnitListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OccupiedUnitList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OccupiedUnitList")
    @WebMethod(operationName = "OccupiedUnitList", action = "http://tempuri.org/OccupiedUnitList")
    @ResponseWrapper(localName = "OccupiedUnitListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OccupiedUnitListResponse")
    public org.tempuri.ArrayOfString occupiedUnitList(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "ReserveUnitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReserveUnit", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReserveUnit")
    @WebMethod(operationName = "ReserveUnit", action = "http://tempuri.org/ReserveUnit")
    @ResponseWrapper(localName = "ReserveUnitResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReserveUnitResponse")
    public org.tempuri.NewAccountResult reserveUnit(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "PST", targetNamespace = "http://tempuri.org/")
        org.tempuri.PaymentST pst,
        @WebParam(name = "UST", targetNamespace = "http://tempuri.org/")
        org.tempuri.UserAccountST ust,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "itypeId", targetNamespace = "http://tempuri.org/")
        long itypeId
    );

    @WebResult(name = "GetUnitSpecialCouponResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUnitSpecialCoupon", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnitSpecialCoupon")
    @WebMethod(operationName = "GetUnitSpecialCoupon", action = "http://tempuri.org/GetUnitSpecialCoupon")
    @ResponseWrapper(localName = "GetUnitSpecialCouponResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnitSpecialCouponResponse")
    public org.tempuri.ArrayOfAnyType getUnitSpecialCoupon(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iTypeId", targetNamespace = "http://tempuri.org/")
        long iTypeId,
        @WebParam(name = "sSpecialID", targetNamespace = "http://tempuri.org/")
        java.lang.String sSpecialID
    );

    @WebResult(name = "BuyInventoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BuyInventory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyInventory")
    @WebMethod(operationName = "BuyInventory", action = "http://tempuri.org/BuyInventory")
    @ResponseWrapper(localName = "BuyInventoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyInventoryResponse")
    public java.lang.String buyInventory(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "itemId", targetNamespace = "http://tempuri.org/")
        int itemId,
        @WebParam(name = "iCustomerNum", targetNamespace = "http://tempuri.org/")
        int iCustomerNum,
        @WebParam(name = "dAmount", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal dAmount,
        @WebParam(name = "ST", targetNamespace = "http://tempuri.org/")
        org.tempuri.PaymentST st
    );

    @WebResult(name = "GetCustomerAccountBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerAccountBalance", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerAccountBalance")
    @WebMethod(operationName = "GetCustomerAccountBalance", action = "http://tempuri.org/GetCustomerAccountBalance")
    @ResponseWrapper(localName = "GetCustomerAccountBalanceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerAccountBalanceResponse")
    public org.tempuri.ArrayOfGetCustomerAccountBalanceST getCustomerAccountBalance(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iCustomerID", targetNamespace = "http://tempuri.org/")
        long iCustomerID,
        @WebParam(name = "iMonth", targetNamespace = "http://tempuri.org/")
        long iMonth,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID
    );

    @WebResult(name = "CheckAccessCodeValidationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckAccessCodeValidation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckAccessCodeValidation")
    @WebMethod(operationName = "CheckAccessCodeValidation", action = "http://tempuri.org/CheckAccessCodeValidation")
    @ResponseWrapper(localName = "CheckAccessCodeValidationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckAccessCodeValidationResponse")
    public long checkAccessCodeValidation(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "csAccessCode", targetNamespace = "http://tempuri.org/")
        java.lang.String csAccessCode
    );

    @WebResult(name = "ReserveUnitNochargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReserveUnitNocharge", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReserveUnitNocharge")
    @WebMethod(operationName = "ReserveUnitNocharge", action = "http://tempuri.org/ReserveUnitNocharge")
    @ResponseWrapper(localName = "ReserveUnitNochargeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReserveUnitNochargeResponse")
    public org.tempuri.NewAccountResult reserveUnitNocharge(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "PST", targetNamespace = "http://tempuri.org/")
        org.tempuri.PaymentST pst,
        @WebParam(name = "UST", targetNamespace = "http://tempuri.org/")
        org.tempuri.UserAccountST ust,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "itypeId", targetNamespace = "http://tempuri.org/")
        long itypeId
    );

    @WebResult(name = "OnlineMoveInReconciliationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OnlineMoveInReconciliation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OnlineMoveInReconciliation")
    @WebMethod(operationName = "OnlineMoveInReconciliation", action = "http://tempuri.org/OnlineMoveInReconciliation")
    @ResponseWrapper(localName = "OnlineMoveInReconciliationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OnlineMoveInReconciliationResponse")
    public boolean onlineMoveInReconciliation(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "sProcessor", targetNamespace = "http://tempuri.org/")
        java.lang.String sProcessor,
        @WebParam(name = "sUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String sUnitID,
        @WebParam(name = "dAmount", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal dAmount,
        @WebParam(name = "dfee", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal dfee
    );

    @WebResult(name = "ProcessCustomeYapCCPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessCustomeYapCCPayment", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessCustomeYapCCPayment")
    @WebMethod(operationName = "ProcessCustomeYapCCPayment", action = "http://tempuri.org/ProcessCustomeYapCCPayment")
    @ResponseWrapper(localName = "ProcessCustomeYapCCPaymentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessCustomeYapCCPaymentResponse")
    public java.lang.String processCustomeYapCCPayment(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "STT", targetNamespace = "http://tempuri.org/")
        org.tempuri.YapstoneST stt
    );

    @WebResult(name = "CreateOrUpdatePasswordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateOrUpdatePassword", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOrUpdatePassword")
    @WebMethod(operationName = "CreateOrUpdatePassword", action = "http://tempuri.org/CreateOrUpdatePassword")
    @ResponseWrapper(localName = "CreateOrUpdatePasswordResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOrUpdatePasswordResponse")
    public boolean createOrUpdatePassword(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "sUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String sUnitID,
        @WebParam(name = "sEmailAddress", targetNamespace = "http://tempuri.org/")
        java.lang.String sEmailAddress,
        @WebParam(name = "sOldPass", targetNamespace = "http://tempuri.org/")
        java.lang.String sOldPass,
        @WebParam(name = "sNewPass", targetNamespace = "http://tempuri.org/")
        java.lang.String sNewPass
    );

    @WebResult(name = "ReserveInCostResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReserveInCost", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReserveInCost")
    @WebMethod(operationName = "ReserveInCost", action = "http://tempuri.org/ReserveInCost")
    @ResponseWrapper(localName = "ReserveInCostResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReserveInCostResponse")
    public org.tempuri.ChargeST reserveInCost(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iUnitTypeId", targetNamespace = "http://tempuri.org/")
        long iUnitTypeId
    );

    @WebResult(name = "GetUnitActiveSpecialsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUnitActiveSpecials", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnitActiveSpecials")
    @WebMethod(operationName = "GetUnitActiveSpecials", action = "http://tempuri.org/GetUnitActiveSpecials")
    @ResponseWrapper(localName = "GetUnitActiveSpecialsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnitActiveSpecialsResponse")
    public java.lang.String getUnitActiveSpecials(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iTypeId", targetNamespace = "http://tempuri.org/")
        long iTypeId
    );

    @WebResult(name = "MoveInSourceListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MoveInSourceList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveInSourceList")
    @WebMethod(operationName = "MoveInSourceList", action = "http://tempuri.org/MoveInSourceList")
    @ResponseWrapper(localName = "MoveInSourceListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveInSourceListResponse")
    public org.tempuri.ArrayOfAnyType moveInSourceList(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "ProcessCustomerCCPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessCustomerCCPayment", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessCustomerCCPayment")
    @WebMethod(operationName = "ProcessCustomerCCPayment", action = "http://tempuri.org/ProcessCustomerCCPayment")
    @ResponseWrapper(localName = "ProcessCustomerCCPaymentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessCustomerCCPaymentResponse")
    public java.lang.String processCustomerCCPayment(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "ST", targetNamespace = "http://tempuri.org/")
        org.tempuri.PaymentST st
    );

    @WebResult(name = "AccessExistingAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AccessExistingAccount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AccessExistingAccount")
    @WebMethod(operationName = "AccessExistingAccount", action = "http://tempuri.org/AccessExistingAccount")
    @ResponseWrapper(localName = "AccessExistingAccountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AccessExistingAccountResponse")
    public org.tempuri.UserAccountST accessExistingAccount(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "csAccessCode", targetNamespace = "http://tempuri.org/")
        java.lang.String csAccessCode
    );

    @WebResult(name = "ProcessCustomerCCPaymentThreadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessCustomerCCPaymentThread", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessCustomerCCPaymentThread")
    @WebMethod(operationName = "ProcessCustomerCCPaymentThread", action = "http://tempuri.org/ProcessCustomerCCPaymentThread")
    @ResponseWrapper(localName = "ProcessCustomerCCPaymentThreadResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessCustomerCCPaymentThreadResponse")
    public java.lang.String processCustomerCCPaymentThread(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitID,
        @WebParam(name = "ST", targetNamespace = "http://tempuri.org/")
        org.tempuri.PaymentST st
    );

    @WebResult(name = "GetUnitEmailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUnitEmail", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnitEmail")
    @WebMethod(operationName = "GetUnitEmail", action = "http://tempuri.org/GetUnitEmail")
    @ResponseWrapper(localName = "GetUnitEmailResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnitEmailResponse")
    public org.tempuri.UserShortInfoST getUnitEmail(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "csUnitId", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnitId
    );

    @WebResult(name = "FacilityInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FacilityInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FacilityInfo")
    @WebMethod(operationName = "FacilityInfo", action = "http://tempuri.org/FacilityInfo")
    @ResponseWrapper(localName = "FacilityInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FacilityInfoResponse")
    public org.tempuri.FacilityInfoST facilityInfo(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );

    @WebResult(name = "AvailableUnitsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AvailableUnits", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AvailableUnits")
    @WebMethod(operationName = "AvailableUnits", action = "http://tempuri.org/AvailableUnits")
    @ResponseWrapper(localName = "AvailableUnitsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AvailableUnitsResponse")
    public org.tempuri.ArrayOfAvailableUnitsST availableUnits(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iTypeID", targetNamespace = "http://tempuri.org/")
        long iTypeID
    );

    @WebResult(name = "UpdateAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateAccount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateAccount")
    @WebMethod(operationName = "UpdateAccount", action = "http://tempuri.org/UpdateAccount")
    @ResponseWrapper(localName = "UpdateAccountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateAccountResponse")
    public java.lang.String updateAccount(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iCustomerID", targetNamespace = "http://tempuri.org/")
        int iCustomerID,
        @WebParam(name = "csUnit", targetNamespace = "http://tempuri.org/")
        java.lang.String csUnit,
        @WebParam(name = "csOldAccessCode", targetNamespace = "http://tempuri.org/")
        java.lang.String csOldAccessCode,
        @WebParam(name = "csNewAccessCode", targetNamespace = "http://tempuri.org/")
        java.lang.String csNewAccessCode,
        @WebParam(name = "ST", targetNamespace = "http://tempuri.org/")
        org.tempuri.UserAccountST st
    );

    @WebResult(name = "MoveInCostResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MoveInCost", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveInCost")
    @WebMethod(operationName = "MoveInCost", action = "http://tempuri.org/MoveInCost")
    @ResponseWrapper(localName = "MoveInCostResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveInCostResponse")
    public org.tempuri.ArrayOfChargeST moveInCost(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName,
        @WebParam(name = "iUnitTypeId", targetNamespace = "http://tempuri.org/")
        long iUnitTypeId,
        @WebParam(name = "tMoveInDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar tMoveInDate
    );

    @WebResult(name = "eComCardTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "eComCardTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EComCardTypes")
    @WebMethod(action = "http://tempuri.org/eComCardTypes")
    @ResponseWrapper(localName = "eComCardTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EComCardTypesResponse")
    public org.tempuri.ArrayOfAnyType eComCardTypes(
        @WebParam(name = "csUser", targetNamespace = "http://tempuri.org/")
        java.lang.String csUser,
        @WebParam(name = "csPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String csPassword,
        @WebParam(name = "csSiteName", targetNamespace = "http://tempuri.org/")
        java.lang.String csSiteName
    );
}
