package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Mar 21 15:00:56 PDT 2011
 * Generated source version: 2.2.9
 */

public final class Service1HttpPost_Service1HttpPost_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Service1");

    private Service1HttpPost_Service1HttpPost_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Service1.WSDL_LOCATION;
        if (args.length > 0) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Service1 ss = new Service1(wsdlURL, SERVICE_NAME);
        Service1HttpPost port = ss.getService1HttpPost();

        {
            System.out.println("Invoking setTenantInfo...");
            java.lang.String _setTenantInfo_csUser = "";
            java.lang.String _setTenantInfo_csPassword = "";
            java.lang.String _setTenantInfo_csSiteName = "";
            java.lang.String _setTenantInfo_csUnit = "";
            java.lang.String _setTenantInfo_csAddress = "";
            java.lang.String _setTenantInfo_csZip = "";
            java.lang.String _setTenantInfo_csCity = "";
            java.lang.String _setTenantInfo_csEmail = "";
            java.lang.String _setTenantInfo_csWorkPhone = "";
            java.lang.String _setTenantInfo_csHomePhone = "";
            java.lang.String _setTenantInfo_csCellPhone = "";
            boolean _setTenantInfo__return = port.setTenantInfo(_setTenantInfo_csUser, _setTenantInfo_csPassword, _setTenantInfo_csSiteName, _setTenantInfo_csUnit, _setTenantInfo_csAddress, _setTenantInfo_csZip, _setTenantInfo_csCity, _setTenantInfo_csEmail, _setTenantInfo_csWorkPhone, _setTenantInfo_csHomePhone, _setTenantInfo_csCellPhone);
            System.out.println("setTenantInfo.result=" + _setTenantInfo__return);


        }
        {
            System.out.println("Invoking moveInSource...");
            java.lang.String _moveInSource_csUser = "";
            java.lang.String _moveInSource_csPassword = "";
            java.lang.String _moveInSource_csSiteName = "";
            java.lang.String _moveInSource_csUnitID = "";
            java.lang.String _moveInSource_csSource = "";
            boolean _moveInSource__return = port.moveInSource(_moveInSource_csUser, _moveInSource_csPassword, _moveInSource_csSiteName, _moveInSource_csUnitID, _moveInSource_csSource);
            System.out.println("moveInSource.result=" + _moveInSource__return);


        }
        {
            System.out.println("Invoking availableInsurance...");
            java.lang.String _availableInsurance_csUser = "";
            java.lang.String _availableInsurance_csPassword = "";
            java.lang.String _availableInsurance_csSiteName = "";
            org.tempuri.ArrayOfAvailableInsuranceST _availableInsurance__return = port.availableInsurance(_availableInsurance_csUser, _availableInsurance_csPassword, _availableInsurance_csSiteName);
            System.out.println("availableInsurance.result=" + _availableInsurance__return);


        }
        {
            System.out.println("Invoking helloWorld...");
            java.lang.String _helloWorld__return = port.helloWorld();
            System.out.println("helloWorld.result=" + _helloWorld__return);


        }
        {
            System.out.println("Invoking goPaperless...");
            java.lang.String _goPaperless_csUser = "";
            java.lang.String _goPaperless_csPassword = "";
            java.lang.String _goPaperless_csSiteName = "";
            java.lang.String _goPaperless_sUnit = "";
            boolean _goPaperless__return = port.goPaperless(_goPaperless_csUser, _goPaperless_csPassword, _goPaperless_csSiteName, _goPaperless_sUnit);
            System.out.println("goPaperless.result=" + _goPaperless__return);


        }
        {
            System.out.println("Invoking paymentHistory...");
            java.lang.String _paymentHistory_csUser = "";
            java.lang.String _paymentHistory_csPassword = "";
            java.lang.String _paymentHistory_csSiteName = "";
            java.lang.String _paymentHistory_iCustomerID = "";
            org.tempuri.ArrayOfPaymentHistoryST _paymentHistory__return = port.paymentHistory(_paymentHistory_csUser, _paymentHistory_csPassword, _paymentHistory_csSiteName, _paymentHistory_iCustomerID);
            System.out.println("paymentHistory.result=" + _paymentHistory__return);


        }
        {
            System.out.println("Invoking listCustomerUnits...");
            java.lang.String _listCustomerUnits_csUser = "";
            java.lang.String _listCustomerUnits_csPassword = "";
            java.lang.String _listCustomerUnits_csSiteName = "";
            java.lang.String _listCustomerUnits_iCustomerID = "";
            org.tempuri.ArrayOfListCustomerUnitsST _listCustomerUnits__return = port.listCustomerUnits(_listCustomerUnits_csUser, _listCustomerUnits_csPassword, _listCustomerUnits_csSiteName, _listCustomerUnits_iCustomerID);
            System.out.println("listCustomerUnits.result=" + _listCustomerUnits__return);


        }
        {
            System.out.println("Invoking justAvailableUnitTypesSpecial...");
            java.lang.String _justAvailableUnitTypesSpecial_csUser = "";
            java.lang.String _justAvailableUnitTypesSpecial_csPassword = "";
            java.lang.String _justAvailableUnitTypesSpecial_csSiteName = "";
            org.tempuri.ArrayOfAvailableUnitTypesSpecialST _justAvailableUnitTypesSpecial__return = port.justAvailableUnitTypesSpecial(_justAvailableUnitTypesSpecial_csUser, _justAvailableUnitTypesSpecial_csPassword, _justAvailableUnitTypesSpecial_csSiteName);
            System.out.println("justAvailableUnitTypesSpecial.result=" + _justAvailableUnitTypesSpecial__return);


        }
        {
            System.out.println("Invoking facilityInfo2...");
            java.lang.String _facilityInfo2_csUser = "";
            java.lang.String _facilityInfo2_csPassword = "";
            java.lang.String _facilityInfo2_csSiteName = "";
            org.tempuri.ArrayOfAnyType _facilityInfo2__return = port.facilityInfo2(_facilityInfo2_csUser, _facilityInfo2_csPassword, _facilityInfo2_csSiteName);
            System.out.println("facilityInfo2.result=" + _facilityInfo2__return);


        }
        {
            System.out.println("Invoking getMoveIncostSpecial...");
            java.lang.String _getMoveIncostSpecial_csUser = "";
            java.lang.String _getMoveIncostSpecial_csPassword = "";
            java.lang.String _getMoveIncostSpecial_csSiteName = "";
            java.lang.String _getMoveIncostSpecial_sSpecial = "";
            java.lang.String _getMoveIncostSpecial_sMoveInParam = "";
            java.lang.String _getMoveIncostSpecial__return = port.getMoveIncostSpecial(_getMoveIncostSpecial_csUser, _getMoveIncostSpecial_csPassword, _getMoveIncostSpecial_csSiteName, _getMoveIncostSpecial_sSpecial, _getMoveIncostSpecial_sMoveInParam);
            System.out.println("getMoveIncostSpecial.result=" + _getMoveIncostSpecial__return);


        }
        {
            System.out.println("Invoking helloWorldPassword...");
            java.lang.String _helloWorldPassword_csUser = "";
            java.lang.String _helloWorldPassword_csPassword = "";
            java.lang.String _helloWorldPassword_csSiteName = "";
            java.lang.String _helloWorldPassword__return = port.helloWorldPassword(_helloWorldPassword_csUser, _helloWorldPassword_csPassword, _helloWorldPassword_csSiteName);
            System.out.println("helloWorldPassword.result=" + _helloWorldPassword__return);


        }
        {
            System.out.println("Invoking moveInCost2...");
            java.lang.String _moveInCost2_csUser = "";
            java.lang.String _moveInCost2_csPassword = "";
            java.lang.String _moveInCost2_csSiteName = "";
            java.lang.String _moveInCost2_iUnitTypeId = "";
            java.lang.String _moveInCost2_tMoveInDate = "";
            java.lang.String _moveInCost2_csCoupon = "";
            java.lang.String _moveInCost2_dInsurance = "";
            org.tempuri.ArrayOfChargeST _moveInCost2__return = port.moveInCost2(_moveInCost2_csUser, _moveInCost2_csPassword, _moveInCost2_csSiteName, _moveInCost2_iUnitTypeId, _moveInCost2_tMoveInDate, _moveInCost2_csCoupon, _moveInCost2_dInsurance);
            System.out.println("moveInCost2.result=" + _moveInCost2__return);


        }
        {
            System.out.println("Invoking justAvailableUnitTypes...");
            java.lang.String _justAvailableUnitTypes_csUser = "";
            java.lang.String _justAvailableUnitTypes_csPassword = "";
            java.lang.String _justAvailableUnitTypes_csSiteName = "";
            org.tempuri.ArrayOfAvailableUnitTypesST _justAvailableUnitTypes__return = port.justAvailableUnitTypes(_justAvailableUnitTypes_csUser, _justAvailableUnitTypes_csPassword, _justAvailableUnitTypes_csSiteName);
            System.out.println("justAvailableUnitTypes.result=" + _justAvailableUnitTypes__return);


        }
        {
            System.out.println("Invoking unitList...");
            java.lang.String _unitList_csUser = "";
            java.lang.String _unitList_csPassword = "";
            java.lang.String _unitList_csSiteName = "";
            org.tempuri.ArrayOfString _unitList__return = port.unitList(_unitList_csUser, _unitList_csPassword, _unitList_csSiteName);
            System.out.println("unitList.result=" + _unitList__return);


        }
        {
            System.out.println("Invoking getAvailableInventory...");
            java.lang.String _getAvailableInventory_csUser = "";
            java.lang.String _getAvailableInventory_csPassword = "";
            java.lang.String _getAvailableInventory_csSiteName = "";
            org.tempuri.ArrayOfAvailableInventory _getAvailableInventory__return = port.getAvailableInventory(_getAvailableInventory_csUser, _getAvailableInventory_csPassword, _getAvailableInventory_csSiteName);
            System.out.println("getAvailableInventory.result=" + _getAvailableInventory__return);


        }
        {
            System.out.println("Invoking assembliesVersion...");
            java.lang.String _assembliesVersion__return = port.assembliesVersion();
            System.out.println("assembliesVersion.result=" + _assembliesVersion__return);


        }
        {
            System.out.println("Invoking availableUnitTypes...");
            java.lang.String _availableUnitTypes_csUser = "";
            java.lang.String _availableUnitTypes_csPassword = "";
            java.lang.String _availableUnitTypes_csSiteName = "";
            org.tempuri.ArrayOfAvailableUnitTypesST _availableUnitTypes__return = port.availableUnitTypes(_availableUnitTypes_csUser, _availableUnitTypes_csPassword, _availableUnitTypes_csSiteName);
            System.out.println("availableUnitTypes.result=" + _availableUnitTypes__return);


        }
        {
            System.out.println("Invoking isPartialPaymentAllowed...");
            java.lang.String _isPartialPaymentAllowed_csUser = "";
            java.lang.String _isPartialPaymentAllowed_csPassword = "";
            java.lang.String _isPartialPaymentAllowed_csSiteName = "";
            boolean _isPartialPaymentAllowed__return = port.isPartialPaymentAllowed(_isPartialPaymentAllowed_csUser, _isPartialPaymentAllowed_csPassword, _isPartialPaymentAllowed_csSiteName);
            System.out.println("isPartialPaymentAllowed.result=" + _isPartialPaymentAllowed__return);


        }
        {
            System.out.println("Invoking addAccountMoveInSpecial...");
            java.lang.String _addAccountMoveInSpecial_csUser = "";
            java.lang.String _addAccountMoveInSpecial_csPassword = "";
            java.lang.String _addAccountMoveInSpecial_csSiteName = "";
            java.lang.String _addAccountMoveInSpecial_sSpecialOrMoveInXML = "";
            java.lang.String _addAccountMoveInSpecial_sPaymentST = "";
            java.lang.String _addAccountMoveInSpecial_sTenantInfo = "";
            java.lang.String _addAccountMoveInSpecial_sMoveInParams = "";
            java.lang.String _addAccountMoveInSpecial__return = port.addAccountMoveInSpecial(_addAccountMoveInSpecial_csUser, _addAccountMoveInSpecial_csPassword, _addAccountMoveInSpecial_csSiteName, _addAccountMoveInSpecial_sSpecialOrMoveInXML, _addAccountMoveInSpecial_sPaymentST, _addAccountMoveInSpecial_sTenantInfo, _addAccountMoveInSpecial_sMoveInParams);
            System.out.println("addAccountMoveInSpecial.result=" + _addAccountMoveInSpecial__return);


        }
        {
            System.out.println("Invoking unitTypeInfo...");
            java.lang.String _unitTypeInfo_csUser = "";
            java.lang.String _unitTypeInfo_csPassword = "";
            java.lang.String _unitTypeInfo_csSiteName = "";
            java.lang.String _unitTypeInfo_itypeId = "";
            org.tempuri.UnitTypeInfoST _unitTypeInfo__return = port.unitTypeInfo(_unitTypeInfo_csUser, _unitTypeInfo_csPassword, _unitTypeInfo_csSiteName, _unitTypeInfo_itypeId);
            System.out.println("unitTypeInfo.result=" + _unitTypeInfo__return);


        }
        {
            System.out.println("Invoking specialDetails...");
            java.lang.String _specialDetails_csUser = "";
            java.lang.String _specialDetails_csPassword = "";
            java.lang.String _specialDetails_csSiteName = "";
            java.lang.String _specialDetails_sSpecialID = "";
            java.lang.String _specialDetails__return = port.specialDetails(_specialDetails_csUser, _specialDetails_csPassword, _specialDetails_csSiteName, _specialDetails_sSpecialID);
            System.out.println("specialDetails.result=" + _specialDetails__return);


        }
        {
            System.out.println("Invoking getOnlinePassword...");
            java.lang.String _getOnlinePassword_csUser = "";
            java.lang.String _getOnlinePassword_csPassword = "";
            java.lang.String _getOnlinePassword_csSiteName = "";
            java.lang.String _getOnlinePassword_csUnitID = "";
            java.lang.String _getOnlinePassword_csEmail = "";
            java.lang.String _getOnlinePassword__return = port.getOnlinePassword(_getOnlinePassword_csUser, _getOnlinePassword_csPassword, _getOnlinePassword_csSiteName, _getOnlinePassword_csUnitID, _getOnlinePassword_csEmail);
            System.out.println("getOnlinePassword.result=" + _getOnlinePassword__return);


        }
        {
            System.out.println("Invoking occupiedUnitList...");
            java.lang.String _occupiedUnitList_csUser = "";
            java.lang.String _occupiedUnitList_csPassword = "";
            java.lang.String _occupiedUnitList_csSiteName = "";
            org.tempuri.ArrayOfString _occupiedUnitList__return = port.occupiedUnitList(_occupiedUnitList_csUser, _occupiedUnitList_csPassword, _occupiedUnitList_csSiteName);
            System.out.println("occupiedUnitList.result=" + _occupiedUnitList__return);


        }
        {
            System.out.println("Invoking getUnitSpecialCoupon...");
            java.lang.String _getUnitSpecialCoupon_csUser = "";
            java.lang.String _getUnitSpecialCoupon_csPassword = "";
            java.lang.String _getUnitSpecialCoupon_csSiteName = "";
            java.lang.String _getUnitSpecialCoupon_iTypeId = "";
            java.lang.String _getUnitSpecialCoupon_sSpecialID = "";
            org.tempuri.ArrayOfAnyType _getUnitSpecialCoupon__return = port.getUnitSpecialCoupon(_getUnitSpecialCoupon_csUser, _getUnitSpecialCoupon_csPassword, _getUnitSpecialCoupon_csSiteName, _getUnitSpecialCoupon_iTypeId, _getUnitSpecialCoupon_sSpecialID);
            System.out.println("getUnitSpecialCoupon.result=" + _getUnitSpecialCoupon__return);


        }
        {
            System.out.println("Invoking onlineMoveInReconciliation...");
            java.lang.String _onlineMoveInReconciliation_csUser = "";
            java.lang.String _onlineMoveInReconciliation_csPassword = "";
            java.lang.String _onlineMoveInReconciliation_csSiteName = "";
            java.lang.String _onlineMoveInReconciliation_sProcessor = "";
            java.lang.String _onlineMoveInReconciliation_sUnitID = "";
            java.lang.String _onlineMoveInReconciliation_dAmount = "";
            java.lang.String _onlineMoveInReconciliation_dfee = "";
            boolean _onlineMoveInReconciliation__return = port.onlineMoveInReconciliation(_onlineMoveInReconciliation_csUser, _onlineMoveInReconciliation_csPassword, _onlineMoveInReconciliation_csSiteName, _onlineMoveInReconciliation_sProcessor, _onlineMoveInReconciliation_sUnitID, _onlineMoveInReconciliation_dAmount, _onlineMoveInReconciliation_dfee);
            System.out.println("onlineMoveInReconciliation.result=" + _onlineMoveInReconciliation__return);


        }
        {
            System.out.println("Invoking getCustomerAccountBalance...");
            java.lang.String _getCustomerAccountBalance_csUser = "";
            java.lang.String _getCustomerAccountBalance_csPassword = "";
            java.lang.String _getCustomerAccountBalance_csSiteName = "";
            java.lang.String _getCustomerAccountBalance_iCustomerID = "";
            java.lang.String _getCustomerAccountBalance_iMonth = "";
            java.lang.String _getCustomerAccountBalance_csUnitID = "";
            org.tempuri.ArrayOfGetCustomerAccountBalanceST _getCustomerAccountBalance__return = port.getCustomerAccountBalance(_getCustomerAccountBalance_csUser, _getCustomerAccountBalance_csPassword, _getCustomerAccountBalance_csSiteName, _getCustomerAccountBalance_iCustomerID, _getCustomerAccountBalance_iMonth, _getCustomerAccountBalance_csUnitID);
            System.out.println("getCustomerAccountBalance.result=" + _getCustomerAccountBalance__return);


        }
        {
            System.out.println("Invoking checkAccessCodeValidation...");
            java.lang.String _checkAccessCodeValidation_csUser = "";
            java.lang.String _checkAccessCodeValidation_csPassword = "";
            java.lang.String _checkAccessCodeValidation_csSiteName = "";
            java.lang.String _checkAccessCodeValidation_csUnitID = "";
            java.lang.String _checkAccessCodeValidation_csAccessCode = "";
            long _checkAccessCodeValidation__return = port.checkAccessCodeValidation(_checkAccessCodeValidation_csUser, _checkAccessCodeValidation_csPassword, _checkAccessCodeValidation_csSiteName, _checkAccessCodeValidation_csUnitID, _checkAccessCodeValidation_csAccessCode);
            System.out.println("checkAccessCodeValidation.result=" + _checkAccessCodeValidation__return);


        }
        {
            System.out.println("Invoking createOrUpdatePassword...");
            java.lang.String _createOrUpdatePassword_csUser = "";
            java.lang.String _createOrUpdatePassword_csPassword = "";
            java.lang.String _createOrUpdatePassword_csSiteName = "";
            java.lang.String _createOrUpdatePassword_sUnitID = "";
            java.lang.String _createOrUpdatePassword_sEmailAddress = "";
            java.lang.String _createOrUpdatePassword_sOldPass = "";
            java.lang.String _createOrUpdatePassword_sNewPass = "";
            boolean _createOrUpdatePassword__return = port.createOrUpdatePassword(_createOrUpdatePassword_csUser, _createOrUpdatePassword_csPassword, _createOrUpdatePassword_csSiteName, _createOrUpdatePassword_sUnitID, _createOrUpdatePassword_sEmailAddress, _createOrUpdatePassword_sOldPass, _createOrUpdatePassword_sNewPass);
            System.out.println("createOrUpdatePassword.result=" + _createOrUpdatePassword__return);


        }
        {
            System.out.println("Invoking reserveInCost...");
            java.lang.String _reserveInCost_csUser = "";
            java.lang.String _reserveInCost_csPassword = "";
            java.lang.String _reserveInCost_csSiteName = "";
            java.lang.String _reserveInCost_iUnitTypeId = "";
            org.tempuri.ChargeST _reserveInCost__return = port.reserveInCost(_reserveInCost_csUser, _reserveInCost_csPassword, _reserveInCost_csSiteName, _reserveInCost_iUnitTypeId);
            System.out.println("reserveInCost.result=" + _reserveInCost__return);


        }
        {
            System.out.println("Invoking getUnitActiveSpecials...");
            java.lang.String _getUnitActiveSpecials_csUser = "";
            java.lang.String _getUnitActiveSpecials_csPassword = "";
            java.lang.String _getUnitActiveSpecials_csSiteName = "";
            java.lang.String _getUnitActiveSpecials_iTypeId = "";
            java.lang.String _getUnitActiveSpecials__return = port.getUnitActiveSpecials(_getUnitActiveSpecials_csUser, _getUnitActiveSpecials_csPassword, _getUnitActiveSpecials_csSiteName, _getUnitActiveSpecials_iTypeId);
            System.out.println("getUnitActiveSpecials.result=" + _getUnitActiveSpecials__return);


        }
        {
            System.out.println("Invoking moveInSourceList...");
            java.lang.String _moveInSourceList_csUser = "";
            java.lang.String _moveInSourceList_csPassword = "";
            java.lang.String _moveInSourceList_csSiteName = "";
            org.tempuri.ArrayOfAnyType _moveInSourceList__return = port.moveInSourceList(_moveInSourceList_csUser, _moveInSourceList_csPassword, _moveInSourceList_csSiteName);
            System.out.println("moveInSourceList.result=" + _moveInSourceList__return);


        }
        {
            System.out.println("Invoking getUnitEmail...");
            java.lang.String _getUnitEmail_csUser = "";
            java.lang.String _getUnitEmail_csPassword = "";
            java.lang.String _getUnitEmail_csSiteName = "";
            java.lang.String _getUnitEmail_csUnitId = "";
            org.tempuri.UserShortInfoST _getUnitEmail__return = port.getUnitEmail(_getUnitEmail_csUser, _getUnitEmail_csPassword, _getUnitEmail_csSiteName, _getUnitEmail_csUnitId);
            System.out.println("getUnitEmail.result=" + _getUnitEmail__return);


        }
        {
            System.out.println("Invoking accessExistingAccount...");
            java.lang.String _accessExistingAccount_csUser = "";
            java.lang.String _accessExistingAccount_csPassword = "";
            java.lang.String _accessExistingAccount_csSiteName = "";
            java.lang.String _accessExistingAccount_csUnitID = "";
            java.lang.String _accessExistingAccount_csAccessCode = "";
            org.tempuri.UserAccountST _accessExistingAccount__return = port.accessExistingAccount(_accessExistingAccount_csUser, _accessExistingAccount_csPassword, _accessExistingAccount_csSiteName, _accessExistingAccount_csUnitID, _accessExistingAccount_csAccessCode);
            System.out.println("accessExistingAccount.result=" + _accessExistingAccount__return);


        }
        {
            System.out.println("Invoking moveInCost...");
            java.lang.String _moveInCost_csUser = "";
            java.lang.String _moveInCost_csPassword = "";
            java.lang.String _moveInCost_csSiteName = "";
            java.lang.String _moveInCost_iUnitTypeId = "";
            java.lang.String _moveInCost_tMoveInDate = "";
            org.tempuri.ArrayOfChargeST _moveInCost__return = port.moveInCost(_moveInCost_csUser, _moveInCost_csPassword, _moveInCost_csSiteName, _moveInCost_iUnitTypeId, _moveInCost_tMoveInDate);
            System.out.println("moveInCost.result=" + _moveInCost__return);


        }
        {
            System.out.println("Invoking eComCardTypes...");
            java.lang.String _eComCardTypes_csUser = "";
            java.lang.String _eComCardTypes_csPassword = "";
            java.lang.String _eComCardTypes_csSiteName = "";
            org.tempuri.ArrayOfAnyType _eComCardTypes__return = port.eComCardTypes(_eComCardTypes_csUser, _eComCardTypes_csPassword, _eComCardTypes_csSiteName);
            System.out.println("eComCardTypes.result=" + _eComCardTypes__return);


        }
        {
            System.out.println("Invoking facilityInfo...");
            java.lang.String _facilityInfo_csUser = "";
            java.lang.String _facilityInfo_csPassword = "";
            java.lang.String _facilityInfo_csSiteName = "";
            org.tempuri.FacilityInfoST _facilityInfo__return = port.facilityInfo(_facilityInfo_csUser, _facilityInfo_csPassword, _facilityInfo_csSiteName);
            System.out.println("facilityInfo.result=" + _facilityInfo__return);


        }
        {
            System.out.println("Invoking availableUnits...");
            java.lang.String _availableUnits_csUser = "";
            java.lang.String _availableUnits_csPassword = "";
            java.lang.String _availableUnits_csSiteName = "";
            java.lang.String _availableUnits_iTypeID = "";
            org.tempuri.ArrayOfAvailableUnitsST _availableUnits__return = port.availableUnits(_availableUnits_csUser, _availableUnits_csPassword, _availableUnits_csSiteName, _availableUnits_iTypeID);
            System.out.println("availableUnits.result=" + _availableUnits__return);


        }

        System.exit(0);
    }

}
