
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Mar 08 16:13:45 PST 2011
 * Generated source version: 2.2.9
 * 
 */

public final class Service1Soap_Service1Soap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Service1");

    private Service1Soap_Service1Soap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Service1.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service1 ss = new Service1(wsdlURL, SERVICE_NAME);
        Service1Soap port = ss.getService1Soap();  
        
        {
        System.out.println("Invoking setTenantInfo...");
        java.lang.String _setTenantInfo_csUser = "";
        java.lang.String _setTenantInfo_csPassword = "";
        java.lang.String _setTenantInfo_csSiteName = "";
        java.lang.String _setTenantInfo_csUnit = "";
        java.lang.String _setTenantInfo_csAddress = "";
        java.lang.String _setTenantInfo_csZip = "";
        java.lang.String _setTenantInfo_csCity = "";
        java.lang.String _setTenantInfo_csEmail = "";
        java.lang.String _setTenantInfo_csWorkPhone = "";
        java.lang.String _setTenantInfo_csHomePhone = "";
        java.lang.String _setTenantInfo_csCellPhone = "";
        boolean _setTenantInfo__return = port.setTenantInfo(_setTenantInfo_csUser, _setTenantInfo_csPassword, _setTenantInfo_csSiteName, _setTenantInfo_csUnit, _setTenantInfo_csAddress, _setTenantInfo_csZip, _setTenantInfo_csCity, _setTenantInfo_csEmail, _setTenantInfo_csWorkPhone, _setTenantInfo_csHomePhone, _setTenantInfo_csCellPhone);
        System.out.println("setTenantInfo.result=" + _setTenantInfo__return);


        }
        {
        System.out.println("Invoking moveInSource...");
        java.lang.String _moveInSource_csUser = "";
        java.lang.String _moveInSource_csPassword = "";
        java.lang.String _moveInSource_csSiteName = "";
        java.lang.String _moveInSource_csUnitID = "";
        java.lang.String _moveInSource_csSource = "";
        boolean _moveInSource__return = port.moveInSource(_moveInSource_csUser, _moveInSource_csPassword, _moveInSource_csSiteName, _moveInSource_csUnitID, _moveInSource_csSource);
        System.out.println("moveInSource.result=" + _moveInSource__return);


        }
        {
        System.out.println("Invoking addAccountMoveIn...");
        java.lang.String _addAccountMoveIn_csUser = "";
        java.lang.String _addAccountMoveIn_csPassword = "";
        java.lang.String _addAccountMoveIn_csSiteName = "";
        org.tempuri.PaymentST _addAccountMoveIn_pst = null;
        org.tempuri.UserAccountST _addAccountMoveIn_ust = null;
        java.lang.String _addAccountMoveIn_csUnitID = "";
        long _addAccountMoveIn_iCustomerID = 0;
        org.tempuri.NewAccountResult _addAccountMoveIn__return = port.addAccountMoveIn(_addAccountMoveIn_csUser, _addAccountMoveIn_csPassword, _addAccountMoveIn_csSiteName, _addAccountMoveIn_pst, _addAccountMoveIn_ust, _addAccountMoveIn_csUnitID, _addAccountMoveIn_iCustomerID);
        System.out.println("addAccountMoveIn.result=" + _addAccountMoveIn__return);


        }
        {
        System.out.println("Invoking addAccountMoveIn2...");
        java.lang.String _addAccountMoveIn2_csUser = "";
        java.lang.String _addAccountMoveIn2_csPassword = "";
        java.lang.String _addAccountMoveIn2_csSiteName = "";
        org.tempuri.PaymentST _addAccountMoveIn2_pst = null;
        org.tempuri.UserAccountST _addAccountMoveIn2_ust = null;
        java.lang.String _addAccountMoveIn2_csUnitID = "";
        long _addAccountMoveIn2_iCustomerID = 0;
        java.math.BigDecimal _addAccountMoveIn2_dInsurance = new java.math.BigDecimal("0");
        long _addAccountMoveIn2_iUnitTypeID = 0;
        java.lang.String _addAccountMoveIn2_csCoupon = "";
        org.tempuri.NewAccountResult _addAccountMoveIn2__return = port.addAccountMoveIn2(_addAccountMoveIn2_csUser, _addAccountMoveIn2_csPassword, _addAccountMoveIn2_csSiteName, _addAccountMoveIn2_pst, _addAccountMoveIn2_ust, _addAccountMoveIn2_csUnitID, _addAccountMoveIn2_iCustomerID, _addAccountMoveIn2_dInsurance, _addAccountMoveIn2_iUnitTypeID, _addAccountMoveIn2_csCoupon);
        System.out.println("addAccountMoveIn2.result=" + _addAccountMoveIn2__return);


        }
        {
        System.out.println("Invoking helloWorld...");
        java.lang.String _helloWorld__return = port.helloWorld();
        System.out.println("helloWorld.result=" + _helloWorld__return);


        }
        {
        System.out.println("Invoking availableInsurance...");
        java.lang.String _availableInsurance_csUser = "";
        java.lang.String _availableInsurance_csPassword = "";
        java.lang.String _availableInsurance_csSiteName = "";
        org.tempuri.ArrayOfAvailableInsuranceST _availableInsurance__return = port.availableInsurance(_availableInsurance_csUser, _availableInsurance_csPassword, _availableInsurance_csSiteName);
        System.out.println("availableInsurance.result=" + _availableInsurance__return);


        }
        {
        System.out.println("Invoking goPaperless...");
        java.lang.String _goPaperless_csUser = "";
        java.lang.String _goPaperless_csPassword = "";
        java.lang.String _goPaperless_csSiteName = "";
        java.lang.String _goPaperless_sUnit = "";
        boolean _goPaperless__return = port.goPaperless(_goPaperless_csUser, _goPaperless_csPassword, _goPaperless_csSiteName, _goPaperless_sUnit);
        System.out.println("goPaperless.result=" + _goPaperless__return);


        }
        {
        System.out.println("Invoking paymentHistory...");
        java.lang.String _paymentHistory_csUser = "";
        java.lang.String _paymentHistory_csPassword = "";
        java.lang.String _paymentHistory_csSiteName = "";
        long _paymentHistory_iCustomerID = 0;
        org.tempuri.ArrayOfPaymentHistoryST _paymentHistory__return = port.paymentHistory(_paymentHistory_csUser, _paymentHistory_csPassword, _paymentHistory_csSiteName, _paymentHistory_iCustomerID);
        System.out.println("paymentHistory.result=" + _paymentHistory__return);


        }
        {
        System.out.println("Invoking listCustomerUnits...");
        java.lang.String _listCustomerUnits_csUser = "";
        java.lang.String _listCustomerUnits_csPassword = "";
        java.lang.String _listCustomerUnits_csSiteName = "";
        long _listCustomerUnits_iCustomerID = 0;
        org.tempuri.ArrayOfListCustomerUnitsST _listCustomerUnits__return = port.listCustomerUnits(_listCustomerUnits_csUser, _listCustomerUnits_csPassword, _listCustomerUnits_csSiteName, _listCustomerUnits_iCustomerID);
        System.out.println("listCustomerUnits.result=" + _listCustomerUnits__return);


        }
        {
        System.out.println("Invoking justAvailableUnitTypesSpecial...");
        java.lang.String _justAvailableUnitTypesSpecial_csUser = "";
        java.lang.String _justAvailableUnitTypesSpecial_csPassword = "";
        java.lang.String _justAvailableUnitTypesSpecial_csSiteName = "";
        org.tempuri.ArrayOfAvailableUnitTypesSpecialST _justAvailableUnitTypesSpecial__return = port.justAvailableUnitTypesSpecial(_justAvailableUnitTypesSpecial_csUser, _justAvailableUnitTypesSpecial_csPassword, _justAvailableUnitTypesSpecial_csSiteName);
        System.out.println("justAvailableUnitTypesSpecial.result=" + _justAvailableUnitTypesSpecial__return);


        }
        {
        System.out.println("Invoking facilityInfo2...");
        java.lang.String _facilityInfo2_csUser = "";
        java.lang.String _facilityInfo2_csPassword = "";
        java.lang.String _facilityInfo2_csSiteName = "";
        org.tempuri.ArrayOfAnyType _facilityInfo2__return = port.facilityInfo2(_facilityInfo2_csUser, _facilityInfo2_csPassword, _facilityInfo2_csSiteName);
        System.out.println("facilityInfo2.result=" + _facilityInfo2__return);


        }
        {
        System.out.println("Invoking getMoveIncostSpecial...");
        java.lang.String _getMoveIncostSpecial_csUser = "";
        java.lang.String _getMoveIncostSpecial_csPassword = "";
        java.lang.String _getMoveIncostSpecial_csSiteName = "";
        java.lang.String _getMoveIncostSpecial_sSpecial = "";
        java.lang.String _getMoveIncostSpecial_sMoveInParam = "";
        java.lang.String _getMoveIncostSpecial__return = port.getMoveIncostSpecial(_getMoveIncostSpecial_csUser, _getMoveIncostSpecial_csPassword, _getMoveIncostSpecial_csSiteName, _getMoveIncostSpecial_sSpecial, _getMoveIncostSpecial_sMoveInParam);
        System.out.println("getMoveIncostSpecial.result=" + _getMoveIncostSpecial__return);


        }
        {
        System.out.println("Invoking helloWorldPassword...");
        java.lang.String _helloWorldPassword_csUser = "";
        java.lang.String _helloWorldPassword_csPassword = "";
        java.lang.String _helloWorldPassword_csSiteName = "";
        java.lang.String _helloWorldPassword__return = port.helloWorldPassword(_helloWorldPassword_csUser, _helloWorldPassword_csPassword, _helloWorldPassword_csSiteName);
        System.out.println("helloWorldPassword.result=" + _helloWorldPassword__return);


        }
        {
        System.out.println("Invoking moveInCost2...");
        java.lang.String _moveInCost2_csUser = "";
        java.lang.String _moveInCost2_csPassword = "";
        java.lang.String _moveInCost2_csSiteName = "";
        long _moveInCost2_iUnitTypeId = 0;
        javax.xml.datatype.XMLGregorianCalendar _moveInCost2_tMoveInDate = null;
        java.lang.String _moveInCost2_csCoupon = "";
        java.math.BigDecimal _moveInCost2_dInsurance = new java.math.BigDecimal("0");
        org.tempuri.ArrayOfChargeST _moveInCost2__return = port.moveInCost2(_moveInCost2_csUser, _moveInCost2_csPassword, _moveInCost2_csSiteName, _moveInCost2_iUnitTypeId, _moveInCost2_tMoveInDate, _moveInCost2_csCoupon, _moveInCost2_dInsurance);
        System.out.println("moveInCost2.result=" + _moveInCost2__return);


        }
        {
        System.out.println("Invoking justAvailableUnitTypes...");
        java.lang.String _justAvailableUnitTypes_csUser = "";
        java.lang.String _justAvailableUnitTypes_csPassword = "";
        java.lang.String _justAvailableUnitTypes_csSiteName = "";
        org.tempuri.ArrayOfAvailableUnitTypesST _justAvailableUnitTypes__return = port.justAvailableUnitTypes(_justAvailableUnitTypes_csUser, _justAvailableUnitTypes_csPassword, _justAvailableUnitTypes_csSiteName);
        System.out.println("justAvailableUnitTypes.result=" + _justAvailableUnitTypes__return);


        }
        {
        System.out.println("Invoking unitList...");
        java.lang.String _unitList_csUser = "";
        java.lang.String _unitList_csPassword = "";
        java.lang.String _unitList_csSiteName = "";
        org.tempuri.ArrayOfString _unitList__return = port.unitList(_unitList_csUser, _unitList_csPassword, _unitList_csSiteName);
        System.out.println("unitList.result=" + _unitList__return);


        }
        {
        System.out.println("Invoking getAvailableInventory...");
        java.lang.String _getAvailableInventory_csUser = "";
        java.lang.String _getAvailableInventory_csPassword = "";
        java.lang.String _getAvailableInventory_csSiteName = "";
        org.tempuri.ArrayOfAvailableInventory _getAvailableInventory__return = port.getAvailableInventory(_getAvailableInventory_csUser, _getAvailableInventory_csPassword, _getAvailableInventory_csSiteName);
        System.out.println("getAvailableInventory.result=" + _getAvailableInventory__return);


        }
        {
        System.out.println("Invoking assembliesVersion...");
        java.lang.String _assembliesVersion__return = port.assembliesVersion();
        System.out.println("assembliesVersion.result=" + _assembliesVersion__return);


        }
        {
        System.out.println("Invoking availableUnitTypes...");
        java.lang.String _availableUnitTypes_csUser = "";
        java.lang.String _availableUnitTypes_csPassword = "";
        java.lang.String _availableUnitTypes_csSiteName = "";
        org.tempuri.ArrayOfAvailableUnitTypesST _availableUnitTypes__return = port.availableUnitTypes(_availableUnitTypes_csUser, _availableUnitTypes_csPassword, _availableUnitTypes_csSiteName);
        System.out.println("availableUnitTypes.result=" + _availableUnitTypes__return);


        }
        {
        System.out.println("Invoking isPartialPaymentAllowed...");
        java.lang.String _isPartialPaymentAllowed_csUser = "";
        java.lang.String _isPartialPaymentAllowed_csPassword = "";
        java.lang.String _isPartialPaymentAllowed_csSiteName = "";
        boolean _isPartialPaymentAllowed__return = port.isPartialPaymentAllowed(_isPartialPaymentAllowed_csUser, _isPartialPaymentAllowed_csPassword, _isPartialPaymentAllowed_csSiteName);
        System.out.println("isPartialPaymentAllowed.result=" + _isPartialPaymentAllowed__return);


        }
        {
        System.out.println("Invoking processCustomeYapstonCC...");
        java.lang.String _processCustomeYapstonCC_csUser = "";
        java.lang.String _processCustomeYapstonCC_csPassword = "";
        java.lang.String _processCustomeYapstonCC_csSiteName = "";
        java.lang.String _processCustomeYapstonCC_csUnitID = "";
        org.tempuri.PaymentST _processCustomeYapstonCC_stt = null;
        java.lang.String _processCustomeYapstonCC__return = port.processCustomeYapstonCC(_processCustomeYapstonCC_csUser, _processCustomeYapstonCC_csPassword, _processCustomeYapstonCC_csSiteName, _processCustomeYapstonCC_csUnitID, _processCustomeYapstonCC_stt);
        System.out.println("processCustomeYapstonCC.result=" + _processCustomeYapstonCC__return);


        }
        {
        System.out.println("Invoking addAccountMoveInSpecial...");
        java.lang.String _addAccountMoveInSpecial_csUser = "";
        java.lang.String _addAccountMoveInSpecial_csPassword = "";
        java.lang.String _addAccountMoveInSpecial_csSiteName = "";
        java.lang.String _addAccountMoveInSpecial_sSpecialOrMoveInXML = "";
        java.lang.String _addAccountMoveInSpecial_sPaymentST = "";
        java.lang.String _addAccountMoveInSpecial_sTenantInfo = "";
        java.lang.String _addAccountMoveInSpecial_sMoveInParams = "";
        java.lang.String _addAccountMoveInSpecial__return = port.addAccountMoveInSpecial(_addAccountMoveInSpecial_csUser, _addAccountMoveInSpecial_csPassword, _addAccountMoveInSpecial_csSiteName, _addAccountMoveInSpecial_sSpecialOrMoveInXML, _addAccountMoveInSpecial_sPaymentST, _addAccountMoveInSpecial_sTenantInfo, _addAccountMoveInSpecial_sMoveInParams);
        System.out.println("addAccountMoveInSpecial.result=" + _addAccountMoveInSpecial__return);


        }
        {
        System.out.println("Invoking setTenantInfoEx...");
        java.lang.String _setTenantInfoEx_csUser = "";
        java.lang.String _setTenantInfoEx_csPassword = "";
        java.lang.String _setTenantInfoEx_csSiteName = "";
        java.lang.String _setTenantInfoEx_csUnit = "";
        org.tempuri.ArrayOfAnyType _setTenantInfoEx_params = null;
        int _setTenantInfoEx__return = port.setTenantInfoEx(_setTenantInfoEx_csUser, _setTenantInfoEx_csPassword, _setTenantInfoEx_csSiteName, _setTenantInfoEx_csUnit, _setTenantInfoEx_params);
        System.out.println("setTenantInfoEx.result=" + _setTenantInfoEx__return);


        }
        {
        System.out.println("Invoking unitTypeInfo...");
        java.lang.String _unitTypeInfo_csUser = "";
        java.lang.String _unitTypeInfo_csPassword = "";
        java.lang.String _unitTypeInfo_csSiteName = "";
        long _unitTypeInfo_itypeId = 0;
        org.tempuri.UnitTypeInfoST _unitTypeInfo__return = port.unitTypeInfo(_unitTypeInfo_csUser, _unitTypeInfo_csPassword, _unitTypeInfo_csSiteName, _unitTypeInfo_itypeId);
        System.out.println("unitTypeInfo.result=" + _unitTypeInfo__return);


        }
        {
        System.out.println("Invoking specialDetails...");
        java.lang.String _specialDetails_csUser = "";
        java.lang.String _specialDetails_csPassword = "";
        java.lang.String _specialDetails_csSiteName = "";
        java.lang.String _specialDetails_sSpecialID = "";
        java.lang.String _specialDetails__return = port.specialDetails(_specialDetails_csUser, _specialDetails_csPassword, _specialDetails_csSiteName, _specialDetails_sSpecialID);
        System.out.println("specialDetails.result=" + _specialDetails__return);


        }
        {
        System.out.println("Invoking getOnlinePassword...");
        java.lang.String _getOnlinePassword_csUser = "";
        java.lang.String _getOnlinePassword_csPassword = "";
        java.lang.String _getOnlinePassword_csSiteName = "";
        java.lang.String _getOnlinePassword_csUnitID = "";
        java.lang.String _getOnlinePassword_csEmail = "";
        java.lang.String _getOnlinePassword__return = port.getOnlinePassword(_getOnlinePassword_csUser, _getOnlinePassword_csPassword, _getOnlinePassword_csSiteName, _getOnlinePassword_csUnitID, _getOnlinePassword_csEmail);
        System.out.println("getOnlinePassword.result=" + _getOnlinePassword__return);


        }
        {
        System.out.println("Invoking occupiedUnitList...");
        java.lang.String _occupiedUnitList_csUser = "";
        java.lang.String _occupiedUnitList_csPassword = "";
        java.lang.String _occupiedUnitList_csSiteName = "";
        org.tempuri.ArrayOfString _occupiedUnitList__return = port.occupiedUnitList(_occupiedUnitList_csUser, _occupiedUnitList_csPassword, _occupiedUnitList_csSiteName);
        System.out.println("occupiedUnitList.result=" + _occupiedUnitList__return);


        }
        {
        System.out.println("Invoking reserveUnit...");
        java.lang.String _reserveUnit_csUser = "";
        java.lang.String _reserveUnit_csPassword = "";
        java.lang.String _reserveUnit_csSiteName = "";
        org.tempuri.PaymentST _reserveUnit_pst = null;
        org.tempuri.UserAccountST _reserveUnit_ust = null;
        java.lang.String _reserveUnit_csUnitID = "";
        long _reserveUnit_itypeId = 0;
        org.tempuri.NewAccountResult _reserveUnit__return = port.reserveUnit(_reserveUnit_csUser, _reserveUnit_csPassword, _reserveUnit_csSiteName, _reserveUnit_pst, _reserveUnit_ust, _reserveUnit_csUnitID, _reserveUnit_itypeId);
        System.out.println("reserveUnit.result=" + _reserveUnit__return);


        }
        {
        System.out.println("Invoking getUnitSpecialCoupon...");
        java.lang.String _getUnitSpecialCoupon_csUser = "";
        java.lang.String _getUnitSpecialCoupon_csPassword = "";
        java.lang.String _getUnitSpecialCoupon_csSiteName = "";
        long _getUnitSpecialCoupon_iTypeId = 0;
        java.lang.String _getUnitSpecialCoupon_sSpecialID = "";
        org.tempuri.ArrayOfAnyType _getUnitSpecialCoupon__return = port.getUnitSpecialCoupon(_getUnitSpecialCoupon_csUser, _getUnitSpecialCoupon_csPassword, _getUnitSpecialCoupon_csSiteName, _getUnitSpecialCoupon_iTypeId, _getUnitSpecialCoupon_sSpecialID);
        System.out.println("getUnitSpecialCoupon.result=" + _getUnitSpecialCoupon__return);


        }
        {
        System.out.println("Invoking buyInventory...");
        java.lang.String _buyInventory_csUser = "";
        java.lang.String _buyInventory_csPassword = "";
        java.lang.String _buyInventory_csSiteName = "";
        int _buyInventory_itemId = 0;
        int _buyInventory_iCustomerNum = 0;
        java.math.BigDecimal _buyInventory_dAmount = new java.math.BigDecimal("0");
        org.tempuri.PaymentST _buyInventory_st = null;
        java.lang.String _buyInventory__return = port.buyInventory(_buyInventory_csUser, _buyInventory_csPassword, _buyInventory_csSiteName, _buyInventory_itemId, _buyInventory_iCustomerNum, _buyInventory_dAmount, _buyInventory_st);
        System.out.println("buyInventory.result=" + _buyInventory__return);


        }
        {
        System.out.println("Invoking getCustomerAccountBalance...");
        java.lang.String _getCustomerAccountBalance_csUser = "";
        java.lang.String _getCustomerAccountBalance_csPassword = "";
        java.lang.String _getCustomerAccountBalance_csSiteName = "";
        long _getCustomerAccountBalance_iCustomerID = 0;
        long _getCustomerAccountBalance_iMonth = 0;
        java.lang.String _getCustomerAccountBalance_csUnitID = "";
        org.tempuri.ArrayOfGetCustomerAccountBalanceST _getCustomerAccountBalance__return = port.getCustomerAccountBalance(_getCustomerAccountBalance_csUser, _getCustomerAccountBalance_csPassword, _getCustomerAccountBalance_csSiteName, _getCustomerAccountBalance_iCustomerID, _getCustomerAccountBalance_iMonth, _getCustomerAccountBalance_csUnitID);
        System.out.println("getCustomerAccountBalance.result=" + _getCustomerAccountBalance__return);


        }
        {
        System.out.println("Invoking checkAccessCodeValidation...");
        java.lang.String _checkAccessCodeValidation_csUser = "";
        java.lang.String _checkAccessCodeValidation_csPassword = "";
        java.lang.String _checkAccessCodeValidation_csSiteName = "";
        java.lang.String _checkAccessCodeValidation_csUnitID = "";
        java.lang.String _checkAccessCodeValidation_csAccessCode = "";
        long _checkAccessCodeValidation__return = port.checkAccessCodeValidation(_checkAccessCodeValidation_csUser, _checkAccessCodeValidation_csPassword, _checkAccessCodeValidation_csSiteName, _checkAccessCodeValidation_csUnitID, _checkAccessCodeValidation_csAccessCode);
        System.out.println("checkAccessCodeValidation.result=" + _checkAccessCodeValidation__return);


        }
        {
        System.out.println("Invoking reserveUnitNocharge...");
        java.lang.String _reserveUnitNocharge_csUser = "";
        java.lang.String _reserveUnitNocharge_csPassword = "";
        java.lang.String _reserveUnitNocharge_csSiteName = "";
        org.tempuri.PaymentST _reserveUnitNocharge_pst = null;
        org.tempuri.UserAccountST _reserveUnitNocharge_ust = null;
        java.lang.String _reserveUnitNocharge_csUnitID = "";
        long _reserveUnitNocharge_itypeId = 0;
        org.tempuri.NewAccountResult _reserveUnitNocharge__return = port.reserveUnitNocharge(_reserveUnitNocharge_csUser, _reserveUnitNocharge_csPassword, _reserveUnitNocharge_csSiteName, _reserveUnitNocharge_pst, _reserveUnitNocharge_ust, _reserveUnitNocharge_csUnitID, _reserveUnitNocharge_itypeId);
        System.out.println("reserveUnitNocharge.result=" + _reserveUnitNocharge__return);


        }
        {
        System.out.println("Invoking onlineMoveInReconciliation...");
        java.lang.String _onlineMoveInReconciliation_csUser = "";
        java.lang.String _onlineMoveInReconciliation_csPassword = "";
        java.lang.String _onlineMoveInReconciliation_csSiteName = "";
        java.lang.String _onlineMoveInReconciliation_sProcessor = "";
        java.lang.String _onlineMoveInReconciliation_sUnitID = "";
        java.math.BigDecimal _onlineMoveInReconciliation_dAmount = new java.math.BigDecimal("0");
        java.math.BigDecimal _onlineMoveInReconciliation_dfee = new java.math.BigDecimal("0");
        boolean _onlineMoveInReconciliation__return = port.onlineMoveInReconciliation(_onlineMoveInReconciliation_csUser, _onlineMoveInReconciliation_csPassword, _onlineMoveInReconciliation_csSiteName, _onlineMoveInReconciliation_sProcessor, _onlineMoveInReconciliation_sUnitID, _onlineMoveInReconciliation_dAmount, _onlineMoveInReconciliation_dfee);
        System.out.println("onlineMoveInReconciliation.result=" + _onlineMoveInReconciliation__return);


        }
        {
        System.out.println("Invoking processCustomeYapCCPayment...");
        java.lang.String _processCustomeYapCCPayment_csUser = "";
        java.lang.String _processCustomeYapCCPayment_csPassword = "";
        java.lang.String _processCustomeYapCCPayment_csSiteName = "";
        java.lang.String _processCustomeYapCCPayment_csUnitID = "";
        org.tempuri.YapstoneST _processCustomeYapCCPayment_stt = null;
        java.lang.String _processCustomeYapCCPayment__return = port.processCustomeYapCCPayment(_processCustomeYapCCPayment_csUser, _processCustomeYapCCPayment_csPassword, _processCustomeYapCCPayment_csSiteName, _processCustomeYapCCPayment_csUnitID, _processCustomeYapCCPayment_stt);
        System.out.println("processCustomeYapCCPayment.result=" + _processCustomeYapCCPayment__return);


        }
        {
        System.out.println("Invoking createOrUpdatePassword...");
        java.lang.String _createOrUpdatePassword_csUser = "";
        java.lang.String _createOrUpdatePassword_csPassword = "";
        java.lang.String _createOrUpdatePassword_csSiteName = "";
        java.lang.String _createOrUpdatePassword_sUnitID = "";
        java.lang.String _createOrUpdatePassword_sEmailAddress = "";
        java.lang.String _createOrUpdatePassword_sOldPass = "";
        java.lang.String _createOrUpdatePassword_sNewPass = "";
        boolean _createOrUpdatePassword__return = port.createOrUpdatePassword(_createOrUpdatePassword_csUser, _createOrUpdatePassword_csPassword, _createOrUpdatePassword_csSiteName, _createOrUpdatePassword_sUnitID, _createOrUpdatePassword_sEmailAddress, _createOrUpdatePassword_sOldPass, _createOrUpdatePassword_sNewPass);
        System.out.println("createOrUpdatePassword.result=" + _createOrUpdatePassword__return);


        }
        {
        System.out.println("Invoking reserveInCost...");
        java.lang.String _reserveInCost_csUser = "";
        java.lang.String _reserveInCost_csPassword = "";
        java.lang.String _reserveInCost_csSiteName = "";
        long _reserveInCost_iUnitTypeId = 0;
        org.tempuri.ChargeST _reserveInCost__return = port.reserveInCost(_reserveInCost_csUser, _reserveInCost_csPassword, _reserveInCost_csSiteName, _reserveInCost_iUnitTypeId);
        System.out.println("reserveInCost.result=" + _reserveInCost__return);


        }
        {
        System.out.println("Invoking getUnitActiveSpecials...");
        java.lang.String _getUnitActiveSpecials_csUser = "";
        java.lang.String _getUnitActiveSpecials_csPassword = "";
        java.lang.String _getUnitActiveSpecials_csSiteName = "";
        long _getUnitActiveSpecials_iTypeId = 0;
        java.lang.String _getUnitActiveSpecials__return = port.getUnitActiveSpecials(_getUnitActiveSpecials_csUser, _getUnitActiveSpecials_csPassword, _getUnitActiveSpecials_csSiteName, _getUnitActiveSpecials_iTypeId);
        System.out.println("getUnitActiveSpecials.result=" + _getUnitActiveSpecials__return);


        }
        {
        System.out.println("Invoking moveInSourceList...");
        java.lang.String _moveInSourceList_csUser = "";
        java.lang.String _moveInSourceList_csPassword = "";
        java.lang.String _moveInSourceList_csSiteName = "";
        org.tempuri.ArrayOfAnyType _moveInSourceList__return = port.moveInSourceList(_moveInSourceList_csUser, _moveInSourceList_csPassword, _moveInSourceList_csSiteName);
        System.out.println("moveInSourceList.result=" + _moveInSourceList__return);


        }
        {
        System.out.println("Invoking processCustomerCCPayment...");
        java.lang.String _processCustomerCCPayment_csUser = "";
        java.lang.String _processCustomerCCPayment_csPassword = "";
        java.lang.String _processCustomerCCPayment_csSiteName = "";
        java.lang.String _processCustomerCCPayment_csUnitID = "";
        org.tempuri.PaymentST _processCustomerCCPayment_st = null;
        java.lang.String _processCustomerCCPayment__return = port.processCustomerCCPayment(_processCustomerCCPayment_csUser, _processCustomerCCPayment_csPassword, _processCustomerCCPayment_csSiteName, _processCustomerCCPayment_csUnitID, _processCustomerCCPayment_st);
        System.out.println("processCustomerCCPayment.result=" + _processCustomerCCPayment__return);


        }
        {
        System.out.println("Invoking accessExistingAccount...");
        java.lang.String _accessExistingAccount_csUser = "";
        java.lang.String _accessExistingAccount_csPassword = "";
        java.lang.String _accessExistingAccount_csSiteName = "";
        java.lang.String _accessExistingAccount_csUnitID = "";
        java.lang.String _accessExistingAccount_csAccessCode = "";
        org.tempuri.UserAccountST _accessExistingAccount__return = port.accessExistingAccount(_accessExistingAccount_csUser, _accessExistingAccount_csPassword, _accessExistingAccount_csSiteName, _accessExistingAccount_csUnitID, _accessExistingAccount_csAccessCode);
        System.out.println("accessExistingAccount.result=" + _accessExistingAccount__return);


        }
        {
        System.out.println("Invoking processCustomerCCPaymentThread...");
        java.lang.String _processCustomerCCPaymentThread_csUser = "";
        java.lang.String _processCustomerCCPaymentThread_csPassword = "";
        java.lang.String _processCustomerCCPaymentThread_csSiteName = "";
        java.lang.String _processCustomerCCPaymentThread_csUnitID = "";
        org.tempuri.PaymentST _processCustomerCCPaymentThread_st = null;
        java.lang.String _processCustomerCCPaymentThread__return = port.processCustomerCCPaymentThread(_processCustomerCCPaymentThread_csUser, _processCustomerCCPaymentThread_csPassword, _processCustomerCCPaymentThread_csSiteName, _processCustomerCCPaymentThread_csUnitID, _processCustomerCCPaymentThread_st);
        System.out.println("processCustomerCCPaymentThread.result=" + _processCustomerCCPaymentThread__return);


        }
        {
        System.out.println("Invoking getUnitEmail...");
        java.lang.String _getUnitEmail_csUser = "";
        java.lang.String _getUnitEmail_csPassword = "";
        java.lang.String _getUnitEmail_csSiteName = "";
        java.lang.String _getUnitEmail_csUnitId = "";
        org.tempuri.UserShortInfoST _getUnitEmail__return = port.getUnitEmail(_getUnitEmail_csUser, _getUnitEmail_csPassword, _getUnitEmail_csSiteName, _getUnitEmail_csUnitId);
        System.out.println("getUnitEmail.result=" + _getUnitEmail__return);


        }
        {
        System.out.println("Invoking facilityInfo...");
        java.lang.String _facilityInfo_csUser = "";
        java.lang.String _facilityInfo_csPassword = "";
        java.lang.String _facilityInfo_csSiteName = "";
        org.tempuri.FacilityInfoST _facilityInfo__return = port.facilityInfo(_facilityInfo_csUser, _facilityInfo_csPassword, _facilityInfo_csSiteName);
        System.out.println("facilityInfo.result=" + _facilityInfo__return);


        }
        {
        System.out.println("Invoking availableUnits...");
        java.lang.String _availableUnits_csUser = "";
        java.lang.String _availableUnits_csPassword = "";
        java.lang.String _availableUnits_csSiteName = "";
        long _availableUnits_iTypeID = 0;
        org.tempuri.ArrayOfAvailableUnitsST _availableUnits__return = port.availableUnits(_availableUnits_csUser, _availableUnits_csPassword, _availableUnits_csSiteName, _availableUnits_iTypeID);
        System.out.println("availableUnits.result=" + _availableUnits__return);


        }
        {
        System.out.println("Invoking updateAccount...");
        java.lang.String _updateAccount_csUser = "";
        java.lang.String _updateAccount_csPassword = "";
        java.lang.String _updateAccount_csSiteName = "";
        int _updateAccount_iCustomerID = 0;
        java.lang.String _updateAccount_csUnit = "";
        java.lang.String _updateAccount_csOldAccessCode = "";
        java.lang.String _updateAccount_csNewAccessCode = "";
        org.tempuri.UserAccountST _updateAccount_st = null;
        java.lang.String _updateAccount__return = port.updateAccount(_updateAccount_csUser, _updateAccount_csPassword, _updateAccount_csSiteName, _updateAccount_iCustomerID, _updateAccount_csUnit, _updateAccount_csOldAccessCode, _updateAccount_csNewAccessCode, _updateAccount_st);
        System.out.println("updateAccount.result=" + _updateAccount__return);


        }
        {
        System.out.println("Invoking moveInCost...");
        java.lang.String _moveInCost_csUser = "";
        java.lang.String _moveInCost_csPassword = "";
        java.lang.String _moveInCost_csSiteName = "";
        long _moveInCost_iUnitTypeId = 0;
        javax.xml.datatype.XMLGregorianCalendar _moveInCost_tMoveInDate = null;
        org.tempuri.ArrayOfChargeST _moveInCost__return = port.moveInCost(_moveInCost_csUser, _moveInCost_csPassword, _moveInCost_csSiteName, _moveInCost_iUnitTypeId, _moveInCost_tMoveInDate);
        System.out.println("moveInCost.result=" + _moveInCost__return);


        }
        {
        System.out.println("Invoking eComCardTypes...");
        java.lang.String _eComCardTypes_csUser = "";
        java.lang.String _eComCardTypes_csPassword = "";
        java.lang.String _eComCardTypes_csSiteName = "";
        org.tempuri.ArrayOfAnyType _eComCardTypes__return = port.eComCardTypes(_eComCardTypes_csUser, _eComCardTypes_csPassword, _eComCardTypes_csSiteName);
        System.out.println("eComCardTypes.result=" + _eComCardTypes__return);


        }

        System.exit(0);
    }

}
