package storitz.constants

/**
 * Created by IntelliJ IDEA.
 * User: mamster
 * Date: Apr 3, 2010
 * Time: 8:03:53 PM
 * To change this template use File | Settings | File Templates.
 */
public enum Country {

  UNITED_STATES("US", "United States"),
  AFGHANISTAN("AF", "Afghanistan"),
  ALAND_ISLANDS("AX", "Aland Islands"),
  ALBANIA("AL", "Albania"),
  ALGERIA("DZ", "Algeria"),
  AMERICAN_SAMOA("AS", "American Samoa"),
  ANDORRA("AD", "Andorra"),
  ANGOLA("AO", "Angola"),
  ANGUILLA("AI", "Anguilla"),
  ANTARCTICA("AQ", "Antartica"),
  ANTIGUA_AND_BARBUDA("AG", "Antigua and Barbuda"),
  ARGENTINA("AR", "Argentina"),
  ARMENIA("AM", "Armenia"),
  ARUBA("AW", "Aruba"),
  AUSTRALIA("AU", "Australia"),
  AUSTRIA("AT", "Austria"),
  AZERBAIJAN("AZ", "Azerbaijan"),
  BAHAMAS("BS", "Bahamas"),
  BAHRAIN("BH", "Bahrain"),
  BANGLADESH("BD", "Bangladesh"),
  BARBADOS("BB", "Barbados"),
  BELARUS("BY", "Belarus"),
  BELGIUM("BE", "Belgium"),
  BELIZE("BZ", "Belize"),
  BENIN("BJ", "Benin"),
  BERMUDA("BM", "Bermuda"),
  BHUTAN("BT", "Bhutan"),
  BOLIVIA("BO", "Bolivia"),
  BOSNIA_AND_HERZEGOVINA("BA", "Boznia and Herzegovina"),
  BOTSWANA("BW", "Botswana"),
  BOUVET_ISLAND("BV", "Bouvet Island"),
  BRAZIL("BR", "Brazil"),
  BRITISH_INDIAN_OCEAN_TERRITORY("IO", "British Indian Ocean"),
  BRUNEI_DARUSSALAM("BN", "Brunei"),
  BULGARIA("BG", "Bulgaria"),
  BURKINA_FASO("BF", "Burkina Faso"),
  BURUNDI("BI", "Burundi"),
  CAMBODIA("KH", "Cambodia"),
  CAMEROON("CM", "Cameroon"),
  CANADA("CA", "Canada"),
  CAPE_VERDE("CV", "Cape Verde"),
  CAYMAN_ISLANDS("KY", "Cayman Islands"),
  CENTRAL_AFRICAN_REPUBLIC("CF", "Central African Republic"),
  CHAD("TD", "Chad"),
  CHILE("CL", "Chile"),
  CHINA("CN", "China"),
  CHRISTMAS_ISLAND("CX", "Christmas Island"),
  COCOS_ISLANDS("CC", "Cocos Islands"),
  COLOMBIA("CO", "Columbia"),
  COMOROS("KM", "Comoros"),
  CONGO("CG", "Congo"),
  CONGO_REPUBLIC("CD", "Democratic Republic of Congo"),
  COOK_ISLANDS("CK", "Cook Islands"),
  COSTA_RICA("CR", "Costa Rica"),
  COTE_DIVOIRE("CI", "Ivory Coast"),
  CROATIA("HR", "Croatia"),
  CUBA("CU", "Cuba"),
  CYPRUS("CY", "Cyprus"),
  CZECH_REPUBLIC("CZ", "Czech Republic"),
  DENMARK("DK", "Denmark"),
  DJIBOUTI("DJ", "Djibouti"),
  DOMINICA("DM", "Dominica"),
  DOMINICAN_REPUBLIC("DO", "Dominican Republic"),
  ECUADOR("EC", "Ecuador"),
  EGYPT("EG", "Egypt"),
  EL_SALVADOR("SV", "El Salvador"),
  EQUATORIAL_GUINEA("GQ", "Equatorial Guinea"),
  ERITREA("ER", "Eritrea"),
  ESTONIA("EE", "Estonia"),
  ETHIOPIA("ET", "Ethiopia"),
  FALKLAND_ISLANDS("FK", "Falkland Islands"),
  FAROE_ISLANDS("FO", "Faroe Islands"),
  FIJI("FJ", "Fiji"),
  FINLAND("FI", "Finland"),
  FRANCE("FR", "France"),
  FRENCH_GUIANA("GF", "French Guiana"),
  FRENCH_POLYNESIA("PF", "French Polynesia"),
  FRENCH_SOUTHERN_TERRITORIES("TF", "French Southern Territories"),
  GABON("GA", "Gabon"),
  GAMBIA("GM", "Gambia"),
  GEORGIA("GE", "Georgia"),
  GERMANY("DE", "Germany"),
  GHANA ("GH", "Ghana"),
  GIBRALTAR("GI", "Gibraltar"),
  GREECE("GR", "Greece"),
  GREENLAND("GL", "Greenland"),
  GRENADA("GD", "Grenada"),
  GUADELOUPE("GP", "Guadeloupe"),
  GUAM("GU", "Guam"),
  GUATEMALA("GT", "Guatemala"),
  GUERNSEY("GG", "Guernsey"),
  GUINEA("GN", "Guinea"),
  GUINEA_BISSAU("GW", "Guinea-Bissau"),
  GUYANA ("GY", "Guyana"),
  HAITI("HT", "Haiti"),
  HEARD_ISLAND_AND_MCDONALD_ISLANDS("HM", "Heard and McDonald Islands"),
  HOLY_SEE("VA", "Vatican City"),
  HONDURAS("HN", "Honduras"),
  HONG_KONG("HK", "Hong Kong"),
  HUNGARY("HU", "Hungary"),
  ICELAND("IS", "Iceland"),
  INDIA("IN", "India"),
  INDONESIA("ID", "Indonesia"),
  IRAN("IR", "Iran"),
  IRAQ("IQ", "Iraq"),
  IRELAND("IE", "Ireland"),
  ISLE_OF_MAN("IM", "Isle of Man"),
  ISRAEL("IL", "Israel"),
  ITALY("IT", "Italy"),
  JAMAICA("JM", "Jamaica"),
  JAPAN("JP", "Japan"),
  JERSEY("JE", "Jersey"),
  JORDAN("JO", "Jordan"),
  KAZAKHSTAN("KZ", "Kazakhstan"),
  KENYA("KE", "Kenya"),
  KIRIBATI("KI", "Kiribati"),
  KOREA_DEMOCRATIC_PEOPLES_REPUBLIC("KP", "North Korea"),
  KOREA_REPUBLIC("KR", "South Korea"),
  KUWAIT("KW", "Kuwait"),
  KYRGYZSTAN("KG", "Kyrgyzstan"),
  LAO("LA", "Laos"),
  LATVIA("LV", "Latvia"),
  LEBANON("LB", "Lebanon"),
  LESOTHO("LS", "Lesotho"),
  LIBERIA("LR", "Liberia"),
  LIBYAN("LY", "Libya"),
  LIECHTENSTEIN("LI", "Liechtenstein"),
  LITHUANIA("LT", "Lithuania"),
  LUXEMBOURG("LU", "Luxembourg"),
  MACAO("MO", "Macao"),
  MACEDONIA("MK", "Macedonia"),
  MADAGASCAR("MG", "Madagascar"),
  MALAWI("MW", "Malawi"),
  MALAYSIA("MY", "Malaysia"),
  MALDIVES("MV", "Maldives"),
  MALI("ML", "Mali"),
  MALTA("MT", "Malta"),
  MARSHALL_ISLANDS("MH", "Marshall Islands"),
  MARTINIQUE("MQ", "Martinique"),
  MAURITANIA("MR", "Mauritania"),
  MAURITIUS("MU", "Mauritius"),
  MAYOTTE("YT", "Mayotte"),
  MEXICO("MX", "Mexico"),
  MICRONESIA("FM", "Micronesia"),
  MOLDOVA("MD", "Moldoca"),
  MONACO("MC", "Monaco"),
  MONGOLIA("MN", "Mongolia"),
  MONTENEGRO("ME", "Montenegro"),
  MONTSERRAT("MS", "Montserrat"),
  MOROCCO("MA", "Morocco"),
  MOZAMBIQUE("MZ", "Mozambique"),
  MYANMAR("MM", "Myanmar"),
  NAMIBIA("NA", "Namibia"),
  NAURU("NR", "Nauru"),
  NEPAL("NP", "Nepal"),
  NETHERLANDS("NL", "Netherlands"),
  NETHERLANDS_ANTILLES("AN", "Netherlands Antilles"),
  NEW_CALEDONIA("NC", "New Caledonia"),
  NEW_ZEALAND("NZ", "New Zealand"),
  NICARAGUA("NI", "Nicaragua"),
  NIGER("NE", "Niger"),
  NIGERIA("NG", "Nigeria"),
  NIUE("NU", "Niue"),
  NORFOLK_ISLAND("NF", "Norfolk Island"),
  NORTHERN_MARIANA_ISLANDS("MP", "Northern Mariana Islands"),
  NORWAY("NO", "Norway"),
  OMAN("OM", "Oman"),
  PAKISTAN("PK", "Pakistan"),
  PALAU("PW", "Palau"),
  PALESTINIAN_TERRITORY("PS", "Palestinian Territory"),
  PANAMA("PA", "Panama"),
  PAPUA_NEW_GUINEA("PG", "Papua New Guinea"),
  PARAGUAY("PY", "Paraguay"),
  PERU("PE", "Peru"),
  PHILIPPINES("PH", "Philippines"),
  PITCAIRN("PN", "Pitcairn"),
  POLAND("PL", "Poland"),
  PORTUGAL("PT", "Portugal"),
  PUERTO_RICO("PR", "Puerto Rico"),
  QATAR("QA", "Qatar"),
  REUNION("RE", "Reunion"),
  ROMANIA("RO", "Romania"),
  RUSSIAN_FEDERATION("RU", "Russia"),
  RWANDA("RW", "Rwanda"),
  SAINT_BARTHELEMY("BL", "Saint Barthelemy"),
  SAINT_HELENA("SH", "Saint Helena"),
  TTS_AND_NEVIS("KN", "Tts and Nevis"),
  SAINT_LUCIA("LC", "Saint Lucia"),
  SAINT_MARTIN("MF", "Saint Martin"),
  SAINT_PIERRE_AND_MIQUELON("PM", "Saint Pierre"),
  SAINT_VINCENT_AND_THE_GRENADINES("VC", "Saint Vincent"),
  SAMOA("WS", "Samoa"),
  SAN_MARINO("SM", "San Marino"),
  SAO_TOME_AND_PRINCIPE("ST", "Sao Tome"),
  SAUDI_ARABIA("SA", "Saudi Arabia"),
  SENEGAL("SN", "Senegal"),
  SERBIA("RS", "Serbia"),
  SEYCHELLES("SC", "Seychelles"),
  SIERRA_LEONE("SL", "Sierra Leone"),
  SINGAPORE("SG", "Singapore"),
  SLOVAKIA("SK", "Slovakia"),
  SLOVENIA("SI", "Slovenia"),
  SOLOMON_ISLANDS("SB", "Solomon Islands"),
  SOMALIA("SO", "Somalia"),
  SOUTH_AFRICA("ZA", "South Africa"),
  SOUTH_GEORGIA("GS", "South Georgia"),
  SPAIN("ES", "Spain"),
  SRI_LANKA("LK", "Sri Lanka"),
  SUDAN("SD", "Sudan"),
  SURINAME("SR", "Suriname"),
  SVALBARD_AND_JAN_MAYEN("SJ", "Svalbard and Jan Mayen"),
  SWAZILAND("SZ", "Swaziland"),
  SWEDEN("SE", "Sweden"),
  SWITZERLAND("CH", "Switzerland"),
  SYRIAN_ARAB_REPUBLIC("SY", "Syria"),
  TAIWAN("TW", "Taiwan"),
  TAJIKISTAN("TJ", "Tajikistan"),
  TANZANIA("TZ", "Tanzania"),
  THAILAND("TH", "Thailand"),
  TIMOR_LESTE("TL", "East Timor"),
  TOGO("TG", "Togo"),
  TOKELAU("TK", "Tokelau"),
  TONGA("TO", "Tonga"),
  TRINIDAD_AND_TOBAGO("TT", "Trinidad and Tobago"),
  TUNISIA("TN", "Tunisia"),
  TURKEY("TR", "Turkey"),
  TURKMENISTAN("TM", "Turkmenistan"),
  TURKS_AND_CAICOS_ISLANDS("TC", "Turks and Caicos Islands"),
  TUVALU("TV", "Tuvalu"),
  UGANDA("UG", "Uganda"),
  UKRAINE("UA", "Ukraine"),
  UNITED_ARAB_EMIRATES("AE", "United Arab Emirates"),
  UNITED_KINGDOM("GB", "United Kingdom"),
  UNITED_STATES_MINOR_OUTLYING_ISLANDS("UM", "United States Minor Outlying Islands"),
  URUGUAY("UY", "Uruguay"),
  UZBEKISTAN("UZ", "Uzbekistan"),
  VANUATU("VU", "Vanuatu"),
  VENEZUELA("VE", "Venezuela"),
  VIETNAM("VN", "Vietnam"),
  VIRGIN_ISLANDS_BRITISH("VG", "British Virgin Islands"),
  VIRGIN_ISLANDS_US("VI", "US Virgin Islands"),
  WALLIS_AND_FUTUNA("WF", "Wallis and Futana"),
  WESTERN_SAHARA("EH", "Western Sahara"),
  YEMEN("YE", "Yemen"),
  ZAMBIA("ZM", "Zambia"),
  ZIMBABWE("ZW", "Zimbabwe");

  final String display
  final String value

  Country(String value, String display) {
    this.value = value
    this.display = display
  }

  String getDisplay() { return this.display }

  String getKey() { return this.value }

  static list() {
    [
            UNITED_STATES, AFGHANISTAN, ALAND_ISLANDS, ALBANIA, ALGERIA, AMERICAN_SAMOA, ANDORRA,
            ANGOLA, ANGUILLA, ANTARCTICA, ANTIGUA_AND_BARBUDA, ARGENTINA, ARMENIA, ARUBA, AUSTRALIA,
            AUSTRIA, AZERBAIJAN, BAHAMAS, BAHRAIN, BANGLADESH, BARBADOS, BELARUS, BELGIUM, BELIZE,
            BENIN, BERMUDA, BHUTAN, BOLIVIA, BOSNIA_AND_HERZEGOVINA, BOTSWANA, BOUVET_ISLAND,
            BRAZIL, BRITISH_INDIAN_OCEAN_TERRITORY, BRUNEI_DARUSSALAM, BULGARIA, BURKINA_FASO,
            BURUNDI, CAMBODIA, CAMEROON, CANADA, CAPE_VERDE, CAYMAN_ISLANDS, CENTRAL_AFRICAN_REPUBLIC,
            CHAD, CHILE, CHINA, CHRISTMAS_ISLAND, COCOS_ISLANDS, COLOMBIA, COMOROS, CONGO,
            CONGO_REPUBLIC, COOK_ISLANDS, COSTA_RICA, COTE_DIVOIRE, CROATIA, CUBA, CYPRUS,
            CZECH_REPUBLIC, DENMARK, DJIBOUTI, DOMINICA, DOMINICAN_REPUBLIC, ECUADOR, EGYPT,
            EL_SALVADOR, EQUATORIAL_GUINEA, ERITREA, ESTONIA, ETHIOPIA, FALKLAND_ISLANDS,
            FAROE_ISLANDS, FIJI, FINLAND, FRANCE, FRENCH_GUIANA, FRENCH_POLYNESIA,
            FRENCH_SOUTHERN_TERRITORIES, GABON, GAMBIA, GEORGIA, GERMANY, GHANA, GIBRALTAR, GREECE,
            GREENLAND, GRENADA, GUADELOUPE, GUAM, GUATEMALA, GUERNSEY, GUINEA, GUINEA_BISSAU, GUYANA,
            HAITI, HEARD_ISLAND_AND_MCDONALD_ISLANDS, HOLY_SEE, HONDURAS, HONG_KONG, HUNGARY, ICELAND,
            INDIA, INDONESIA, IRAN, IRAQ, IRELAND, ISLE_OF_MAN, ISRAEL, ITALY, JAMAICA, JAPAN, JERSEY,
            JORDAN, KAZAKHSTAN, KENYA, KIRIBATI, KOREA_DEMOCRATIC_PEOPLES_REPUBLIC, KOREA_REPUBLIC,
            KUWAIT, KYRGYZSTAN, LAO, LATVIA, LEBANON, LESOTHO, LIBERIA, LIBYAN, LIECHTENSTEIN,
            LITHUANIA, LUXEMBOURG, MACAO, MACEDONIA, MADAGASCAR, MALAWI, MALAYSIA, MALDIVES, MALI,
            MALTA, MARSHALL_ISLANDS, MARTINIQUE, MAURITANIA, MAURITIUS, MAYOTTE, MEXICO, MICRONESIA,
            MOLDOVA, MONACO, MONGOLIA, MONTENEGRO, MONTSERRAT, MOROCCO, MOZAMBIQUE, MYANMAR,
            NAMIBIA, NAURU, NEPAL, NETHERLANDS, NETHERLANDS_ANTILLES, NEW_CALEDONIA, NEW_ZEALAND,
            NICARAGUA, NIGER, NIGERIA, NIUE, NORFOLK_ISLAND, NORTHERN_MARIANA_ISLANDS, NORWAY, OMAN,
            PAKISTAN, PALAU, PALESTINIAN_TERRITORY, PANAMA, PAPUA_NEW_GUINEA, PARAGUAY, PERU,
            PHILIPPINES, PITCAIRN, POLAND, PORTUGAL, PUERTO_RICO, QATAR, REUNION, ROMANIA,
            RUSSIAN_FEDERATION, RWANDA, SAINT_BARTHELEMY, SAINT_HELENA, TTS_AND_NEVIS, SAINT_LUCIA,
            SAINT_MARTIN, SAINT_PIERRE_AND_MIQUELON, SAINT_VINCENT_AND_THE_GRENADINES, SAMOA,
            SAN_MARINO, SAO_TOME_AND_PRINCIPE, SAUDI_ARABIA, SENEGAL, SERBIA, SEYCHELLES, SIERRA_LEONE,
            SINGAPORE, SLOVAKIA, SLOVENIA, SOLOMON_ISLANDS, SOMALIA, SOUTH_AFRICA, SOUTH_GEORGIA,
            SPAIN, SRI_LANKA, SUDAN, SURINAME, SVALBARD_AND_JAN_MAYEN, SWAZILAND, SWEDEN, SWITZERLAND,
            SYRIAN_ARAB_REPUBLIC, TAIWAN, TAJIKISTAN, TANZANIA, THAILAND, TIMOR_LESTE, TOGO,
            TOKELAU, TONGA, TRINIDAD_AND_TOBAGO, TUNISIA, TURKEY, TURKMENISTAN,
            TURKS_AND_CAICOS_ISLANDS, TUVALU, UGANDA, UKRAINE, UNITED_ARAB_EMIRATES, UNITED_KINGDOM,
            UNITED_STATES_MINOR_OUTLYING_ISLANDS, URUGUAY, UZBEKISTAN, VANUATU, VENEZUELA,
            VIETNAM, VIRGIN_ISLANDS_BRITISH, VIRGIN_ISLANDS_US, WALLIS_AND_FUTUNA, WESTERN_SAHARA,
            YEMEN, ZAMBIA, ZIMBABWE
    ]
  }

  public static Country fromText(String key) {
    def ret = list().find{ it.getKey() == key }
    if (!ret) return Country.valueOf(key)
    return ret
  }

}