package storitz

import storitz.*
import com.storitz.*

def descriptions_extraspace = [
	"ADN-Air-Cooled Down Normal"
	,"ADNM-Air-Cooled Down Normal"
	,"ADNU-Air-Cooled Down Normal"
	,"AEEM-Air-Cooled UP Economy"
	,"AEN-Air-Cooled UP Normal"
	,"AENM-Air-Cooled UP Normal"
	,"AENU-Air-Cooled UP Normal"
	,"AON-Air-Cooled Outside Normal"
	,"AONM-Air-Cooled Outside Normal"
	,"AONU-Air-Cooled Outside Normal"
	,"ASN-Air-Cooled UP Normal"
	,"BAA-Billboard"
	,"Boat/RV Parking"
	,"CBN-Climate Basement Normal"
	,"CBNM-Climate Basement Normal"
	,"CDE-Climate Down Economy"
	,"CDNA-Climate Down Normal"
	,"CDN-Climate Down Normal"
	,"CDNM-Climate Down Normal"
	,"CDNU-Climate Down Normal"
	,"CDNV-Climate Down Normal"
	,"CDP-Climate Down Premium"
	,"CDU-Climate Down U.Premium"
	,"CDX-Climate Down Locker"
	,"CDXV - Climate DOWN Locker Unit Wine"
	,"CDY-Climate Down Ladder Unit"
	,"CEE-Climate UP Economy"
	,"CENA-Climate UP Normal"
	,"CEN-Climate UP Normal"
	,"CENM-Climate UP Normal"
	,"CENU-Climate UP Normal"
	,"CENW-Climate UP Normal"
	,"CEP-Climate UP Premium"
	,"CEX - Climate UP Locker Unit"
	,"CEY - Climate UP Locker Unit"
	,"CLE-Climate UP Economy"
	,"CLN-Climate UP Normal"
	,"CLNM-Climate UP Normal"
	,"CLNU-Climate UP Normal"
	,"CON-Climate Outside Normal"
	,"CONM-Climate Outside Normal"
	,"COP-Climate Outside Premium"
	,"CSE-Climate UP Economy"
	,"CSN-Climate UP Normal"
	,"CSNM-Climate UP Normal"
	,"CSX - Climate UP Locker Unit"
	,"DDN-Dehumidified Down Normal"
	,"Garage Unit"
	,"HDE-Heated Down Economy"
	,"HDEM-Heated Down Economy"
	,"HDN-Heated Down Normal"
	,"HDNM-Heated Down Normal"
	,"HDP-Heated Down Premium"
	,"HDX-Heated Down Locker"
	,"HDY-Heated DOWN Locker Unit"
	,"HEE-Heated UP Economy"
	,"HEEM-Heated UP Economy"
	,"HEEU-Heated UP Economy"
	,"HEN-Heated UP Normal"
	,"HENM-Heated UP Normal"
	,"HEX - Heated UP Locker Unit"
	,"HEY - Heated UP Locker Unit"
	,"HLN-Heated UP Normal"
	,"HON-Heated Outside Normal"
	,"HONU-Heated Outside Normal"
	,"HOP-Heated Outside Premium"
	,"HSN-Heated UP Normal"
	,"LAA-Parking"
	,"MAA-Miscillaneous"
	,"Mailbox - Small"
	,"NBNM-Non-Climate Basement Normal"
	,"NBN-Non-Climate Basement Normal"
	,"NDEM-Non-Climate Down Economy"
	,"NDE-Non-Climate Down Economy"
	,"NDNA-Non-Climate Down Normal"
	,"NDNM-Non-Climate Down Normal"
	,"NDN-Non-Climate Down Normal"
	,"NDNU-Non-Climate Down Normal"
	,"NDNW-Non-Climate Down Normal"
	,"NDP-Non-Climate Down Premium"
	,"NDX-Non-Climate Down Locker"
	,"NDY-Non-Climate Down Ladder Unit"
	,"NDZ-Non-Climate Down Ladder Unit"
	,"NEEM-Non-Climate UP Economy"
	,"NEE-Non-Climate UP Economy"
	,"NENM-Non-Climate UP Normal"
	,"NEN-Non-Climate UP Normal"
	,"NENU-Non-Climate UP Normal"
	,"NEP-Non-Climate UP Premium"
	,"NEX - Non-Climate UP Locker Unit"
	,"NEY - Non-Climate UP Locker Unit"
	,"NLE-Non Climate Up Economy (near lift)"
	,"NLNM-Non-Climate UP Normal"
	,"NLN-Non-Climate UP Normal"
	,"NOEMA-Non-Climate Outside Economy"
	,"NOEM-Non-Climate Outside Economy"
	,"NOE-Non-Climate Outside Economy"
	,"NOEU-Non-Climate Outside Economy"
	,"NONA-Non-Climate Outside Normal"
	,"NONM-Non-Climate Outside Normal"
	,"NON-Non-Climate Outside Normal"
	,"NONU-Non-Climate Outside Normal"
	,"NONW-Non-Climate Outside Normal"
	,"NOP-Non-Climate Outside Premium"
	,"NSE-Non-Climate UP Economy"
	,"NSNM-Non-Climate UP Normal"
	,"NSN-Non-Climate UP Normal"
	,"NSX - Non-Climate UP Locker Unit"
	,"NXN-Non-Climate Stacked Normal"
	,"NYN-Non-Climate Stacked Normal"
	,"NZN-Non-Climate Stacked Normal"
	,"OAA-OfficeSpace"
	,"OAE-OfficeSpace Economy"
	,"OAP-OfficeSpace Premium"
	,"PAA-Parking"
	,"PAAU-Parking"
	,"PAE-Parking"
	,"PAP-Parking"
	,"RAA-Retail"
	,"Recreational Vehicle"
	,"Self Storage"
	,"TAA-CellTower"
	,"VAA-Parking"
	,"VAAU-Parking"
	,"VAE-Parking"
	,"VDA-Parking"
	,"WAA-WorkShop"
	,"XAA-WareHouse"
	,"ZAA - Apartment"
]

def descriptions_lockup = [
	"10x28"
	,"20 PARKING"
	,"30 PARKING"
	,"A - Drive Up CC"
	,"A - Drive Up Climate Control"
	,"A - Drive Up Trad"
	,"A - Interior Climate"
	,"A - Interior Trad"
	,"A-Parking"
	,"B - Drive Up CC"
	,"B - Drive Up Trad"
	,"Billboard"
	,"B - Interior Climate"
	,"B - Interior Trad"
	,"B-Parking"
	,"CC Economy"
	,"C - Drive Up CC"
	,"C - Drive Up Trad"
	,"C - Interior Climate"
	,"C - Interior Trad"
	,"Climate Controlled Interior Unit"
	,"Company"
	,"Mezzanine"
	,"Motorcycle Storage"
	,"Outside Parking"
	,"Parking Space"
	,"Sky Box"
	,"Wine 105 Case"
	,"Wine 120 Case"
	,"Wine 12 D"
	,"Wine 12 S"
	,"Wine 14"
	,"Wine 150 Case"
	,"Wine 16 Case"
	,"Wine 16 D"
	,"Wine 16 S"
	,"Wine 18"
	,"Wine 180 Case"
	,"Wine 18 Case"
	,"Wine 190 Case"
	,"Wine 24 Case"
	,"Wine 24 D"
	,"Wine 260 Case"
	,"Wine 268 Case"
	,"Wine 28"
	,"Wine 32 D"
	,"Wine 36 D"
	,"Wine 4"
	,"Wine 42"
	,"Wine 48 Case"
	,"Wine 48 D"
	,"Wine 4 S"
	,"Wine 6"
	,"Wine64D"
	,"Wine 8 D"
	,"Wine 8 S"
	,"Wine 9"
	,"Wine 96 Case"
	,"Wine Storage"
]

def descriptions_metro = [
	"5th Floor Interior Climate Control"
	,"Apartment"
	,"Climate Controlled"
	,"Climate Controlled Top Locker"
	,"Drive-thru access climate controlled storage"
	,"Drive-thru, drive-up access regular storage"
	,"Drive Up Access"
	,"Drive Up Access Climate Controlled"
	,"Drive-up access climate controlled storage"
	,"Drive Up Access Double Door"
	,"Drive-up access regular storage"
	,"Drive Up Access Regular Storage Dual Access"
	,"Drive up access regular storage - special price"
	,"Drive-up access regular storage w/ electric"
	,"Drive Up Access Regular Storage w/ High Door"
	,"Drive-up w/crank oversized regular storage"
	,"Drive-up w/hook regular storage"
	,"Economy 1st floor climate controlled storage"
	,"Economy multi-level climate controlled storage"
	,"Exterior Parking Space"
	,"Indoor"
	,"Industrial Unit"
	,"Interior, 1st floor CC storage - special price"
	,"Interior, 1st floor climate controlled storage"
	,"Interior, 1st floor locker climate controlled"
	,"Interior, 1st floor regular storage"
	,"Interior 1st floor Regular Storage- Premium"
	,"Interior, 1st flr regular storage - special price"
	,"Interior, 4th Floor Climate Controlled Storage"
	,"Interior, Climate Controlled Parking"
	,"Interior, heated parking space"
	,"Interior, locker regular storage"
	,"Interior, multi-level CC storage - special price"
	,"Interior, multi-level climate controlled storage"
	,"Interior, multi-level locker climate controlled"
	,"Interior, multi-level locker regular storage"
	,"Interior, multi-level reg storage - special price"
	,"Interior, multi-level regular storage"
	,"Interior Office Space"
	,"Interior office space with common areas"
	,"Interior parking space"
	,"Mailbox"
	,"Office Suite A"
	,"Outside Parking"
	,"Parking Space"
	,"Premium 1st floor climate controlled storage"
	,"RV Parking"
	,"RV Parking - Covered"
	,"Wine - Walk In Cellar"
]

def descriptions_price = [
	"1st Floor EZ Access"
	,"1st Floor Hall EZ Access"
	,"1st Floor Standard Access"
	,"2nd Floor EZ Access"
	,"2nd Floor Hall EZ Access"
	,"2nd Floor Standard Access"
	,"3rd Floor EZ Access"
	,"3rd Floor Hall EZ Access"
	,"3rd Floor Standard Access"
	,"Bldg A Drive-Up"
	,"Bldg A Ground Level"
	,"Bldg A Upper Floor"
	,"Bldg B Drive-Up"
	,"Bldg B Ground Level"
	,"Cell Tower"
	,"Climate Controlled"
	,"Company"
	,"Drive Up 24 Hour Access"
	,"Drive Up Access"
	,"Drive Up Access Portable"
	,"EZ Access"
	,"Locker"
	,"Locker 1st Floor - Hall EZ Access"
	,"Lower Level EZ Access"
	,"Outside Parking"
	,"Parking Space"
	,"Personal Vault"
	,"Recreational Vehicle"
	,"Recreational Vehicle w/ Electric"
	,"RV Parking - Uncovered"
	,"Standard Access"
	,"Wine - Bottom 36 Case"
	,"Wine - Full 54 Case"
	,"Wine - Top 18 Case"
	,"Wine - Walk In Cellar"
]

def descriptions_simply = [
	"1st Floor Air Conditioned"
	,"1st Floor Climate Control"
	,"1st Floor Climate Controlled"
	,"1st Floor Climate Control Special"
	,"1st Floor Commercial Climate Control"
	,"1st Floor Interior"
	,"1st Floor Interior Climate Controlled"
	,"1st Floor Interior/Drive Up"
	,"1st Floor Locker"
	,"1st Floor Non-Climate Controlled"
	,"1st Floor Upper Locker"
	,"24 Hour Access"
	,"2nd Floor Climate Controlled"
	,"2nd Floor Climate Controlled Special"
	,"2nd Floor Climate Control Special"
	,"2nd Floor Interior"
	,"2nd Floor Interior Climate Controlled"
	," 2nd Floor Self Storage - Non Climate"
	,"2nd Floor Stair Access Only"
	,"2nd Floor Storage"
	,"2nd Floor Upper Locker"
	,"3rd Floor Climate Controlled"
	,"3rd Floor Interior"
	,"4th Floor Climate Controlled"
	,"4th Floor Interior"
	,"4th Floor Locker"
	,"A-Parking"
	,"Apartment"
	,"Billboard"
	,"CDN-Climate Down Normal"
	,"CDNM-Climate Down Normal"
	,"Cell Tower"
	,"CEN-Climate UP Normal"
	,"CENM-Climate UP Normal"
	,"Climate Control Ground Level"
	,"Climate Controlled"
	,"Climate Controlled Ground Level"
	,"Climate Controlled Special"
	,"Climate Controlled Upper Unit"
	,"Climate Controlled Upstairs Interior"
	,"Climate control upper Mezz200"
	,"Climate,Outside, Drive up"
	,"Company"
	,"Drive Up"
	,"Drive Up 24 Hour Access"
	,"Drive Up Access"
	,"Drive Up Access Back"
	,"Drive Up Access Climate Controlled"
	,"Drive Up Access CP"
	,"Drive Up Access Double Door"
	,"Drive up access regular storage - special price"
	,"Drive Up Access Special"
	,"Drive Up Climate Control"
	,"Drive Up Interior"
	,"Drive-Up - Irregular Shape"
	,"Drive Up Storage 24hr"
	,"Elevator - Climate Controlled"
	,"Enclosed Units"
	,"Enclosed Winter Car Storage"
	,"Exterior Parking Space P"
	,"Ground Level"
	,"Heated Only"
	,"Heated Upper Unit"
	,"Humidity Controlled"
	,"Inside, Climate Control"
	,"Inside, Non Climate Controll"
	,"Inside RV Parking"
	,"Interior"
	,"Interior, 1st floor alarmed regular storage"
	,"Interior, 1st floor regular storage"
	,"Interior 1st floor Regular Storage- Premium"
	,"Interior, 1st flr regular storage - special price"
	,"Interior Climate Controlled - 1st Floor - Special"
	,"Interior Climate Controlled - 2nd Floor - Special"
	,"Interior Climate Controlled - 3rd Floor - Special"
	,"Interior Climate Controlled - 4th Floor - Special"
	,"Interior Climate Controlled Special"
	,"Interior Climate Control - Lower Level - Special"
	,"Interior Ground Level"
	,"Interior Ground Level - Economy"
	,"Interior Non Climate - 1st Floor - Special"
	,"Interior Non Climate - 2nd Floor - Special"
	,"Interior Non Climate - 3rd Floor - Special"
	,"Interior Non Climate - 5th Floor - Special"
	,"Interior Non Climate - Lower Level - Special"
	,"Interior Non Climate - Upper Level - Special"
	,"Interior Storage"
	,"Interior Unit"
	,"Interior Unit Ground Level"
	,"Interior Unit Second Floor"
	,"Locker Climate Controlled"
	,"Lower Level"
	,"Lower Level Climate Controlled"
	,"Lower Level Climate Controlled Bottom Locker"
	,"L-Shape Unit"
	,"Mail Box"
	,"Medium Mail Box"
	,"Mezzanine Climate Controlled"
	,"Motorcycle Storage"
	,"No Attribute"
	,"NON-Non-Climate Outside Normal"
	,"Office"
	,"Office - Executive"
	,"Office Front"
	,"Office - Jr. Executive"
	,"Office - Professional"
	,"Office Suite"
	,"Office Suite A"
	,"Office Suite B"
	,"Outside, Drive Up"
	,"Outside Parking"
	,"Outside Walk-Up"
	,"PA-Parking"
	,"Parking - Covered"
	,"Parking Outside"
	,"Parking Space"
	,"Parking Type 2"
	,"Prking Outside"
	,"Recreational Vehicle"
	,"Retail Office Space"
	,"RV Back Lot"
	,"RV - Gravel"
	,"R-V Parking"
	,"RV Parking"
	,"RV Parking - Covered"
	,"RV Parking - Large"
	,"RV Parking - Uncovered"
	,"RV - Paved"
	,"Small Mail Box"
	,"Special"
	,"Uncovered Parking"
	,"Upper-Elevator Access"
	,"Upper Floor"
	,"Upper Level"
	,"Vehicle Parking"
	,"Warehouse Space"
	,"Wine Storage"
	,"XO-WareHouse"
]

def descriptions_sst = [
	"1st Floor"
	,"1st Floor Climate Control"
	,"1st Floor Climate Controlled"
	,"1st Floor Interior"
	,"1st Floor Non-Climate Controlled"
	,"24 HR Out"
	,"2nd Floor Interior"
	,"2nd Floor Storage"
	,"3rd Floor Climate Controlled"
	,"3rd Floor Interior"
	,"3rd Floor Storage"
	,"AirCDn"
	,"AirCDnPrem"
	,"AirCDnVal"
	,"AirCUp"
	,"AirCUpElev"
	,"AirCUpPElev"
	,"AirCUpVElev"
	,"Apartment"
	,"BAA-Billboard"
	,"Basement Interior Unit"
	,"Billbrd"
	,"CCDn"
	,"CCDnPrem"
	,"CCDnVal"
	,"CC Drive Up"
	,"CC IN 10"
	,"CC IN 8"
	,"CC Locker"
	,"CCOut"
	,"CCUp"
	,"CCUpElev"
	,"CCUpElevPrem"
	,"CCUpPrem"
	,"CCUpVal"
	,"CELL"
	,"Cell Tower"
	,"CellTwr"
	,"Climate Controlled"
	,"Company"
	,"Dehumidified Ground Level"
	,"Drive Up Access"
	,"Drive up with electric"
	," ELEC"
	,"In"
	,"InDriveUp"
	,"Industrial Unit"
	,"In prem"
	,"InUpElev"
	,"InUpLift"
	,"In up lift prem"
	,"InUpPrem"
	,"InUpVal"
	,"In val"
	,"Locker"
	,"Locker 6 FT Upper"
	,"Mailbox"
	,"Mail Box"
	,"NC EXT 10"
	,"NC EXT 8"
	,"NON"
	,"Non-Climate Controlled"
	,"Office"
	,"Office Up"
	,"OffWhse"
	,"Out"
	,"OutHbay"
	,"Out prem"
	,"Outside Parking"
	,"Out val"
	,"PA-Parking"
	,"Parking Space"
	,"PrkgCov"
	,"PrkgCovElec"
	,"PrkgIn"
	,"PrkgUnc"
	,"Prking UnCvd"
	,"RETAIL"
	,"RV"
	,"RV Parking - Covered"
	,"RV Parking - Uncovered"
	," SOUT"
	,"StrFrnt"
	,"Surfboard Storage"
	,"Uncovered Parking"
	,"Upper,ClimateControl"
	,"Vault"
	,"Warehouse Space"
	,"Wine Storage"
]

def descriptions_storquest = [
	"Apartment"
	,"Bike Storage"
	,"Billboard"
	,"Cell Tower"
	,"Climate Controlled Ground Level"
	,"Container"
	,"C-Parking"
	,"Drive Up 24 Hour Access"
	,"Drive Up Access"
	,"Drive Up Access, High Door"
	,"Elevator Access"
	,"Elevator Air Conditioned"
	,"Elevator-Air Cooled"
	,"Elevator - Climate Controlled"
	,"Exterior"
	,"Ground, Air Cooled"
	,"Ground Climate Controlled"
	,"Ground Level"
	,"Ground Level Air Conditioned"
	,"Ground Level - NON Climate Controlled"
	,"Locker Climate Controlled"
	,"Lower"
	,"Lower-Elevator Access"
	,"Lower-Elevator Access CC"
	,"Lower-Ground Level"
	,"Lower- Ground Level CC"
	,"Mailbox"
	,"Mail Box"
	,"Mailbox-Out"
	,"Office"
	,"Office Space"
	,"Outside Parking"
	,"Parking Inside"
	,"Parking Outside"
	,"Parking Space"
	,"Parking Type 1"
	,"Parking Type 2"
	,"Recreational Vehicle"
	,"Retail Office Space"
	,"Roll-Up"
	,"RV Back Lot"
	,"RV Parking"
	,"RV Parking - Covered"
	,"RV Parking - Uncovered"
	,"RV Side Lot"
	,"Special"
	,"Standard"
	,"Surfboard Storage"
	,"Upper"
	,"Upper-Elevator Access"
	,"Upper-Elevator Access CC"
	,"Upper-Ground Level"
	,"Upper-Ground Level CC"
	,"Upstairs-Lift Access"
	,"Wine Storage"
]

def descriptions_ustoreit = [
	"AAA"
	,"BAA"
	,"CBE"
	,"CBN"
	,"CBNM"
	,"CBP"
	,"CDE"
	,"CDEM"
	,"CDN"
	,"CDNA"
	,"CDNB"
	,"CDNE"
	,"CDNM"
	,"CDNO"
	,"CDNU"
	,"CDNW"
	,"CDP"
	,"CDPB"
	,"CDPM"
	,"CDPU"
	,"CEE"
	,"CEEA"
	,"CEEM"
	,"CEN"
	,"CENA"
	,"CENM"
	,"CENO"
	,"CENU"
	,"CEP"
	,"CEPM"
	,"CLE"
	,"CLN"
	,"CLNM"
	,"CON"
	,"CONB"
	,"CONL"
	,"CONM"
	,"CONO"
	,"COP"
	,"CSN"
	,"CSNU"
	,"CXN"
	,"CXNA"
	,"CYN"
	,"CZN"
	,"DDN"
	,"DDNM"
	,"DDNU"
	,"DDP"
	,"Drive Up Access"
	,"HBN"
	,"HBNM"
	,"HDE"
	,"HDN"
	,"HDNM"
	,"HDP"
	,"HDPU"
	,"HEE"
	,"HEN"
	,"HON"
	,"HONM"
	,"HONO"
	,"HSN"
	,"HYN"
	,"LAA"
	,"MAA"
	,"MDN"
	,"NBN"
	,"NDE"
	,"NDEM"
	,"NDN"
	,"NDNA"
	,"NDNB"
	,"NDNE"
	,"NDNM"
	,"NDNO"
	,"NDNU"
	,"NDP"
	,"NDPM"
	,"NDPU"
	,"NEE"
	,"NEN"
	,"NENM"
	,"NENU"
	,"NEP"
	,"NLE"
	,"NLEM"
	,"NLN"
	,"NLNM"
	,"NLP"
	,"NOE"
	,"NOEM"
	,"NON"
	,"NONA"
	,"NONB"
	,"NOND"
	,"NONE"
	,"NONH"
	,"NONL"
	,"NONM"
	,"NONO"
	,"NONU"
	,"NONW"
	,"NOP"
	,"NOPM"
	,"NSE"
	,"NSN"
	,"NSNM"
	,"NWN"
	,"NWNM"
	,"NXN"
	,"NXP"
	,"NYN"
	,"NYP"
	,"OAA"
	,"PCE"
	,"PCN"
	,"PCNA"
	,"PIN"
	,"PON"
	,"PONA"
	,"PONE"
	,"RAA"
	,"TAA"
	,"VEN"
	,"WAA"
]

def descriptions_valuestor = [
	"CCDI"
	,"CCDIE"
	,"CCDIS"
	,"CC Downstairs Electric"
	,"CCUI"
	,"CCUIE"
	,"CCUIS"
	,"Container"
	,"Container Outside"
	,"Irregular Unit"
	,"NCDI"
	,"NCDO"
	,"NCUI"
	,"NCUIE"
	,"PO Box"
	,"RV"
	,"RVC"
	,"RV Parking"
]

println "OPERATOR|DESCRIPTION|METHOD|TEMP CONTROLLED|TEST TEMP CONTROLLED"

// OP: EXTRASPACE
for (int i = 0; i < descriptions_extraspace.size(); i++) {
  def desc = descriptions_extraspace[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "Extraspace| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}

// OP: LOCK UP
for (int i = 0; i < descriptions_lockup.size(); i++) {
  def desc = descriptions_lockup[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "Lock Up| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}

// OP: Metro
for (int i = 0; i < descriptions_metro.size(); i++) {
  def desc = descriptions_metro[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "Metro| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}

// OP: Price
for (int i = 0; i < descriptions_price.size(); i++) {
  def desc = descriptions_price[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "Price| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}

// OP: Simply 
for (int i = 0; i < descriptions_simply.size(); i++) {
  def desc = descriptions_simply[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "Simply| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}

// OP: SST
for (int i = 0; i < descriptions_sst.size(); i++) {
  def desc = descriptions_sst[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "SST| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}

// OP: Storquest
for (int i = 0; i < descriptions_storquest.size(); i++) {
  def desc = descriptions_storquest[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "StorQuest| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}

// OP: U-Store-It
for (int i = 0; i < descriptions_ustoreit.size(); i++) {
  def desc = descriptions_ustoreit[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "U-Store-It| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}

// OP: Value
for (int i = 0; i < descriptions_valuestor.size(); i++) {
  def desc = descriptions_valuestor[i]
  def lookup = UnitTypeLookup.findByDescription (desc)
  if (lookup) {
    println "Value| ${desc}| [Lookup] | ${lookup.tempControlled}"
  }
  else {
    def cc = (desc ==~ /(?i).*climate\s+.*/ && !(desc ==~ /(?i).*non-climate\s+.*/))
    def cc1 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]+.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]+.*/))
    def cc2 = (desc ==~ /(?i).*(heated|climate)[\p{Punct}\s]*.*/ && !(desc ==~ /(?i).*non[ -](heated|climate)[\p{Punct}\s]*.*/))
    println "Lock Up| ${desc}| [Regexp] | ${cc}| ${cc1}| ${cc2}"
  }
}
