package com.centershift.store40;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Mar 08 17:07:55 PST 2011
 * Generated source version: 2.2.9
 */

public final class WSSoap_WSSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.centershift.com/STORE40/", "WS");

    private WSSoap_WSSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WS.WSDL_LOCATION;
        if (args.length > 0) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WS ss = new WS(wsdlURL, SERVICE_NAME);
        WSSoap port = ss.getWSSoap();

        {
            System.out.println("Invoking viewLetterPdf...");
            com.centershift.store40.LookupUserRequest _viewLetterPdf_lookupUserRequest = null;
            com.centershift.store40.ViewLtrRequest _viewLetterPdf_request = null;
            com.centershift.store40.PdfFilePathResponse _viewLetterPdf__return = port.viewLetterPdf(_viewLetterPdf_lookupUserRequest, _viewLetterPdf_request);
            System.out.println("viewLetterPdf.result=" + _viewLetterPdf__return);


        }
        {
            System.out.println("Invoking cancelReservationCashCredit...");
            com.centershift.store40.LookupUserRequest _cancelReservationCashCredit_lookupUserRequest = null;
            com.centershift.store40.CancelReservationRequest _cancelReservationCashCredit_request = null;
            com.centershift.store40.RefundData _cancelReservationCashCredit_refundInfo = null;
            com.centershift.store40.CancelReservationCashCreditResponse2 _cancelReservationCashCredit__return = port.cancelReservationCashCredit(_cancelReservationCashCredit_lookupUserRequest, _cancelReservationCashCredit_request, _cancelReservationCashCredit_refundInfo);
            System.out.println("cancelReservationCashCredit.result=" + _cancelReservationCashCredit__return);


        }
        {
            System.out.println("Invoking getLetterInfo...");
            com.centershift.store40.LookupUserRequest _getLetterInfo_lookupUserRequest = null;
            com.centershift.store40.GetLetterInfoRequest _getLetterInfo_request = null;
            com.centershift.store40.GetLetterInfoResponse2 _getLetterInfo__return = port.getLetterInfo(_getLetterInfo_lookupUserRequest, _getLetterInfo_request);
            System.out.println("getLetterInfo.result=" + _getLetterInfo__return);


        }
        {
            System.out.println("Invoking removePCD...");
            com.centershift.store40.LookupUserRequest _removePCD_lookupUserRequest = null;
            com.centershift.store40.RemovePCDRequest _removePCD_request = null;
            com.centershift.store40.RemovePCDResponse2 _removePCD__return = port.removePCD(_removePCD_lookupUserRequest, _removePCD_request);
            System.out.println("removePCD.result=" + _removePCD__return);


        }
        {
            System.out.println("Invoking exportInsuranceDetail...");
            com.centershift.store40.ExportInsuranceDetailRequest _exportInsuranceDetail_request = null;
            com.centershift.store40.ExportInsuranceDetailResponse2 _exportInsuranceDetail__return = port.exportInsuranceDetail(_exportInsuranceDetail_request);
            System.out.println("exportInsuranceDetail.result=" + _exportInsuranceDetail__return);


        }
        {
            System.out.println("Invoking getUnitData...");
            com.centershift.store40.LookupUserRequest _getUnitData_lookupUserRequest = null;
            com.centershift.store40.GetUnitDataRequest _getUnitData_request = null;
            com.centershift.store40.GetUnitDataResponse2 _getUnitData__return = port.getUnitData(_getUnitData_lookupUserRequest, _getUnitData_request);
            System.out.println("getUnitData.result=" + _getUnitData__return);


        }
        {
            System.out.println("Invoking getScheduledLetterList...");
            com.centershift.store40.LookupUserRequest _getScheduledLetterList_lookupUserRequest = null;
            com.centershift.store40.GetScheduledLetterListRequest _getScheduledLetterList_request = null;
            com.centershift.store40.GetScheduledLetterListResponse2 _getScheduledLetterList__return = port.getScheduledLetterList(_getScheduledLetterList_lookupUserRequest, _getScheduledLetterList_request);
            System.out.println("getScheduledLetterList.result=" + _getScheduledLetterList__return);


        }
        {
            System.out.println("Invoking getSiteAttributes...");
            com.centershift.store40.LookupUserRequest _getSiteAttributes_lookupUserRequest = null;
            com.centershift.store40.GetSiteAttributesRequest _getSiteAttributes_request = null;
            com.centershift.store40.GetSiteAttributesResponse2 _getSiteAttributes__return = port.getSiteAttributes(_getSiteAttributes_lookupUserRequest, _getSiteAttributes_request);
            System.out.println("getSiteAttributes.result=" + _getSiteAttributes__return);


        }
        {
            System.out.println("Invoking viewLeasePdf...");
            com.centershift.store40.LookupUserRequest _viewLeasePdf_lookupUserRequest = null;
            com.centershift.store40.ViewLeaseRequest _viewLeasePdf_request = null;
            com.centershift.store40.PdfFilePathResponse _viewLeasePdf__return = port.viewLeasePdf(_viewLeasePdf_lookupUserRequest, _viewLeasePdf_request);
            System.out.println("viewLeasePdf.result=" + _viewLeasePdf__return);


        }
        {
            System.out.println("Invoking exportRefunds...");
            com.centershift.store40.LookupUserRequest _exportRefunds_lookupUserRequest = null;
            com.centershift.store40.RefundRequest _exportRefunds_request = null;
            com.centershift.store40.RefundResponse _exportRefunds__return = port.exportRefunds(_exportRefunds_lookupUserRequest, _exportRefunds_request);
            System.out.println("exportRefunds.result=" + _exportRefunds__return);


        }
        {
            System.out.println("Invoking getAutoPaySettings...");
            com.centershift.store40.LookupUserRequest _getAutoPaySettings_lookupUserRequest = null;
            com.centershift.store40.GetAutoPaySettingsRequest _getAutoPaySettings_request = null;
            com.centershift.store40.ArrayOfGetAutoPaySettingsResponse _getAutoPaySettings__return = port.getAutoPaySettings(_getAutoPaySettings_lookupUserRequest, _getAutoPaySettings_request);
            System.out.println("getAutoPaySettings.result=" + _getAutoPaySettings__return);


        }
        {
            System.out.println("Invoking getAvailableDiscounts...");
            com.centershift.store40.LookupUserRequest _getAvailableDiscounts_lookupUserRequest = null;
            com.centershift.store40.GetAvailableDiscountsRequest _getAvailableDiscounts_request = null;
            com.centershift.store40.GetAvailableDiscountsResponse2 _getAvailableDiscounts__return = port.getAvailableDiscounts(_getAvailableDiscounts_lookupUserRequest, _getAvailableDiscounts_request);
            System.out.println("getAvailableDiscounts.result=" + _getAvailableDiscounts__return);


        }
        {
            System.out.println("Invoking eUnitStatus...");
            long _eUnitStatus_orgID = 0;
            com.centershift.store40.ArrayOfCFGLOOKUPS _eUnitStatus__return = port.eUnitStatus(_eUnitStatus_orgID);
            System.out.println("eUnitStatus.result=" + _eUnitStatus__return);


        }
        {
            System.out.println("Invoking getUnitFeatures...");
            com.centershift.store40.LookupUserRequest _getUnitFeatures_lookupUserRequest = null;
            com.centershift.store40.GetUnitFeaturesRequest _getUnitFeatures_request = null;
            com.centershift.store40.GetUnitFeaturesResponse2 _getUnitFeatures__return = port.getUnitFeatures(_getUnitFeatures_lookupUserRequest, _getUnitFeatures_request);
            System.out.println("getUnitFeatures.result=" + _getUnitFeatures__return);


        }
        {
            System.out.println("Invoking getContacts...");
            com.centershift.store40.LookupUserRequest _getContacts_lookupUserRequest = null;
            com.centershift.store40.GetContactsRequest _getContacts_request = null;
            com.centershift.store40.GetContactsResponse2 _getContacts__return = port.getContacts(_getContacts_lookupUserRequest, _getContacts_request);
            System.out.println("getContacts.result=" + _getContacts__return);


        }
        {
            System.out.println("Invoking eUnitAttr01...");
            long _eUnitAttr01_orgID = 0;
            com.centershift.store40.ArrayOfCFGLOOKUPS _eUnitAttr01__return = port.eUnitAttr01(_eUnitAttr01_orgID);
            System.out.println("eUnitAttr01.result=" + _eUnitAttr01__return);


        }
        {
            System.out.println("Invoking exrfiuExport...");
            com.centershift.store40.LookupUserRequest _exrfiuExport_lookupUserRequest = null;
            com.centershift.store40.FIURequest _exrfiuExport_request = null;
            com.centershift.store40.EXRFIUResponse _exrfiuExport__return = port.exrfiuExport(_exrfiuExport_lookupUserRequest, _exrfiuExport_request);
            System.out.println("exrfiuExport.result=" + _exrfiuExport__return);


        }
        {
            System.out.println("Invoking getSiteUnitDataFiltered...");
            com.centershift.store40.LookupUserRequest _getSiteUnitDataFiltered_lookupUserRequest = null;
            com.centershift.store40.GetSiteUnitDataRequest _getSiteUnitDataFiltered_request = null;
            com.centershift.store40.GetSiteUnitDataResponse _getSiteUnitDataFiltered__return = port.getSiteUnitDataFiltered(_getSiteUnitDataFiltered_lookupUserRequest, _getSiteUnitDataFiltered_request);
            System.out.println("getSiteUnitDataFiltered.result=" + _getSiteUnitDataFiltered__return);


        }
        {
            System.out.println("Invoking retrievePassword...");
            com.centershift.store40.LookupUserRequest _retrievePassword_lookupUserRequest = null;
            com.centershift.store40.PasswordRequest _retrievePassword_request = null;
            com.centershift.store40.PasswordResponse _retrievePassword__return = port.retrievePassword(_retrievePassword_lookupUserRequest, _retrievePassword_request);
            System.out.println("retrievePassword.result=" + _retrievePassword__return);


        }
        {
            System.out.println("Invoking getUnitStatus...");
            com.centershift.store40.LookupUserRequest _getUnitStatus_lookupUserRequest = null;
            com.centershift.store40.GetUnitStatusRequest _getUnitStatus_request = null;
            com.centershift.store40.GetUnitStatusResponse2 _getUnitStatus__return = port.getUnitStatus(_getUnitStatus_lookupUserRequest, _getUnitStatus_request);
            System.out.println("getUnitStatus.result=" + _getUnitStatus__return);


        }
        {
            System.out.println("Invoking processManualAutoPay...");
            com.centershift.store40.LookupUserRequest _processManualAutoPay_lookupUserRequest = null;
            com.centershift.store40.ProcessManualAutoPayRequest _processManualAutoPay_request = null;
            com.centershift.store40.ProcessManualAutoPayResponse2 _processManualAutoPay__return = port.processManualAutoPay(_processManualAutoPay_lookupUserRequest, _processManualAutoPay_request);
            System.out.println("processManualAutoPay.result=" + _processManualAutoPay__return);


        }
        {
            System.out.println("Invoking cancelReservation...");
            com.centershift.store40.LookupUserRequest _cancelReservation_lookupUserRequest = null;
            com.centershift.store40.CancelReservationRequest _cancelReservation_request = null;
            com.centershift.store40.CancelReservationResponse2 _cancelReservation__return = port.cancelReservation(_cancelReservation_lookupUserRequest, _cancelReservation_request);
            System.out.println("cancelReservation.result=" + _cancelReservation__return);


        }
        {
            System.out.println("Invoking getAssessments...");
            com.centershift.store40.LookupUserRequest _getAssessments_lookupUserRequest = null;
            com.centershift.store40.GetAssessmentsRequest _getAssessments_request = null;
            com.centershift.store40.GetAssessmentsResponse2 _getAssessments__return = port.getAssessments(_getAssessments_lookupUserRequest, _getAssessments_request);
            System.out.println("getAssessments.result=" + _getAssessments__return);


        }
        {
            System.out.println("Invoking makeEcommReservation...");
            com.centershift.store40.LookupUserRequest _makeEcommReservation_lookupUserRequest = null;
            com.centershift.store40.MakeEcommReservationRequest _makeEcommReservation_request = null;
            com.centershift.store40.MakeReservationResponse _makeEcommReservation__return = port.makeEcommReservation(_makeEcommReservation_lookupUserRequest, _makeEcommReservation_request);
            System.out.println("makeEcommReservation.result=" + _makeEcommReservation__return);


        }
        {
            System.out.println("Invoking getSiteUnitData...");
            com.centershift.store40.LookupUserRequest _getSiteUnitData_lookupUserRequest = null;
            com.centershift.store40.GetSiteUnitDataRequest _getSiteUnitData_request = null;
            com.centershift.store40.GetSiteUnitDataResponse _getSiteUnitData__return = port.getSiteUnitData(_getSiteUnitData_lookupUserRequest, _getSiteUnitData_request);
            System.out.println("getSiteUnitData.result=" + _getSiteUnitData__return);


        }
        {
            System.out.println("Invoking getEcommRentalInfo...");
            com.centershift.store40.LookupUserRequest _getEcommRentalInfo_lookupUserRequest = null;
            com.centershift.store40.GetEcommRentalInfoRequest _getEcommRentalInfo_request = null;
            com.centershift.store40.GetEcommRentalInfoResponse2 _getEcommRentalInfo__return = port.getEcommRentalInfo(_getEcommRentalInfo_lookupUserRequest, _getEcommRentalInfo_request);
            System.out.println("getEcommRentalInfo.result=" + _getEcommRentalInfo__return);


        }
        {
            System.out.println("Invoking getAssessmentsByID...");
            com.centershift.store40.LookupUserRequest _getAssessmentsByID_lookupUserRequest = null;
            com.centershift.store40.GetAssessmentsByIDRequest _getAssessmentsByID_request = null;
            com.centershift.store40.GetAssessmentsByIDResponse2 _getAssessmentsByID__return = port.getAssessmentsByID(_getAssessmentsByID_lookupUserRequest, _getAssessmentsByID_request);
            System.out.println("getAssessmentsByID.result=" + _getAssessmentsByID__return);


        }
        {
            System.out.println("Invoking getBaseFees...");
            com.centershift.store40.LookupUserRequest _getBaseFees_lookupUserRequest = null;
            com.centershift.store40.GetBaseFeesRequest _getBaseFees_request = null;
            com.centershift.store40.GetBaseFeesResponse2 _getBaseFees__return = port.getBaseFees(_getBaseFees_lookupUserRequest, _getBaseFees_request);
            System.out.println("getBaseFees.result=" + _getBaseFees__return);


        }
        {
            System.out.println("Invoking updateContact...");
            com.centershift.store40.LookupUserRequest _updateContact_lookupUserRequest = null;
            com.centershift.store40.ContactRequest _updateContact_request = null;
            com.centershift.store40.ContactResponse _updateContact__return = port.updateContact(_updateContact_lookupUserRequest, _updateContact_request);
            System.out.println("updateContact.result=" + _updateContact__return);


        }
        {
            System.out.println("Invoking createNotes...");
            com.centershift.store40.LookupUserRequest _createNotes_lookupUserRequest = null;
            com.centershift.store40.CreateNotesRequest _createNotes_request = null;
            com.centershift.store40.CreateNotesResponse2 _createNotes__return = port.createNotes(_createNotes_lookupUserRequest, _createNotes_request);
            System.out.println("createNotes.result=" + _createNotes__return);


        }
        {
            System.out.println("Invoking getInsuranceProviders...");
            com.centershift.store40.LookupUserRequest _getInsuranceProviders_lookupUserRequest = null;
            com.centershift.store40.GetInsuranceProvidersRequest _getInsuranceProviders_request = null;
            com.centershift.store40.GetInsuranceProvidersResponse2 _getInsuranceProviders__return = port.getInsuranceProviders(_getInsuranceProviders_lookupUserRequest, _getInsuranceProviders_request);
            System.out.println("getInsuranceProviders.result=" + _getInsuranceProviders__return);


        }
        {
            System.out.println("Invoking sendEmail...");
            com.centershift.store40.LookupUserRequest _sendEmail_lookupUserRequest = null;
            com.centershift.store40.SendEmailRequest _sendEmail_request = null;
            com.centershift.store40.SendEmailResponse _sendEmail__return = port.sendEmail(_sendEmail_lookupUserRequest, _sendEmail_request);
            System.out.println("sendEmail.result=" + _sendEmail__return);


        }
        {
            System.out.println("Invoking getTotalDuePastDue...");
            com.centershift.store40.LookupUserRequest _getTotalDuePastDue_lookupUserRequest = null;
            com.centershift.store40.GetTotalDueRequest _getTotalDuePastDue_request = null;
            com.centershift.store40.GetTotalDuePastDueResponse2 _getTotalDuePastDue__return = port.getTotalDuePastDue(_getTotalDuePastDue_lookupUserRequest, _getTotalDuePastDue_request);
            System.out.println("getTotalDuePastDue.result=" + _getTotalDuePastDue__return);


        }
        {
            System.out.println("Invoking fiuSelect...");
            com.centershift.store40.LookupUserRequest _fiuSelect_lookupUserRequest = null;
            com.centershift.store40.FIURequest _fiuSelect_request = null;
            com.centershift.store40.FIUResponse _fiuSelect__return = port.fiuSelect(_fiuSelect_lookupUserRequest, _fiuSelect_request);
            System.out.println("fiuSelect.result=" + _fiuSelect__return);


        }
        {
            System.out.println("Invoking completeUnitTransfer...");
            com.centershift.store40.LookupUserRequest _completeUnitTransfer_lookupUserRequest = null;
            com.centershift.store40.CompleteUnitTransferRequest _completeUnitTransfer_request = null;
            com.centershift.store40.CompleteUnitTransferResponse2 _completeUnitTransfer__return = port.completeUnitTransfer(_completeUnitTransfer_lookupUserRequest, _completeUnitTransfer_request);
            System.out.println("completeUnitTransfer.result=" + _completeUnitTransfer__return);


        }
        {
            System.out.println("Invoking updateReservation...");
            com.centershift.store40.LookupUserRequest _updateReservation_lookupUserRequest = null;
            com.centershift.store40.MakeReservationRequest _updateReservation_request = null;
            com.centershift.store40.MakeReservationResponse _updateReservation__return = port.updateReservation(_updateReservation_lookupUserRequest, _updateReservation_request);
            System.out.println("updateReservation.result=" + _updateReservation__return);


        }
        {
            System.out.println("Invoking getOrgList...");
            com.centershift.store40.LookupUserRequest _getOrgList_lookupUserRequest = null;
            com.centershift.store40.GetOrgListResponse2 _getOrgList__return = port.getOrgList(_getOrgList_lookupUserRequest);
            System.out.println("getOrgList.result=" + _getOrgList__return);


        }
        {
            System.out.println("Invoking verifyLogin...");
            com.centershift.store40.LookupUserRequest _verifyLogin_lookupUserRequest = null;
            com.centershift.store40.PasswordRequest _verifyLogin_request = null;
            com.centershift.store40.PasswordResponse _verifyLogin__return = port.verifyLogin(_verifyLogin_lookupUserRequest, _verifyLogin_request);
            System.out.println("verifyLogin.result=" + _verifyLogin__return);


        }
        {
            System.out.println("Invoking fiuExport...");
            com.centershift.store40.LookupUserRequest _fiuExport_lookupUserRequest = null;
            com.centershift.store40.FIURequest _fiuExport_request = null;
            com.centershift.store40.FIUResponse _fiuExport__return = port.fiuExport(_fiuExport_lookupUserRequest, _fiuExport_request);
            System.out.println("fiuExport.result=" + _fiuExport__return);


        }
        {
            System.out.println("Invoking getLeaseGroupTemplateInfo...");
            com.centershift.store40.LookupUserRequest _getLeaseGroupTemplateInfo_lookupUserRequest = null;
            com.centershift.store40.GetLeaseGroupTemplateInfoRequest _getLeaseGroupTemplateInfo_request = null;
            com.centershift.store40.GetLeaseGroupTemplateInfoResponse2 _getLeaseGroupTemplateInfo__return = port.getLeaseGroupTemplateInfo(_getLeaseGroupTemplateInfo_lookupUserRequest, _getLeaseGroupTemplateInfo_request);
            System.out.println("getLeaseGroupTemplateInfo.result=" + _getLeaseGroupTemplateInfo__return);


        }
        {
            System.out.println("Invoking getRefundTypes...");
            com.centershift.store40.LookupUserRequest _getRefundTypes_lookupUserRequest = null;
            com.centershift.store40.GetRefundTypesRequest _getRefundTypes_request = null;
            com.centershift.store40.GetRefundTypesResponse2 _getRefundTypes__return = port.getRefundTypes(_getRefundTypes_lookupUserRequest, _getRefundTypes_request);
            System.out.println("getRefundTypes.result=" + _getRefundTypes__return);


        }
        {
            System.out.println("Invoking getVersion...");
            java.lang.String _getVersion__return = port.getVersion();
            System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
            System.out.println("Invoking updateUnitStatus...");
            com.centershift.store40.LookupUserRequest _updateUnitStatus_lookupUserRequest = null;
            com.centershift.store40.UpdateUnitStatusRequest _updateUnitStatus_request = null;
            com.centershift.store40.UpdateUnitStatusResponse2 _updateUnitStatus__return = port.updateUnitStatus(_updateUnitStatus_lookupUserRequest, _updateUnitStatus_request);
            System.out.println("updateUnitStatus.result=" + _updateUnitStatus__return);


        }
        {
            System.out.println("Invoking sellRetailWithAccount...");
            com.centershift.store40.LookupUserRequest _sellRetailWithAccount_lookupUserRequest = null;
            com.centershift.store40.SellRetailWithAccountRequest _sellRetailWithAccount_request = null;
            com.centershift.store40.SellRetailWithAccountResponse2 _sellRetailWithAccount__return = port.sellRetailWithAccount(_sellRetailWithAccount_lookupUserRequest, _sellRetailWithAccount_request);
            System.out.println("sellRetailWithAccount.result=" + _sellRetailWithAccount__return);


        }
        {
            System.out.println("Invoking viewReceiptPdf...");
            com.centershift.store40.LookupUserRequest _viewReceiptPdf_lookupUserRequest = null;
            com.centershift.store40.CreateOrViewReceiptRequest _viewReceiptPdf_request = null;
            com.centershift.store40.PdfFilePathResponse _viewReceiptPdf__return = port.viewReceiptPdf(_viewReceiptPdf_lookupUserRequest, _viewReceiptPdf_request);
            System.out.println("viewReceiptPdf.result=" + _viewReceiptPdf__return);


        }
        {
            System.out.println("Invoking getReceiptTemplateInfo...");
            com.centershift.store40.LookupUserRequest _getReceiptTemplateInfo_lookupUserRequest = null;
            com.centershift.store40.GetLtrTemplateInfoRequest _getReceiptTemplateInfo_request = null;
            com.centershift.store40.GetLtrTemplateInfoResponse _getReceiptTemplateInfo__return = port.getReceiptTemplateInfo(_getReceiptTemplateInfo_lookupUserRequest, _getReceiptTemplateInfo_request);
            System.out.println("getReceiptTemplateInfo.result=" + _getReceiptTemplateInfo__return);


        }
        {
            System.out.println("Invoking addNewAddress...");
            com.centershift.store40.LookupUserRequest _addNewAddress_lookupUserRequest = null;
            com.centershift.store40.ContactAddress _addNewAddress_request = null;
            com.centershift.store40.AddressResponse _addNewAddress__return = port.addNewAddress(_addNewAddress_lookupUserRequest, _addNewAddress_request);
            System.out.println("addNewAddress.result=" + _addNewAddress__return);


        }
        {
            System.out.println("Invoking updateUnitStatusExpanded...");
            com.centershift.store40.LookupUserRequest _updateUnitStatusExpanded_lookupUserRequest = null;
            com.centershift.store40.UpdateUnitStatusExpandedRequest _updateUnitStatusExpanded_request = null;
            com.centershift.store40.UpdateUnitStatusExpandedResponse2 _updateUnitStatusExpanded__return = port.updateUnitStatusExpanded(_updateUnitStatusExpanded_lookupUserRequest, _updateUnitStatusExpanded_request);
            System.out.println("updateUnitStatusExpanded.result=" + _updateUnitStatusExpanded__return);


        }
        {
            System.out.println("Invoking updateEcommPassword...");
            com.centershift.store40.LookupUserRequest _updateEcommPassword_lookupUserRequest = null;
            com.centershift.store40.UpdateEcommPasswordRequest _updateEcommPassword_request = null;
            com.centershift.store40.UpdateEcommPasswordResponse2 _updateEcommPassword__return = port.updateEcommPassword(_updateEcommPassword_lookupUserRequest, _updateEcommPassword_request);
            System.out.println("updateEcommPassword.result=" + _updateEcommPassword__return);


        }
        {
            System.out.println("Invoking resetServicesPassword...");
            com.centershift.store40.LookupUserRequest _resetServicesPassword_lookupUserRequest = null;
            com.centershift.store40.ResetServicesPasswordRequest _resetServicesPassword_request = null;
            com.centershift.store40.ResetServicesPasswordResponse2 _resetServicesPassword__return = port.resetServicesPassword(_resetServicesPassword_lookupUserRequest, _resetServicesPassword_request);
            System.out.println("resetServicesPassword.result=" + _resetServicesPassword__return);


        }
        {
            System.out.println("Invoking getRefunds...");
            com.centershift.store40.LookupUserRequest _getRefunds_lookupUserRequest = null;
            com.centershift.store40.RefundRequest _getRefunds_request = null;
            com.centershift.store40.RefundResponse _getRefunds__return = port.getRefunds(_getRefunds_lookupUserRequest, _getRefunds_request);
            System.out.println("getRefunds.result=" + _getRefunds__return);


        }
        {
            System.out.println("Invoking getReservations...");
            com.centershift.store40.LookupUserRequest _getReservations_lookupUserRequest = null;
            com.centershift.store40.GetReservationsRequest _getReservations_request = null;
            com.centershift.store40.GetReservationsResponse2 _getReservations__return = port.getReservations(_getReservations_lookupUserRequest, _getReservations_request);
            System.out.println("getReservations.result=" + _getReservations__return);


        }
        {
            System.out.println("Invoking rentalActivity...");
            com.centershift.store40.LookupUserRequest _rentalActivity_lookupUserRequest = null;
            com.centershift.store40.RentalActivityRequest _rentalActivity_request = null;
            com.centershift.store40.RentalActivityResponse2 _rentalActivity__return = port.rentalActivity(_rentalActivity_lookupUserRequest, _rentalActivity_request);
            System.out.println("rentalActivity.result=" + _rentalActivity__return);


        }
        {
            System.out.println("Invoking addUpdateAutoPaySettings...");
            com.centershift.store40.LookupUserRequest _addUpdateAutoPaySettings_lookupUserRequest = null;
            com.centershift.store40.AddUpdateAutoPaySettingsRequest _addUpdateAutoPaySettings_request = null;
            com.centershift.store40.AddUpdateAutoPaySettingsResponse2 _addUpdateAutoPaySettings__return = port.addUpdateAutoPaySettings(_addUpdateAutoPaySettings_lookupUserRequest, _addUpdateAutoPaySettings_request);
            System.out.println("addUpdateAutoPaySettings.result=" + _addUpdateAutoPaySettings__return);


        }
        {
            System.out.println("Invoking getPrimaryRentalInfo...");
            com.centershift.store40.LookupUserRequest _getPrimaryRentalInfo_lookupUserRequest = null;
            com.centershift.store40.GetPrimaryRentalInfoRequest _getPrimaryRentalInfo_request = null;
            com.centershift.store40.GetPrimaryRentalInfoResponse2 _getPrimaryRentalInfo__return = port.getPrimaryRentalInfo(_getPrimaryRentalInfo_lookupUserRequest, _getPrimaryRentalInfo_request);
            System.out.println("getPrimaryRentalInfo.result=" + _getPrimaryRentalInfo__return);


        }
        {
            System.out.println("Invoking addDeposit...");
            com.centershift.store40.LookupUserRequest _addDeposit_lookupUserRequest = null;
            com.centershift.store40.AddDepositRequest _addDeposit_request = null;
            com.centershift.store40.AddDepositResponse2 _addDeposit__return = port.addDeposit(_addDeposit_lookupUserRequest, _addDeposit_request);
            System.out.println("addDeposit.result=" + _addDeposit__return);


        }
        {
            System.out.println("Invoking addUpdatePCD...");
            com.centershift.store40.LookupUserRequest _addUpdatePCD_lookupUserRequest = null;
            com.centershift.store40.AddUpdatePCDRequest _addUpdatePCD_request = null;
            com.centershift.store40.AddUpdatePCDResponse2 _addUpdatePCD__return = port.addUpdatePCD(_addUpdatePCD_lookupUserRequest, _addUpdatePCD_request);
            System.out.println("addUpdatePCD.result=" + _addUpdatePCD__return);


        }
        {
            System.out.println("Invoking voidMoveIn...");
            com.centershift.store40.LookupUserRequest _voidMoveIn_lookupUserRequest = null;
            com.centershift.store40.VoidMoveInRequest _voidMoveIn_request = null;
            com.centershift.store40.VoidMoveInResponse2 _voidMoveIn__return = port.voidMoveIn(_voidMoveIn_lookupUserRequest, _voidMoveIn_request);
            System.out.println("voidMoveIn.result=" + _voidMoveIn__return);


        }
        {
            System.out.println("Invoking addUpdateMerchandiseItems...");
            com.centershift.store40.LookupUserRequest _addUpdateMerchandiseItems_lookupUserRequest = null;
            com.centershift.store40.AddUpdateMerchandiseItemsRequest _addUpdateMerchandiseItems_request = null;
            com.centershift.store40.AddUpdateMerchandiseItemsResponse2 _addUpdateMerchandiseItems__return = port.addUpdateMerchandiseItems(_addUpdateMerchandiseItems_lookupUserRequest, _addUpdateMerchandiseItems_request);
            System.out.println("addUpdateMerchandiseItems.result=" + _addUpdateMerchandiseItems__return);


        }
        {
            System.out.println("Invoking updateRentRate...");
            com.centershift.store40.LookupUserRequest _updateRentRate_lookupUserRequest = null;
            com.centershift.store40.UpdateRentRateRequest _updateRentRate_request = null;
            com.centershift.store40.UpdateRentRateResponse2 _updateRentRate__return = port.updateRentRate(_updateRentRate_lookupUserRequest, _updateRentRate_request);
            System.out.println("updateRentRate.result=" + _updateRentRate__return);


        }
        {
            System.out.println("Invoking eUnitFeatures...");
            long _eUnitFeatures_orgID = 0;
            com.centershift.store40.ArrayOfCFGLOOKUPS _eUnitFeatures__return = port.eUnitFeatures(_eUnitFeatures_orgID);
            System.out.println("eUnitFeatures.result=" + _eUnitFeatures__return);


        }
        {
            System.out.println("Invoking sellRetailNoAccount...");
            com.centershift.store40.LookupUserRequest _sellRetailNoAccount_lookupUserRequest = null;
            com.centershift.store40.SellRetailNoAccountRequest _sellRetailNoAccount_request = null;
            com.centershift.store40.SellRetailNoAccountResponse2 _sellRetailNoAccount__return = port.sellRetailNoAccount(_sellRetailNoAccount_lookupUserRequest, _sellRetailNoAccount_request);
            System.out.println("sellRetailNoAccount.result=" + _sellRetailNoAccount__return);


        }
        {
            System.out.println("Invoking sendEmailContact...");
            com.centershift.store40.LookupUserRequest _sendEmailContact_lookupUserRequest = null;
            com.centershift.store40.SendEmailContactRequest _sendEmailContact_request = null;
            com.centershift.store40.SendEmailResponse _sendEmailContact__return = port.sendEmailContact(_sendEmailContact_lookupUserRequest, _sendEmailContact_request);
            System.out.println("sendEmailContact.result=" + _sendEmailContact__return);


        }
        {
            System.out.println("Invoking fiuReInt...");
            com.centershift.store40.LookupUserRequest _fiuReInt_lookupUserRequest = null;
            com.centershift.store40.FIURequest _fiuReInt_request = null;
            com.centershift.store40.FIUResponse _fiuReInt__return = port.fiuReInt(_fiuReInt_lookupUserRequest, _fiuReInt_request);
            System.out.println("fiuReInt.result=" + _fiuReInt__return);


        }
        {
            System.out.println("Invoking createNewAccount...");
            com.centershift.store40.LookupUserRequest _createNewAccount_lookupUserRequest = null;
            com.centershift.store40.CreateNewAccountRequest _createNewAccount_request = null;
            com.centershift.store40.StructCreateAccount _createNewAccount__return = port.createNewAccount(_createNewAccount_lookupUserRequest, _createNewAccount_request);
            System.out.println("createNewAccount.result=" + _createNewAccount__return);


        }
        {
            System.out.println("Invoking eUnitAccessType...");
            long _eUnitAccessType_orgID = 0;
            com.centershift.store40.ArrayOfCFGLOOKUPS _eUnitAccessType__return = port.eUnitAccessType(_eUnitAccessType_orgID);
            System.out.println("eUnitAccessType.result=" + _eUnitAccessType__return);


        }
        {
            System.out.println("Invoking scheduledLetter...");
            com.centershift.store40.LookupUserRequest _scheduledLetter_lookupUserRequest = null;
            com.centershift.store40.ScheduledLetterRequest _scheduledLetter_request = null;
            com.centershift.store40.ScheduledLetterResponse2 _scheduledLetter__return = port.scheduledLetter(_scheduledLetter_lookupUserRequest, _scheduledLetter_request);
            System.out.println("scheduledLetter.result=" + _scheduledLetter__return);


        }
        {
            System.out.println("Invoking getProcessingMailRules...");
            com.centershift.store40.LookupUserRequest _getProcessingMailRules_lookupUserRequest = null;
            com.centershift.store40.GetRulesRequest _getProcessingMailRules_request = null;
            com.centershift.store40.GetRulesResponse _getProcessingMailRules__return = port.getProcessingMailRules(_getProcessingMailRules_lookupUserRequest, _getProcessingMailRules_request);
            System.out.println("getProcessingMailRules.result=" + _getProcessingMailRules__return);


        }
        {
            System.out.println("Invoking getAuctions...");
            com.centershift.store40.LookupUserRequest _getAuctions_lookupUserRequest = null;
            com.centershift.store40.GetAuctionsRequest _getAuctions_request = null;
            com.centershift.store40.GetAuctionsResponse2 _getAuctions__return = port.getAuctions(_getAuctions_lookupUserRequest, _getAuctions_request);
            System.out.println("getAuctions.result=" + _getAuctions__return);


        }
        {
            System.out.println("Invoking getSiteList...");
            com.centershift.store40.LookupUserRequest _getSiteList_lookupUserRequest = null;
            com.centershift.store40.GetSiteListRequest _getSiteList_request = null;
            com.centershift.store40.GetSiteListResponse2 _getSiteList__return = port.getSiteList(_getSiteList_lookupUserRequest, _getSiteList_request);
            System.out.println("getSiteList.result=" + _getSiteList__return);


        }
        {
            System.out.println("Invoking auctionEndRental...");
            com.centershift.store40.LookupUserRequest _auctionEndRental_lookupUserRequest = null;
            com.centershift.store40.AuctionEndRentalRequest _auctionEndRental_request = null;
            com.centershift.store40.AuctionEndRentalResponse2 _auctionEndRental__return = port.auctionEndRental(_auctionEndRental_lookupUserRequest, _auctionEndRental_request);
            System.out.println("auctionEndRental.result=" + _auctionEndRental__return);


        }
        {
            System.out.println("Invoking getSiteTasks...");
            com.centershift.store40.LookupUserRequest _getSiteTasks_lookupUserRequest = null;
            com.centershift.store40.GetSiteTasksRequest _getSiteTasks_request = null;
            com.centershift.store40.GetSiteTasksResponse2 _getSiteTasks__return = port.getSiteTasks(_getSiteTasks_lookupUserRequest, _getSiteTasks_request);
            System.out.println("getSiteTasks.result=" + _getSiteTasks__return);


        }
        {
            System.out.println("Invoking eInquirySource...");
            long _eInquirySource_orgID = 0;
            com.centershift.store40.ArrayOfCFGLOOKUPS _eInquirySource__return = port.eInquirySource(_eInquirySource_orgID);
            System.out.println("eInquirySource.result=" + _eInquirySource__return);


        }
        {
            System.out.println("Invoking sendEmailWithUnit...");
            com.centershift.store40.LookupUserRequest _sendEmailWithUnit_lookupUserRequest = null;
            com.centershift.store40.SendEmailWithUnitRequest _sendEmailWithUnit_request = null;
            com.centershift.store40.SendEmailResponse _sendEmailWithUnit__return = port.sendEmailWithUnit(_sendEmailWithUnit_lookupUserRequest, _sendEmailWithUnit_request);
            System.out.println("sendEmailWithUnit.result=" + _sendEmailWithUnit__return);


        }
        {
            System.out.println("Invoking getRentalLedger...");
            com.centershift.store40.LookupUserRequest _getRentalLedger_lookupUserRequest = null;
            com.centershift.store40.GetRentalLedgerRequest _getRentalLedger_requestVal = null;
            javax.xml.ws.Holder<com.centershift.store40.GetRentalLedgerRequest> _getRentalLedger_request = new javax.xml.ws.Holder<com.centershift.store40.GetRentalLedgerRequest>(_getRentalLedger_requestVal);
            javax.xml.ws.Holder<com.centershift.store40.GetRentalLedgerResponse2> _getRentalLedger_getRentalLedgerResult = new javax.xml.ws.Holder<com.centershift.store40.GetRentalLedgerResponse2>();
            port.getRentalLedger(_getRentalLedger_lookupUserRequest, _getRentalLedger_request, _getRentalLedger_getRentalLedgerResult);

            System.out.println("getRentalLedger._getRentalLedger_request=" + _getRentalLedger_request.value);
            System.out.println("getRentalLedger._getRentalLedger_getRentalLedgerResult=" + _getRentalLedger_getRentalLedgerResult.value);

        }
        {
            System.out.println("Invoking getRetailRefundAmount...");
            com.centershift.store40.LookupUserRequest _getRetailRefundAmount_lookupUserRequest = null;
            com.centershift.store40.GetRetailRefundAmountRequest _getRetailRefundAmount_request = null;
            com.centershift.store40.GetRetailRefundAmountResponse2 _getRetailRefundAmount__return = port.getRetailRefundAmount(_getRetailRefundAmount_lookupUserRequest, _getRetailRefundAmount_request);
            System.out.println("getRetailRefundAmount.result=" + _getRetailRefundAmount__return);


        }
        {
            System.out.println("Invoking sendEmailWithPassword...");
            com.centershift.store40.LookupUserRequest _sendEmailWithPassword_lookupUserRequest = null;
            com.centershift.store40.SendEmailWithPasswordRequest _sendEmailWithPassword_request = null;
            com.centershift.store40.SendEmailResponse _sendEmailWithPassword__return = port.sendEmailWithPassword(_sendEmailWithPassword_lookupUserRequest, _sendEmailWithPassword_request);
            System.out.println("sendEmailWithPassword.result=" + _sendEmailWithPassword__return);


        }
        {
            System.out.println("Invoking getAvailableCredits...");
            com.centershift.store40.LookupUserRequest _getAvailableCredits_lookupUserRequest = null;
            com.centershift.store40.GetAvailableCreditsRequest _getAvailableCredits_request = null;
            com.centershift.store40.GetAvailableCreditsResponse2 _getAvailableCredits__return = port.getAvailableCredits(_getAvailableCredits_lookupUserRequest, _getAvailableCredits_request);
            System.out.println("getAvailableCredits.result=" + _getAvailableCredits__return);


        }
        {
            System.out.println("Invoking createAuctionEndRental...");
            com.centershift.store40.LookupUserRequest _createAuctionEndRental_lookupUserRequest = null;
            com.centershift.store40.CreateAuctionEndRentalRequest _createAuctionEndRental_request = null;
            com.centershift.store40.CreateAuctionEndRentalResponse2 _createAuctionEndRental__return = port.createAuctionEndRental(_createAuctionEndRental_lookupUserRequest, _createAuctionEndRental_request);
            System.out.println("createAuctionEndRental.result=" + _createAuctionEndRental__return);


        }
        {
            System.out.println("Invoking getAppliedServices...");
            com.centershift.store40.LookupUserRequest _getAppliedServices_lookupUserRequest = null;
            com.centershift.store40.GetAppliedServicesRequest _getAppliedServices_request = null;
            com.centershift.store40.GetAppliedServicesResponse2 _getAppliedServices__return = port.getAppliedServices(_getAppliedServices_lookupUserRequest, _getAppliedServices_request);
            System.out.println("getAppliedServices.result=" + _getAppliedServices__return);


        }
        {
            System.out.println("Invoking getCashCredits...");
            com.centershift.store40.LookupUserRequest _getCashCredits_lookupUserRequest = null;
            com.centershift.store40.GetCashCreditsRequest _getCashCredits_request = null;
            com.centershift.store40.GetCashCreditsResponse2 _getCashCredits__return = port.getCashCredits(_getCashCredits_lookupUserRequest, _getCashCredits_request);
            System.out.println("getCashCredits.result=" + _getCashCredits__return);


        }
        {
            System.out.println("Invoking getAuctionRentals...");
            com.centershift.store40.LookupUserRequest _getAuctionRentals_lookupUserRequest = null;
            com.centershift.store40.GetAuctionRentalsRequest _getAuctionRentals_request = null;
            com.centershift.store40.GetAuctionRentalsResponse2 _getAuctionRentals__return = port.getAuctionRentals(_getAuctionRentals_lookupUserRequest, _getAuctionRentals_request);
            System.out.println("getAuctionRentals.result=" + _getAuctionRentals__return);


        }
        {
            System.out.println("Invoking endRental...");
            com.centershift.store40.LookupUserRequest _endRental_lookupUserRequest = null;
            com.centershift.store40.EndRentalRequest _endRental_request = null;
            com.centershift.store40.EndRentalResponse2 _endRental__return = port.endRental(_endRental_lookupUserRequest, _endRental_request);
            System.out.println("endRental.result=" + _endRental__return);


        }
        {
            System.out.println("Invoking updateRentalSettings...");
            com.centershift.store40.LookupUserRequest _updateRentalSettings_lookupUserRequest = null;
            com.centershift.store40.UpdateRentalSettingsRequest _updateRentalSettings_request = null;
            com.centershift.store40.UpdateRentalSettingsResponse2 _updateRentalSettings__return = port.updateRentalSettings(_updateRentalSettings_lookupUserRequest, _updateRentalSettings_request);
            System.out.println("updateRentalSettings.result=" + _updateRentalSettings__return);


        }
        {
            System.out.println("Invoking createSiteTask...");
            com.centershift.store40.LookupUserRequest _createSiteTask_lookupUserRequest = null;
            com.centershift.store40.CreateSiteTaskRequest _createSiteTask_createSiteTaskReq = null;
            com.centershift.store40.CreateSiteTaskResponse2 _createSiteTask__return = port.createSiteTask(_createSiteTask_lookupUserRequest, _createSiteTask_createSiteTaskReq);
            System.out.println("createSiteTask.result=" + _createSiteTask__return);


        }
        {
            System.out.println("Invoking createLetter...");
            com.centershift.store40.LookupUserRequest _createLetter_lookupUserRequest = null;
            com.centershift.store40.CreateOrViewLtrRequest _createLetter_request = null;
            com.centershift.store40.TntLtrNumResponse _createLetter__return = port.createLetter(_createLetter_lookupUserRequest, _createLetter_request);
            System.out.println("createLetter.result=" + _createLetter__return);


        }
        {
            System.out.println("Invoking eUnitClimate...");
            long _eUnitClimate_orgID = 0;
            com.centershift.store40.ArrayOfCFGLOOKUPS _eUnitClimate__return = port.eUnitClimate(_eUnitClimate_orgID);
            System.out.println("eUnitClimate.result=" + _eUnitClimate__return);


        }
        {
            System.out.println("Invoking getScheduledFees...");
            com.centershift.store40.LookupUserRequest _getScheduledFees_lookupUserRequest = null;
            com.centershift.store40.GetScheduledFeesRequest _getScheduledFees_request = null;
            com.centershift.store40.GetScheduledFeesResponse2 _getScheduledFees__return = port.getScheduledFees(_getScheduledFees_lookupUserRequest, _getScheduledFees_request);
            System.out.println("getScheduledFees.result=" + _getScheduledFees__return);


        }
        {
            System.out.println("Invoking applyPCDs...");
            com.centershift.store40.LookupUserRequest _applyPCDs_lookupUserRequest = null;
            com.centershift.store40.ApplyPCDsRequest _applyPCDs_request = null;
            com.centershift.store40.ApplyPCDsResponse2 _applyPCDs__return = port.applyPCDs(_applyPCDs_lookupUserRequest, _applyPCDs_request);
            System.out.println("applyPCDs.result=" + _applyPCDs__return);


        }
        {
            System.out.println("Invoking updateAuction...");
            com.centershift.store40.LookupUserRequest _updateAuction_lookupUserRequest = null;
            com.centershift.store40.UpdateAuctionRequest _updateAuction_request = null;
            com.centershift.store40.CreateAuctionResponse _updateAuction__return = port.updateAuction(_updateAuction_lookupUserRequest, _updateAuction_request);
            System.out.println("updateAuction.result=" + _updateAuction__return);


        }
        {
            System.out.println("Invoking createDemoUser...");
            com.centershift.store40.LookupUserRequest _createDemoUser_lookupUserRequest = null;
            com.centershift.store40.CreateDemoUserRequest _createDemoUser_request = null;
            com.centershift.store40.CreateDemoUserResponse2 _createDemoUser__return = port.createDemoUser(_createDemoUser_lookupUserRequest, _createDemoUser_request);
            System.out.println("createDemoUser.result=" + _createDemoUser__return);


        }
        {
            System.out.println("Invoking getTemplateIdRules...");
            com.centershift.store40.LookupUserRequest _getTemplateIdRules_lookupUserRequest = null;
            com.centershift.store40.GetRulesRequest _getTemplateIdRules_request = null;
            com.centershift.store40.GetRulesResponse _getTemplateIdRules__return = port.getTemplateIdRules(_getTemplateIdRules_lookupUserRequest, _getTemplateIdRules_request);
            System.out.println("getTemplateIdRules.result=" + _getTemplateIdRules__return);


        }
        {
            System.out.println("Invoking getChannelList...");
            com.centershift.store40.LookupUserRequest _getChannelList_lookupUserRequest = null;
            com.centershift.store40.GetChannelListRequest _getChannelList_request = null;
            com.centershift.store40.GetChannelListResponse2 _getChannelList__return = port.getChannelList(_getChannelList_lookupUserRequest, _getChannelList_request);
            System.out.println("getChannelList.result=" + _getChannelList__return);


        }
        {
            System.out.println("Invoking getWaiveVoidFeeStats...");
            com.centershift.store40.LookupUserRequest _getWaiveVoidFeeStats_lookupUserRequest = null;
            com.centershift.store40.GetWaiveVoidFeeStatsRequest _getWaiveVoidFeeStats_request = null;
            com.centershift.store40.GetWaiveVoidFeeStatsResponse2 _getWaiveVoidFeeStats__return = port.getWaiveVoidFeeStats(_getWaiveVoidFeeStats_lookupUserRequest, _getWaiveVoidFeeStats_request);
            System.out.println("getWaiveVoidFeeStats.result=" + _getWaiveVoidFeeStats__return);


        }
        {
            System.out.println("Invoking returnRetailItems...");
            com.centershift.store40.LookupUserRequest _returnRetailItems_lookupUserRequest = null;
            com.centershift.store40.ReturnRetailItemsRequest _returnRetailItems_request = null;
            com.centershift.store40.ReturnRetailItemsResponse2 _returnRetailItems__return = port.returnRetailItems(_returnRetailItems_lookupUserRequest, _returnRetailItems_request);
            System.out.println("returnRetailItems.result=" + _returnRetailItems__return);


        }
        {
            System.out.println("Invoking rollbackUnitTransfer...");
            com.centershift.store40.LookupUserRequest _rollbackUnitTransfer_lookupUserRequest = null;
            com.centershift.store40.RollbackUnitTransferRequest _rollbackUnitTransfer_request = null;
            com.centershift.store40.RollbackUnitTransferResponse2 _rollbackUnitTransfer__return = port.rollbackUnitTransfer(_rollbackUnitTransfer_lookupUserRequest, _rollbackUnitTransfer_request);
            System.out.println("rollbackUnitTransfer.result=" + _rollbackUnitTransfer__return);


        }
        {
            System.out.println("Invoking updateLeasePeriod...");
            com.centershift.store40.LookupUserRequest _updateLeasePeriod_lookupUserRequest = null;
            com.centershift.store40.UpdateLeasePeriodRequest _updateLeasePeriod_request = null;
            com.centershift.store40.UpdateLeasePeriodResponse2 _updateLeasePeriod__return = port.updateLeasePeriod(_updateLeasePeriod_lookupUserRequest, _updateLeasePeriod_request);
            System.out.println("updateLeasePeriod.result=" + _updateLeasePeriod__return);


        }
        {
            System.out.println("Invoking getSiteDetails...");
            com.centershift.store40.LookupUserRequest _getSiteDetails_lookupUserRequest = null;
            com.centershift.store40.GetSiteDetailsRequest _getSiteDetails_request = null;
            com.centershift.store40.GetSiteDetailsResponse2 _getSiteDetails__return = port.getSiteDetails(_getSiteDetails_lookupUserRequest, _getSiteDetails_request);
            System.out.println("getSiteDetails.result=" + _getSiteDetails__return);


        }
        {
            System.out.println("Invoking getRentalInfo...");
            com.centershift.store40.LookupUserRequest _getRentalInfo_lookupUserRequest = null;
            com.centershift.store40.GetRentalInfoRequest _getRentalInfo_request = null;
            com.centershift.store40.GetRentalInfoResponse2 _getRentalInfo__return = port.getRentalInfo(_getRentalInfo_lookupUserRequest, _getRentalInfo_request);
            System.out.println("getRentalInfo.result=" + _getRentalInfo__return);


        }
        {
            System.out.println("Invoking voidFee...");
            com.centershift.store40.LookupUserRequest _voidFee_lookupUserRequest = null;
            com.centershift.store40.VoidFeeRequest _voidFee_request = null;
            com.centershift.store40.VoidFeeResponse2 _voidFee__return = port.voidFee(_voidFee_lookupUserRequest, _voidFee_request);
            System.out.println("voidFee.result=" + _voidFee__return);


        }
        {
            System.out.println("Invoking versResAssessBundle...");
            com.centershift.store40.LookupUserRequest _versResAssessBundle_lookupUserRequest = null;
            com.centershift.store40.VersResAssessBundleRequest _versResAssessBundle_request = null;
            com.centershift.store40.VersResAssessBundleResponse2 _versResAssessBundle__return = port.versResAssessBundle(_versResAssessBundle_lookupUserRequest, _versResAssessBundle_request);
            System.out.println("versResAssessBundle.result=" + _versResAssessBundle__return);


        }
        {
            System.out.println("Invoking makePaymentByAssessment...");
            com.centershift.store40.LookupUserRequest _makePaymentByAssessment_lookupUserRequest = null;
            com.centershift.store40.MakePaymentByAssessmentRequest _makePaymentByAssessment_request = null;
            com.centershift.store40.MakePaymentResponse _makePaymentByAssessment__return = port.makePaymentByAssessment(_makePaymentByAssessment_lookupUserRequest, _makePaymentByAssessment_request);
            System.out.println("makePaymentByAssessment.result=" + _makePaymentByAssessment__return);


        }
        {
            System.out.println("Invoking getLetterTemplateInfo...");
            com.centershift.store40.LookupUserRequest _getLetterTemplateInfo_lookupUserRequest = null;
            com.centershift.store40.GetLtrTemplateInfoRequest _getLetterTemplateInfo_request = null;
            com.centershift.store40.GetLtrTemplateInfoResponse _getLetterTemplateInfo__return = port.getLetterTemplateInfo(_getLetterTemplateInfo_lookupUserRequest, _getLetterTemplateInfo_request);
            System.out.println("getLetterTemplateInfo.result=" + _getLetterTemplateInfo__return);


        }
        {
            System.out.println("Invoking getEligibleAuctionRentals...");
            com.centershift.store40.LookupUserRequest _getEligibleAuctionRentals_lookupUserRequest = null;
            com.centershift.store40.GetEligibleAuctionRentalsRequest _getEligibleAuctionRentals_request = null;
            com.centershift.store40.GetEligibleAuctionRentalsResponse2 _getEligibleAuctionRentals__return = port.getEligibleAuctionRentals(_getEligibleAuctionRentals_lookupUserRequest, _getEligibleAuctionRentals_request);
            System.out.println("getEligibleAuctionRentals.result=" + _getEligibleAuctionRentals__return);


        }
        {
            System.out.println("Invoking addRentalsToAuction...");
            com.centershift.store40.LookupUserRequest _addRentalsToAuction_lookupUserRequest = null;
            com.centershift.store40.AddRentalsToAuctionRequest _addRentalsToAuction_request = null;
            com.centershift.store40.AddRentalToAuctionResponse _addRentalsToAuction__return = port.addRentalsToAuction(_addRentalsToAuction_lookupUserRequest, _addRentalsToAuction_request);
            System.out.println("addRentalsToAuction.result=" + _addRentalsToAuction__return);


        }
        {
            System.out.println("Invoking getPartialPayRules...");
            com.centershift.store40.LookupUserRequest _getPartialPayRules_lookupUserRequest = null;
            com.centershift.store40.GetPartialPayRulesRequest _getPartialPayRules_request = null;
            com.centershift.store40.GetPartialPayRulesResponse2 _getPartialPayRules__return = port.getPartialPayRules(_getPartialPayRules_lookupUserRequest, _getPartialPayRules_request);
            System.out.println("getPartialPayRules.result=" + _getPartialPayRules__return);


        }
        {
            System.out.println("Invoking reassignRental...");
            com.centershift.store40.LookupUserRequest _reassignRental_lookupUserRequest = null;
            com.centershift.store40.ReassignRentalRequest _reassignRental_request = null;
            com.centershift.store40.ReassignRentalResponse2 _reassignRental__return = port.reassignRental(_reassignRental_lookupUserRequest, _reassignRental_request);
            System.out.println("reassignRental.result=" + _reassignRental__return);


        }
        {
            System.out.println("Invoking getEstimatedRefund...");
            com.centershift.store40.LookupUserRequest _getEstimatedRefund_lookupUserRequest = null;
            com.centershift.store40.GetEstimatedRefundRequest _getEstimatedRefund_request = null;
            com.centershift.store40.GetEstimatedRefundResponse2 _getEstimatedRefund__return = port.getEstimatedRefund(_getEstimatedRefund_lookupUserRequest, _getEstimatedRefund_request);
            System.out.println("getEstimatedRefund.result=" + _getEstimatedRefund__return);


        }
        {
            System.out.println("Invoking eUnitClass...");
            long _eUnitClass_siteID = 0;
            com.centershift.store40.ArrayOfSITECLASSES _eUnitClass__return = port.eUnitClass(_eUnitClass_siteID);
            System.out.println("eUnitClass.result=" + _eUnitClass__return);


        }
        {
            System.out.println("Invoking getAvailableServices...");
            com.centershift.store40.LookupUserRequest _getAvailableServices_lookupUserRequest = null;
            com.centershift.store40.GetAvailableServicesRequest _getAvailableServices_request = null;
            com.centershift.store40.GetAvailableServicesResponse2 _getAvailableServices__return = port.getAvailableServices(_getAvailableServices_lookupUserRequest, _getAvailableServices_request);
            System.out.println("getAvailableServices.result=" + _getAvailableServices__return);


        }
        {
            System.out.println("Invoking getLeaseTemplateInfo...");
            com.centershift.store40.LookupUserRequest _getLeaseTemplateInfo_lookupUserRequest = null;
            com.centershift.store40.GetLeaseTemplateInfoRequest _getLeaseTemplateInfo_request = null;
            com.centershift.store40.GetLeaseTemplateInfoResponse2 _getLeaseTemplateInfo__return = port.getLeaseTemplateInfo(_getLeaseTemplateInfo_lookupUserRequest, _getLeaseTemplateInfo_request);
            System.out.println("getLeaseTemplateInfo.result=" + _getLeaseTemplateInfo__return);


        }
        {
            System.out.println("Invoking sellRetailNoAccountMultiple...");
            com.centershift.store40.LookupUserRequest _sellRetailNoAccountMultiple_lookupUserRequest = null;
            com.centershift.store40.SellRetailNoAccountMultipleRequest _sellRetailNoAccountMultiple_request = null;
            com.centershift.store40.SellRetailMultipleResponse _sellRetailNoAccountMultiple__return = port.sellRetailNoAccountMultiple(_sellRetailNoAccountMultiple_lookupUserRequest, _sellRetailNoAccountMultiple_request);
            System.out.println("sellRetailNoAccountMultiple.result=" + _sellRetailNoAccountMultiple__return);


        }
        {
            System.out.println("Invoking makeMiscPayment...");
            com.centershift.store40.LookupUserRequest _makeMiscPayment_lookupUserRequest = null;
            com.centershift.store40.MakeMiscPaymentRequest _makeMiscPayment_request = null;
            com.centershift.store40.MakePaymentResponse _makeMiscPayment__return = port.makeMiscPayment(_makeMiscPayment_lookupUserRequest, _makeMiscPayment_request);
            System.out.println("makeMiscPayment.result=" + _makeMiscPayment__return);


        }
        {
            System.out.println("Invoking voidTransaction...");
            com.centershift.store40.LookupUserRequest _voidTransaction_lookupUserRequest = null;
            com.centershift.store40.VoidTransactionRequest _voidTransaction_request = null;
            com.centershift.store40.VoidTransactionResponse2 _voidTransaction__return = port.voidTransaction(_voidTransaction_lookupUserRequest, _voidTransaction_request);
            System.out.println("voidTransaction.result=" + _voidTransaction__return);


        }
        {
            System.out.println("Invoking updateAccount...");
            com.centershift.store40.LookupUserRequest _updateAccount_lookupUserRequest = null;
            com.centershift.store40.UpdateAccountRequest _updateAccount_request = null;
            com.centershift.store40.UpdateAccountResponse2 _updateAccount__return = port.updateAccount(_updateAccount_lookupUserRequest, _updateAccount_request);
            System.out.println("updateAccount.result=" + _updateAccount__return);


        }
        {
            System.out.println("Invoking getAuctionTax...");
            com.centershift.store40.LookupUserRequest _getAuctionTax_lookupUserRequest = null;
            com.centershift.store40.AuctionProceeds _getAuctionTax_request = null;
            com.centershift.store40.GetAuctionTaxResponse2 _getAuctionTax__return = port.getAuctionTax(_getAuctionTax_lookupUserRequest, _getAuctionTax_request);
            System.out.println("getAuctionTax.result=" + _getAuctionTax__return);


        }
        {
            System.out.println("Invoking getSiteRules...");
            com.centershift.store40.LookupUserRequest _getSiteRules_lookupUserRequest = null;
            com.centershift.store40.RulesRequest _getSiteRules_request = null;
            com.centershift.store40.GetSiteRulesResponse2 _getSiteRules__return = port.getSiteRules(_getSiteRules_lookupUserRequest, _getSiteRules_request);
            System.out.println("getSiteRules.result=" + _getSiteRules__return);


        }
        {
            System.out.println("Invoking addNewContact...");
            com.centershift.store40.LookupUserRequest _addNewContact_lookupUserRequest = null;
            com.centershift.store40.ContactRequest _addNewContact_request = null;
            com.centershift.store40.ContactResponse _addNewContact__return = port.addNewContact(_addNewContact_lookupUserRequest, _addNewContact_request);
            System.out.println("addNewContact.result=" + _addNewContact__return);


        }
        {
            System.out.println("Invoking getTotalDue...");
            com.centershift.store40.LookupUserRequest _getTotalDue_lookupUserRequest = null;
            com.centershift.store40.GetTotalDueRequest _getTotalDue_request = null;
            com.centershift.store40.GetTotalDueResponse2 _getTotalDue__return = port.getTotalDue(_getTotalDue_lookupUserRequest, _getTotalDue_request);
            System.out.println("getTotalDue.result=" + _getTotalDue__return);


        }
        {
            System.out.println("Invoking getQuoteData...");
            com.centershift.store40.LookupUserRequest _getQuoteData_lookupUserRequest = null;
            com.centershift.store40.GetQuoteDataRequest _getQuoteData_request = null;
            com.centershift.store40.GetQuoteDataResponse2 _getQuoteData__return = port.getQuoteData(_getQuoteData_lookupUserRequest, _getQuoteData_request);
            System.out.println("getQuoteData.result=" + _getQuoteData__return);


        }
        {
            System.out.println("Invoking addMultipleServices...");
            com.centershift.store40.LookupUserRequest _addMultipleServices_lookupUserRequest = null;
            com.centershift.store40.AddMultipleServiceRequest _addMultipleServices_request = null;
            com.centershift.store40.ArrayOfAddMultipleServicesResponse _addMultipleServices__return = port.addMultipleServices(_addMultipleServices_lookupUserRequest, _addMultipleServices_request);
            System.out.println("addMultipleServices.result=" + _addMultipleServices__return);


        }
        {
            System.out.println("Invoking makeReservation...");
            com.centershift.store40.LookupUserRequest _makeReservation_lookupUserRequest = null;
            com.centershift.store40.MakeReservationRequest _makeReservation_request = null;
            com.centershift.store40.MakeReservationResponse _makeReservation__return = port.makeReservation(_makeReservation_lookupUserRequest, _makeReservation_request);
            System.out.println("makeReservation.result=" + _makeReservation__return);


        }
        {
            System.out.println("Invoking assessFee...");
            com.centershift.store40.LookupUserRequest _assessFee_lookupUserRequest = null;
            com.centershift.store40.AssessFeeRequest _assessFee_request = null;
            com.centershift.store40.AssessFeeResponse2 _assessFee__return = port.assessFee(_assessFee_lookupUserRequest, _assessFee_request);
            System.out.println("assessFee.result=" + _assessFee__return);


        }
        {
            System.out.println("Invoking searchBy...");
            com.centershift.store40.LookupUserRequest _searchBy_lookupUserRequest = null;
            com.centershift.store40.SearchByRequest _searchBy_request = null;
            com.centershift.store40.SearchByResponse2 _searchBy__return = port.searchBy(_searchBy_lookupUserRequest, _searchBy_request);
            System.out.println("searchBy.result=" + _searchBy__return);


        }
        {
            System.out.println("Invoking updatePhone...");
            com.centershift.store40.LookupUserRequest _updatePhone_lookupUserRequest = null;
            com.centershift.store40.PhoneRequest _updatePhone_request = null;
            com.centershift.store40.PhoneResponse _updatePhone__return = port.updatePhone(_updatePhone_lookupUserRequest, _updatePhone_request);
            System.out.println("updatePhone.result=" + _updatePhone__return);


        }
        {
            System.out.println("Invoking mailCentralizedReceipt...");
            com.centershift.store40.LookupUserRequest _mailCentralizedReceipt_lookupUserRequest = null;
            com.centershift.store40.CreateOrViewReceiptRequest _mailCentralizedReceipt_request = null;
            com.centershift.store40.TntLtrNumResponse _mailCentralizedReceipt__return = port.mailCentralizedReceipt(_mailCentralizedReceipt_lookupUserRequest, _mailCentralizedReceipt_request);
            System.out.println("mailCentralizedReceipt.result=" + _mailCentralizedReceipt__return);


        }
        {
            System.out.println("Invoking cancelInsurance...");
            com.centershift.store40.LookupUserRequest _cancelInsurance_lookupUserRequest = null;
            com.centershift.store40.CancelInsuranceRequest _cancelInsurance_request = null;
            com.centershift.store40.CancelInsuranceResponse _cancelInsurance__return = port.cancelInsurance(_cancelInsurance_lookupUserRequest, _cancelInsurance_request);
            System.out.println("cancelInsurance.result=" + _cancelInsurance__return);


        }
        {
            System.out.println("Invoking createAndViewLetter...");
            com.centershift.store40.LookupUserRequest _createAndViewLetter_lookupUserRequest = null;
            com.centershift.store40.CreateOrViewLtrRequest _createAndViewLetter_request = null;
            com.centershift.store40.PdfFilePathResponse _createAndViewLetter__return = port.createAndViewLetter(_createAndViewLetter_lookupUserRequest, _createAndViewLetter_request);
            System.out.println("createAndViewLetter.result=" + _createAndViewLetter__return);


        }
        {
            System.out.println("Invoking getMoveOutInfo...");
            com.centershift.store40.LookupUserRequest _getMoveOutInfo_lookupUserRequest = null;
            com.centershift.store40.GetMoveOutInfoRequest _getMoveOutInfo_request = null;
            com.centershift.store40.GetMoveOutInfoResponse2 _getMoveOutInfo__return = port.getMoveOutInfo(_getMoveOutInfo_lookupUserRequest, _getMoveOutInfo_request);
            System.out.println("getMoveOutInfo.result=" + _getMoveOutInfo__return);


        }
        {
            System.out.println("Invoking walkThruList...");
            com.centershift.store40.LookupUserRequest _walkThruList_lookupUserRequest = null;
            com.centershift.store40.WalkThruListRequest _walkThruList_request = null;
            com.centershift.store40.WalkThruListResponse2 _walkThruList__return = port.walkThruList(_walkThruList_lookupUserRequest, _walkThruList_request);
            System.out.println("walkThruList.result=" + _walkThruList__return);


        }
        {
            System.out.println("Invoking miniKeyStats...");
            com.centershift.store40.LookupUserRequest _miniKeyStats_lookupUserRequest = null;
            com.centershift.store40.MiniKeyStatsRequest _miniKeyStats_request = null;
            com.centershift.store40.MiniKeyStatsResponse2 _miniKeyStats__return = port.miniKeyStats(_miniKeyStats_lookupUserRequest, _miniKeyStats_request);
            System.out.println("miniKeyStats.result=" + _miniKeyStats__return);


        }
        {
            System.out.println("Invoking getEndRentalRules...");
            com.centershift.store40.LookupUserRequest _getEndRentalRules_lookupUserRequest = null;
            com.centershift.store40.GetEndRentalRulesRequest _getEndRentalRules_request = null;
            com.centershift.store40.GetEndRentalRulesResponse2 _getEndRentalRules__return = port.getEndRentalRules(_getEndRentalRules_lookupUserRequest, _getEndRentalRules_request);
            System.out.println("getEndRentalRules.result=" + _getEndRentalRules__return);


        }
        {
            System.out.println("Invoking sellRetailWithAccountMultiple...");
            com.centershift.store40.LookupUserRequest _sellRetailWithAccountMultiple_lookupUserRequest = null;
            com.centershift.store40.SellRetailWithAccountMultipleRequest _sellRetailWithAccountMultiple_request = null;
            com.centershift.store40.SellRetailMultipleResponse _sellRetailWithAccountMultiple__return = port.sellRetailWithAccountMultiple(_sellRetailWithAccountMultiple_lookupUserRequest, _sellRetailWithAccountMultiple_request);
            System.out.println("sellRetailWithAccountMultiple.result=" + _sellRetailWithAccountMultiple__return);


        }
        {
            System.out.println("Invoking addInsurance...");
            com.centershift.store40.LookupUserRequest _addInsurance_lookupUserRequest = null;
            com.centershift.store40.AddInsuranceRequest _addInsurance_request = null;
            com.centershift.store40.AddInsuranceResponse2 _addInsurance__return = port.addInsurance(_addInsurance_lookupUserRequest, _addInsurance_request);
            System.out.println("addInsurance.result=" + _addInsurance__return);


        }
        {
            System.out.println("Invoking updateOverlockStatus...");
            com.centershift.store40.LookupUserRequest _updateOverlockStatus_lookupUserRequest = null;
            com.centershift.store40.UpdateOverlockStatusRequest _updateOverlockStatus_request = null;
            com.centershift.store40.UpdateOverlockStatusResponse2 _updateOverlockStatus__return = port.updateOverlockStatus(_updateOverlockStatus_lookupUserRequest, _updateOverlockStatus_request);
            System.out.println("updateOverlockStatus.result=" + _updateOverlockStatus__return);


        }
        {
            System.out.println("Invoking getAppliedInsurance...");
            com.centershift.store40.LookupUserRequest _getAppliedInsurance_lookupUserRequest = null;
            com.centershift.store40.GetAppliedInsuranceRequest _getAppliedInsurance_request = null;
            com.centershift.store40.GetAppliedInsuranceResponse2 _getAppliedInsurance__return = port.getAppliedInsurance(_getAppliedInsurance_lookupUserRequest, _getAppliedInsurance_request);
            System.out.println("getAppliedInsurance.result=" + _getAppliedInsurance__return);


        }
        {
            System.out.println("Invoking cancelInsuranceBundle...");
            com.centershift.store40.LookupUserRequest _cancelInsuranceBundle_lookupUserRequest = null;
            com.centershift.store40.GetAppliedInsuranceRequest _cancelInsuranceBundle_request = null;
            com.centershift.store40.CancelInsuranceResponse _cancelInsuranceBundle__return = port.cancelInsuranceBundle(_cancelInsuranceBundle_lookupUserRequest, _cancelInsuranceBundle_request);
            System.out.println("cancelInsuranceBundle.result=" + _cancelInsuranceBundle__return);


        }
        {
            System.out.println("Invoking makeMultipleReservations...");
            com.centershift.store40.LookupUserRequest _makeMultipleReservations_lookupUserRequest = null;
            com.centershift.store40.MakeMultipleReservationsRequest _makeMultipleReservations_request = null;
            com.centershift.store40.MakeMultipleReservationsResponse2 _makeMultipleReservations__return = port.makeMultipleReservations(_makeMultipleReservations_lookupUserRequest, _makeMultipleReservations_request);
            System.out.println("makeMultipleReservations.result=" + _makeMultipleReservations__return);


        }
        {
            System.out.println("Invoking waiveFee...");
            com.centershift.store40.LookupUserRequest _waiveFee_lookupUserRequest = null;
            com.centershift.store40.WaiveFeeRequest _waiveFee_request = null;
            com.centershift.store40.WaiveFeeResponse2 _waiveFee__return = port.waiveFee(_waiveFee_lookupUserRequest, _waiveFee_request);
            System.out.println("waiveFee.result=" + _waiveFee__return);


        }
        {
            System.out.println("Invoking getSiteRuleValue...");
            com.centershift.store40.LookupUserRequest _getSiteRuleValue_lookupUserRequest = null;
            com.centershift.store40.RulesRequest _getSiteRuleValue_request = null;
            com.centershift.store40.GetSiteRuleValueResponse2 _getSiteRuleValue__return = port.getSiteRuleValue(_getSiteRuleValue_lookupUserRequest, _getSiteRuleValue_request);
            System.out.println("getSiteRuleValue.result=" + _getSiteRuleValue__return);


        }
        {
            System.out.println("Invoking terminateService...");
            com.centershift.store40.LookupUserRequest _terminateService_lookupUserRequest = null;
            com.centershift.store40.TerminateServiceRequest _terminateService_request = null;
            com.centershift.store40.TerminateServiceResponse2 _terminateService__return = port.terminateService(_terminateService_lookupUserRequest, _terminateService_request);
            System.out.println("terminateService.result=" + _terminateService__return);


        }
        {
            System.out.println("Invoking applyCreditToAssessments...");
            com.centershift.store40.LookupUserRequest _applyCreditToAssessments_lookupUserRequest = null;
            com.centershift.store40.ApplyCreditToAssessmentsRequest _applyCreditToAssessments_request = null;
            com.centershift.store40.ApplyCreditToAssessmentsResponse2 _applyCreditToAssessments__return = port.applyCreditToAssessments(_applyCreditToAssessments_lookupUserRequest, _applyCreditToAssessments_request);
            System.out.println("applyCreditToAssessments.result=" + _applyCreditToAssessments__return);


        }
        {
            System.out.println("Invoking createNewEcommAccount...");
            com.centershift.store40.LookupUserRequest _createNewEcommAccount_lookupUserRequest = null;
            com.centershift.store40.CreateNewEcommAccountRequest _createNewEcommAccount_request = null;
            com.centershift.store40.CreateNewEcommAccountResponse2 _createNewEcommAccount__return = port.createNewEcommAccount(_createNewEcommAccount_lookupUserRequest, _createNewEcommAccount_request);
            System.out.println("createNewEcommAccount.result=" + _createNewEcommAccount__return);


        }
        {
            System.out.println("Invoking createAuction...");
            com.centershift.store40.LookupUserRequest _createAuction_lookupUserRequest = null;
            com.centershift.store40.CreateAuctionRequest _createAuction_request = null;
            com.centershift.store40.CreateAuctionResponse _createAuction__return = port.createAuction(_createAuction_lookupUserRequest, _createAuction_request);
            System.out.println("createAuction.result=" + _createAuction__return);


        }
        {
            System.out.println("Invoking updateGatePIN...");
            com.centershift.store40.LookupUserRequest _updateGatePIN_lookupUserRequest = null;
            com.centershift.store40.UpdateGatePINRequest _updateGatePIN_request = null;
            com.centershift.store40.UpdateGatePINResponse2 _updateGatePIN__return = port.updateGatePIN(_updateGatePIN_lookupUserRequest, _updateGatePIN_request);
            System.out.println("updateGatePIN.result=" + _updateGatePIN__return);


        }
        {
            System.out.println("Invoking getRetailReceiptItems...");
            com.centershift.store40.LookupUserRequest _getRetailReceiptItems_lookupUserRequest = null;
            com.centershift.store40.GetRetailReceiptItemsRequest _getRetailReceiptItems_request = null;
            com.centershift.store40.GetRetailReceiptItemsResponse2 _getRetailReceiptItems__return = port.getRetailReceiptItems(_getRetailReceiptItems_lookupUserRequest, _getRetailReceiptItems_request);
            System.out.println("getRetailReceiptItems.result=" + _getRetailReceiptItems__return);


        }
        {
            System.out.println("Invoking getTenantLetterList...");
            com.centershift.store40.LookupUserRequest _getTenantLetterList_lookupUserRequest = null;
            com.centershift.store40.GetTenantDocListRequest _getTenantLetterList_request = null;
            com.centershift.store40.GetTenantLetterListResponse2 _getTenantLetterList__return = port.getTenantLetterList(_getTenantLetterList_lookupUserRequest, _getTenantLetterList_request);
            System.out.println("getTenantLetterList.result=" + _getTenantLetterList__return);


        }
        {
            System.out.println("Invoking getMiscRevenueClassData...");
            com.centershift.store40.LookupUserRequest _getMiscRevenueClassData_lookupUserRequest = null;
            com.centershift.store40.GetMiscRevenueClassDataRequest _getMiscRevenueClassData_request = null;
            com.centershift.store40.GetMiscRevenueClassDataResponse2 _getMiscRevenueClassData__return = port.getMiscRevenueClassData(_getMiscRevenueClassData_lookupUserRequest, _getMiscRevenueClassData_request);
            System.out.println("getMiscRevenueClassData.result=" + _getMiscRevenueClassData__return);


        }
        {
            System.out.println("Invoking getInsuranceInfo...");
            com.centershift.store40.GetInsuranceInfoRequest _getInsuranceInfo_request = null;
            com.centershift.store40.GetInsuranceInfoResponse2 _getInsuranceInfo__return = port.getInsuranceInfo(_getInsuranceInfo_request);
            System.out.println("getInsuranceInfo.result=" + _getInsuranceInfo__return);


        }
        {
            System.out.println("Invoking eUnitAttr02...");
            long _eUnitAttr02_orgID = 0;
            com.centershift.store40.ArrayOfCFGLOOKUPS _eUnitAttr02__return = port.eUnitAttr02(_eUnitAttr02_orgID);
            System.out.println("eUnitAttr02.result=" + _eUnitAttr02__return);


        }
        {
            System.out.println("Invoking getGateCodeInfo...");
            com.centershift.store40.LookupUserRequest _getGateCodeInfo_lookupUserRequest = null;
            com.centershift.store40.GetGateCodeInfoRequest _getGateCodeInfo_request = null;
            com.centershift.store40.GetGateCodeInfoResponse2 _getGateCodeInfo__return = port.getGateCodeInfo(_getGateCodeInfo_lookupUserRequest, _getGateCodeInfo_request);
            System.out.println("getGateCodeInfo.result=" + _getGateCodeInfo__return);


        }
        {
            System.out.println("Invoking fiuChecksumUpdate...");
            com.centershift.store40.LookupUserRequest _fiuChecksumUpdate_lookupUserRequest = null;
            com.centershift.store40.FIUChecksumRequest _fiuChecksumUpdate_request = null;
            java.lang.String _fiuChecksumUpdate__return = port.fiuChecksumUpdate(_fiuChecksumUpdate_lookupUserRequest, _fiuChecksumUpdate_request);
            System.out.println("fiuChecksumUpdate.result=" + _fiuChecksumUpdate__return);


        }
        {
            System.out.println("Invoking updateRental...");
            com.centershift.store40.LookupUserRequest _updateRental_lookupUserRequest = null;
            com.centershift.store40.UpdateRentalRequest _updateRental_request = null;
            com.centershift.store40.UpdateRentalResponse2 _updateRental__return = port.updateRental(_updateRental_lookupUserRequest, _updateRental_request);
            System.out.println("updateRental.result=" + _updateRental__return);


        }
        {
            System.out.println("Invoking getNotes...");
            com.centershift.store40.LookupUserRequest _getNotes_lookupUserRequest = null;
            com.centershift.store40.GetNotesRequest _getNotes_request = null;
            com.centershift.store40.GetNotesResponse2 _getNotes__return = port.getNotes(_getNotes_lookupUserRequest, _getNotes_request);
            System.out.println("getNotes.result=" + _getNotes__return);


        }
        {
            System.out.println("Invoking eUnitDoor...");
            long _eUnitDoor_orgID = 0;
            com.centershift.store40.ArrayOfCFGLOOKUPS _eUnitDoor__return = port.eUnitDoor(_eUnitDoor_orgID);
            System.out.println("eUnitDoor.result=" + _eUnitDoor__return);


        }
        {
            System.out.println("Invoking updateStreetRate...");
            com.centershift.store40.LookupUserRequest _updateStreetRate_lookupUserRequest = null;
            com.centershift.store40.UpdateStreetRateRequest _updateStreetRate_request = null;
            com.centershift.store40.UpdateStreetRateResponse2 _updateStreetRate__return = port.updateStreetRate(_updateStreetRate_lookupUserRequest, _updateStreetRate_request);
            System.out.println("updateStreetRate.result=" + _updateStreetRate__return);


        }
        {
            System.out.println("Invoking removeRentalFromAuction...");
            com.centershift.store40.LookupUserRequest _removeRentalFromAuction_lookupUserRequest = null;
            com.centershift.store40.RemoveRentalFromAuctionRequest _removeRentalFromAuction_request = null;
            com.centershift.store40.RemoveRentalFromAuctionResponse2 _removeRentalFromAuction__return = port.removeRentalFromAuction(_removeRentalFromAuction_lookupUserRequest, _removeRentalFromAuction_request);
            System.out.println("removeRentalFromAuction.result=" + _removeRentalFromAuction__return);


        }
        {
            System.out.println("Invoking getContactPhoneNumbers...");
            com.centershift.store40.LookupUserRequest _getContactPhoneNumbers_lookupUserRequest = null;
            com.centershift.store40.AccountRequest _getContactPhoneNumbers_request = null;
            com.centershift.store40.GetContactPhoneNumbersResponse2 _getContactPhoneNumbers__return = port.getContactPhoneNumbers(_getContactPhoneNumbers_lookupUserRequest, _getContactPhoneNumbers_request);
            System.out.println("getContactPhoneNumbers.result=" + _getContactPhoneNumbers__return);


        }
        {
            System.out.println("Invoking updateInsurance...");
            com.centershift.store40.LookupUserRequest _updateInsurance_lookupUserRequest = null;
            com.centershift.store40.UpdateInsuranceRequest _updateInsurance_request = null;
            com.centershift.store40.UpdateInsuranceResponse2 _updateInsurance__return = port.updateInsurance(_updateInsurance_lookupUserRequest, _updateInsurance_request);
            System.out.println("updateInsurance.result=" + _updateInsurance__return);


        }
        {
            System.out.println("Invoking getAvailableDeposits...");
            com.centershift.store40.LookupUserRequest _getAvailableDeposits_lookupUserRequest = null;
            com.centershift.store40.GetAvailableDepositsRequest _getAvailableDeposits_request = null;
            com.centershift.store40.GetAvailableDepositsResponse2 _getAvailableDeposits__return = port.getAvailableDeposits(_getAvailableDeposits_lookupUserRequest, _getAvailableDeposits_request);
            System.out.println("getAvailableDeposits.result=" + _getAvailableDeposits__return);


        }
        {
            System.out.println("Invoking processRefund...");
            com.centershift.store40.LookupUserRequest _processRefund_lookupUserRequest = null;
            com.centershift.store40.ProcessRefundRequest _processRefund_request = null;
            com.centershift.store40.ProcessRefundResponse2 _processRefund__return = port.processRefund(_processRefund_lookupUserRequest, _processRefund_request);
            System.out.println("processRefund.result=" + _processRefund__return);


        }
        {
            System.out.println("Invoking getAccountInfo...");
            com.centershift.store40.LookupUserRequest _getAccountInfo_lookupUserRequest = null;
            com.centershift.store40.AccountRequest _getAccountInfo_request = null;
            com.centershift.store40.GetAccountInfoResponse2 _getAccountInfo__return = port.getAccountInfo(_getAccountInfo_lookupUserRequest, _getAccountInfo_request);
            System.out.println("getAccountInfo.result=" + _getAccountInfo__return);


        }
        {
            System.out.println("Invoking initiateUnitTransfer...");
            com.centershift.store40.LookupUserRequest _initiateUnitTransfer_lookupUserRequest = null;
            com.centershift.store40.InitiateUnitTransferRequest _initiateUnitTransfer_request = null;
            com.centershift.store40.InitiateUnitTransferResponse2 _initiateUnitTransfer__return = port.initiateUnitTransfer(_initiateUnitTransfer_lookupUserRequest, _initiateUnitTransfer_request);
            System.out.println("initiateUnitTransfer.result=" + _initiateUnitTransfer__return);


        }
        {
            System.out.println("Invoking makePayment...");
            com.centershift.store40.LookupUserRequest _makePayment_lookupUserRequest = null;
            com.centershift.store40.MakePaymentRequest _makePayment_request = null;
            com.centershift.store40.MakePaymentResponse _makePayment__return = port.makePayment(_makePayment_lookupUserRequest, _makePayment_request);
            System.out.println("makePayment.result=" + _makePayment__return);


        }
        {
            System.out.println("Invoking addNewPhone...");
            com.centershift.store40.LookupUserRequest _addNewPhone_lookupUserRequest = null;
            com.centershift.store40.PhoneRequest _addNewPhone_request = null;
            com.centershift.store40.PhoneResponse _addNewPhone__return = port.addNewPhone(_addNewPhone_lookupUserRequest, _addNewPhone_request);
            System.out.println("addNewPhone.result=" + _addNewPhone__return);


        }
        {
            System.out.println("Invoking paymentReceiptBundle...");
            com.centershift.store40.LookupUserRequest _paymentReceiptBundle_lookupUserRequest = null;
            com.centershift.store40.PaymentReceiptBundleRequest _paymentReceiptBundle_request = null;
            com.centershift.store40.PaymentReceiptBundleResponse2 _paymentReceiptBundle__return = port.paymentReceiptBundle(_paymentReceiptBundle_lookupUserRequest, _paymentReceiptBundle_request);
            System.out.println("paymentReceiptBundle.result=" + _paymentReceiptBundle__return);


        }
        {
            System.out.println("Invoking getAvailableRetailItems...");
            com.centershift.store40.LookupUserRequest _getAvailableRetailItems_lookupUserRequest = null;
            com.centershift.store40.GetAvailableRetailItemsRequest _getAvailableRetailItems_request = null;
            com.centershift.store40.GetAvailableRetailItemsResponse2 _getAvailableRetailItems__return = port.getAvailableRetailItems(_getAvailableRetailItems_lookupUserRequest, _getAvailableRetailItems_request);
            System.out.println("getAvailableRetailItems.result=" + _getAvailableRetailItems__return);


        }
        {
            System.out.println("Invoking getContactAddresses...");
            com.centershift.store40.LookupUserRequest _getContactAddresses_lookupUserRequest = null;
            com.centershift.store40.AccountRequest _getContactAddresses_request = null;
            com.centershift.store40.GetContactAddressesResponse2 _getContactAddresses__return = port.getContactAddresses(_getContactAddresses_lookupUserRequest, _getContactAddresses_request);
            System.out.println("getContactAddresses.result=" + _getContactAddresses__return);


        }
        {
            System.out.println("Invoking voidRetailAssessments...");
            com.centershift.store40.LookupUserRequest _voidRetailAssessments_lookupUserRequest = null;
            com.centershift.store40.VoidRetailAssessmentRequest _voidRetailAssessments_request = null;
            com.centershift.store40.VoidRetailAssessmentResponse _voidRetailAssessments__return = port.voidRetailAssessments(_voidRetailAssessments_lookupUserRequest, _voidRetailAssessments_request);
            System.out.println("voidRetailAssessments.result=" + _voidRetailAssessments__return);


        }
        {
            System.out.println("Invoking addService...");
            com.centershift.store40.LookupUserRequest _addService_lookupUserRequest = null;
            com.centershift.store40.AddServiceRequest _addService_request = null;
            com.centershift.store40.AddServiceResponse2 _addService__return = port.addService(_addService_lookupUserRequest, _addService_request);
            System.out.println("addService.result=" + _addService__return);


        }
        {
            System.out.println("Invoking getReceiptRules...");
            com.centershift.store40.LookupUserRequest _getReceiptRules_lookupUserRequest = null;
            com.centershift.store40.GetRulesRequest _getReceiptRules_request = null;
            com.centershift.store40.GetRulesResponse _getReceiptRules__return = port.getReceiptRules(_getReceiptRules_lookupUserRequest, _getReceiptRules_request);
            System.out.println("getReceiptRules.result=" + _getReceiptRules__return);


        }
        {
            System.out.println("Invoking updateAddress...");
            com.centershift.store40.LookupUserRequest _updateAddress_lookupUserRequest = null;
            com.centershift.store40.ContactAddress _updateAddress_request = null;
            com.centershift.store40.AddressResponse _updateAddress__return = port.updateAddress(_updateAddress_lookupUserRequest, _updateAddress_request);
            System.out.println("updateAddress.result=" + _updateAddress__return);


        }
        {
            System.out.println("Invoking getTenantLeaseList...");
            com.centershift.store40.LookupUserRequest _getTenantLeaseList_lookupUserRequest = null;
            com.centershift.store40.GetTenantDocListRequest _getTenantLeaseList_request = null;
            com.centershift.store40.GetTenantLeaseListResponse2 _getTenantLeaseList__return = port.getTenantLeaseList(_getTenantLeaseList_lookupUserRequest, _getTenantLeaseList_request);
            System.out.println("getTenantLeaseList.result=" + _getTenantLeaseList__return);


        }
        {
            System.out.println("Invoking verifyEcommLogin...");
            com.centershift.store40.LookupUserRequest _verifyEcommLogin_lookupUserRequest = null;
            com.centershift.store40.PasswordRequest _verifyEcommLogin_request = null;
            com.centershift.store40.VerifyEcommLoginResponse2 _verifyEcommLogin__return = port.verifyEcommLogin(_verifyEcommLogin_lookupUserRequest, _verifyEcommLogin_request);
            System.out.println("verifyEcommLogin.result=" + _verifyEcommLogin__return);


        }
        {
            System.out.println("Invoking resetRefunds...");
            com.centershift.store40.LookupUserRequest _resetRefunds_lookupUserRequest = null;
            com.centershift.store40.RefundRequest _resetRefunds_request = null;
            com.centershift.store40.RefundResponse _resetRefunds__return = port.resetRefunds(_resetRefunds_lookupUserRequest, _resetRefunds_request);
            System.out.println("resetRefunds.result=" + _resetRefunds__return);


        }
        {
            System.out.println("Invoking getDelinqSchedule...");
            com.centershift.store40.LookupUserRequest _getDelinqSchedule_lookupUserRequest = null;
            com.centershift.store40.GetDelinqScheduleRequest _getDelinqSchedule_request = null;
            com.centershift.store40.GetDelinqScheduleResponse2 _getDelinqSchedule__return = port.getDelinqSchedule(_getDelinqSchedule_lookupUserRequest, _getDelinqSchedule_request);
            System.out.println("getDelinqSchedule.result=" + _getDelinqSchedule__return);


        }

        System.exit(0);
    }

}
