var directionsService;
var directionsDisplay;
var map;
var marker;
var premiums = [];
var destLatLng;
var siteLat = "${site.lat}";
var siteLng = "${site.lng}";
var siteTitle = "${site.title}";
var srcIconMapGreen = ${p.imageLink(src: 'icn_map_grn.png')};
var srcIconMapBlue = ${p.imageLink(src: 'icn_map_blue.png')};
