import storitz.constants.TruckType;
import storitz.constants.PromoType

class BootStrap {

     def authenticateService

     def init = { servletContext ->
       
       def roleUser = new Role( authority: 'ROLE_USER', description: 'Authenticated User').save(flush: true)
       def roleAdmin = new Role( authority: 'ROLE_ADMIN', description: 'Admin user').save(flush: true)
       def roleManager = new Role( authority: 'ROLE_MANAGER', description: 'Site Manager').save(flush: true)

       def admin = new User( username:'admin', passwd:authenticateService.encodePassword('WWCharter'), userRealName:'Administrator', enabled:true, email:'mamster@wnx.com')
       if (roleAdmin) {
        roleAdmin.addToPeople(admin)
       }
       if (roleUser) {
        roleUser.addToPeople(admin)
       }
       admin.save(flush: true)

       /**
       def site1 = new StorageSite( title:'Public Storage - Self Storage', address:'1606 Cotner Ave', city:'Los Angeles', state:'CA', zipcode: '90064', phone:'(800) 883-8369', url:'http://publicstorage.com', lat:'34.0482555637589', lng:'-118.446877335723', freeTruck: TruckType.FREE, requiresInsurance: true, boxesAvailable:true, isGate: true, isKeypad: true, isCamera: true, isUnitAlarmed: false, adminFee: 25, lockFee: 14).save();
       def site2 = new StorageSite( title:'Public Storage', address:'1617 Pontius Ave', city:'Los Angeles', state:'CA', zipcode: '90064', phone:'(310) 914-4572', url:'http://publicstorage.com', lat:'34.0480245162411', lng:'-118.446916184277', freeTruck: TruckType.NONE, requiresInsurance: true, boxesAvailable:true, isGate: true, isKeypad: true, isCamera: true, isUnitAlarmed: false, adminFee: 20, lockFee: 14 ).save();
       def site3 = new StorageSite( title:'A-1 Self Storage: Full Security', address:'11820 W. Olympic Blvd.', city:'Los Angeles', state:'CA', zipcode: '90064', phone:'(310) 571-0044', url:'http://selfstorage1.com', lat:'34.044858', lng:'-118.448436', freeTruck: TruckType.RENTAL, requiresInsurance: true, boxesAvailable:true, isGate: true, isKeypad: true, isCamera: true, isUnitAlarmed: false, adminFee: 22, lockFee: 8 ).save();
       def site4 = new StorageSite( title:'Public Storage - Self Storage', address:'11200 W Pico Blvd', city:'Los Angeles', state:'CA', zipcode: '90064', phone:'(800) 883-8369', url:'http://publicstorage.com', lat:'34.0365126774481', lng:'-118.425388593827', freeTruck: TruckType.FREE, requiresInsurance: true, boxesAvailable:true, isGate: true, isKeypad: true, isCamera: true, isUnitAlarmed: false, adminFee: 20, lockFee: 0 ).save();
       def site5 = new StorageSite( title:'Westwood Self Storage', address:'1901 S Sepulveda Blvd', city:'Los Angeles', state:'CA', zipcode:'90025-5619', phone:'(310) 478-1901', url:'http://www.executiveselfstorage.com', lat:'34.1074181042622', lng:'-118.480301588142', freeTruck: TruckType.NONE, requiresInsurance: false, boxesAvailable:true, isGate: true, isKeypad: true, isCamera: true, isUnitAlarmed: false, adminFee: 25, lockFee: 0 ).save();
       def site6 = new StorageSite( title:'EZ Storage - Self Storage', address:'11471 West Pico Blvd.', city:'Los Angeles', state:'CA', zipcode:'90064', phone:'(877) 351-6029', url:'http://ezstorageonline.com', lat:'34.0340018834908', lng:'-118.441389137916', freeTruck: TruckType.RENTAL, requiresInsurance: false, boxesAvailable:false, isGate: true, isKeypad: true, isCamera: true, isUnitAlarmed: false, adminFee: 25, lockFee: 12).save();
       def site7 = new StorageSite( title:'A-American Self Storage: West Los Angeles', address:'2300 Federal Ave.', city:'Los Angeles', state:'CA', zipcode:'90064-1406', phone:'(310) 597-4004', url:'http://aamericanselfstorage.com', lat:'34.0339469723605', lng:'-118.444585453274', freeTruck: TruckType.FREE, requiresInsurance: false, boxesAvailable:true, isGate: true, isKeypad: true, isCamera: true, isUnitAlarmed: false, adminFee: 20, lockFee: 12 ).save();
       def site8 = new StorageSite( title:'Storquest Self Storage', address:'2531 Sawtelle Blvd.', city:'Los Angeles', state:'CA', zipcode:'90064', phone:'(310) 817-6710', url:'http://storquest.com', lat:'34.0292128938148', lng:'-118.441494670588', freeTruck: TruckType.RENTAL, requiresInsurance: false, boxesAvailable:false, isGate: true, isKeypad: true, isCamera: true, isUnitAlarmed: false, adminFee: 30, lockFee: 10  ).save();

       def offer1 = new SpecialOffer(promoName: 'Second Month $1', description:'Second Month $1', prepay: false, active: true, inMonth: 2, expireMonth: 1, prepayMonths: 1, promoType: PromoType.FIXED_RATE, promoQty: new BigDecimal(1.00)).save();
       def offer2 = new SpecialOffer(promoName:'Second Month 50% off', description:'Second Month 50% off', prepay: false, active: true, inMonth: 2, expireMonth: 1, prepayMonths: 1, promoType: PromoType.PERCENT_OFF, promoQty: new BigDecimal(0.50)).save();
       def offer3 = new SpecialOffer(promoName:'$19.95 Moves you in', description:'$19.95 Moves you in', prepay: false, active: true, inMonth: 1, expireMonth: 1, prepayMonths: 1, promoType: PromoType.FIXED_RATE, promoQty: new BigDecimal(19.95)).save();
       def offer4 = new SpecialOffer(promoName:'$10 Off move in', description:'$10 Off move in', prepay: false, active: true, inMonth: 1, prepayMonths: 1, expireMonth: 1, promoType: PromoType.AMOUNT_OFF, promoQty: new BigDecimal(10.00)).save();
       def offer5 = new SpecialOffer(promoName:'4 mos. 50% off', description:'4 mos. 50% off', prepay: true, active: true, inMonth: 1, expireMonth: 4, prepayMonths: 4, promoType: PromoType.PERCENT_OFF, promoQty: new BigDecimal(0.50)).save();
       def offer6 = new SpecialOffer(promoName:'Second Month Free', description:'Second Month Free', prepay: true, active: true, inMonth: 2, expireMonth: 1, prepayMonths: 2, promoType: PromoType.PERCENT_OFF, promoQty: new BigDecimal(1.00)).save();

       site1.addToSpecialOffers(offer1)
       site2.addToSpecialOffers(offer2)
       site2.addToSpecialOffers(offer3)
       site3.addToSpecialOffers(offer3)
       site4.addToSpecialOffers(offer4)
       site5.addToSpecialOffers(offer5)
       site6.addToSpecialOffers(offer4)
       site7.addToSpecialOffers(offer3)
       site7.addToSpecialOffers(offer5)
       site8.addToSpecialOffers(offer6)
       **/

       def sizeUndefined = new StorageSize( description:'No size chosen', width: 0, length: 0).save();
       def size5x5 = new StorageSize( description:'5 x 5', width: 5, length: 5).save();
       def size5x10 = new StorageSize( description:'5 x 10', width: 5, length: 10).save();
       def size7x10 = new StorageSize( description:'7 x 10', width: 7, length: 10).save();
       def size10x10 = new StorageSize( description:'10 x 10', width: 10, length: 10).save();
       def size10x15 = new StorageSize( description:'10 x 15', width: 10, length: 15).save();
       def size10x20 = new StorageSize( description:'10 x 20', width: 10, length: 20).save();
       def size10x25 = new StorageSize( description:'10 x 25', width: 10, length: 25).save();
       def size10x30 = new StorageSize( description:'10 x 30', width: 10, length: 30).save();

       /**
       site1.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '1', isUpper: true, isInterior: false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 62, displaySize: "5 X 5", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '2', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 69, displaySize: "5 X 5", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '3', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 65, displaySize: "5 X 5", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '4', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 92, displaySize: "5 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '5', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 105, displaySize: "5 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '6', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 99, displaySize: "5 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '7', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 139, displaySize: "7 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '8', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 145, displaySize: "7 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '9', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 149, displaySize: "7 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '10', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 149, displaySize: "10 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '11', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 190, displaySize: "10 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '12', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 185, displaySize: "10 X 10", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '13', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 209, displaySize: "10 X 15", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '14', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 255, displaySize: "10 X 15", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '15', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 229, displaySize: "10 X 15", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '16', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 249, displaySize: "10 X 20", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '17', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 305, displaySize: "10 X 20", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '18', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 275, displaySize: "10 X 20", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '19', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 299, displaySize: "10 X 25", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '20', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 325, displaySize: "10 X 25", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '21', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 299, displaySize: "10 X 25", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '22', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 365, displaySize: "10 X 30", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '23', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 420, displaySize: "10 X 30", isAvailable: true).save())
       site1.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '24', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 410, displaySize: "10 X 30", isAvailable: true).save())

       site2.addToUnits(new StorageUnit(unitsize: size5x5, unitNumber: '1', isUpper: true, isInterior: false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 61,     displaySize: "5 X 5",   isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size5x5, unitNumber: '2', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 59,     displaySize: "5 X 5",   isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size5x5, unitNumber: '3', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 57,     displaySize: "5 X 5",   isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size5x10, unitNumber: '4', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 82,     displaySize: "5 X 10",  isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size5x10, unitNumber: '5', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 101,   displaySize: "5 X 10",  isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size5x10, unitNumber: '6', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 88,    displaySize: "5 X 10",  isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size7x10, unitNumber: '7', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 135,    displaySize: "7 X 10",  isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size7x10, unitNumber: '8', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 139,   displaySize: "7 X 10",  isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size7x10, unitNumber: '9', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 129,   displaySize: "7 X 10",  isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x10, unitNumber: '10', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 139,  displaySize: "10 X 10", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x10, unitNumber: '11', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 180, displaySize: "10 X 10", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x10, unitNumber: '12', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 175, displaySize: "10 X 10", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x15, unitNumber: '13', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 199,  displaySize: "10 X 15", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x15, unitNumber: '14', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 245, displaySize: "10 X 15", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x15, unitNumber: '15', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 219, displaySize: "10 X 15", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x20, unitNumber: '16', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 239,  displaySize: "10 X 20", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x20, unitNumber: '17', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 303, displaySize: "10 X 20", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x20, unitNumber: '18', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 265, displaySize: "10 X 20", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x25, unitNumber: '19', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 305,  displaySize: "10 X 25", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x25, unitNumber: '20', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 289, displaySize: "10 X 25", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x25, unitNumber: '21', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 289, displaySize: "10 X 25", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x30, unitNumber: '22', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 345,  displaySize: "10 X 30", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x30, unitNumber: '23', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 390, displaySize: "10 X 30", isAvailable: true).save())
       site2.addToUnits(new StorageUnit(unitsize: size10x30, unitNumber: '24', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 388, displaySize: "10 X 30", isAvailable: true).save())

       site3.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '1', isUpper: true, isInterior: false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 71,     displaySize: "5 X 5",   isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '2', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 78,     displaySize: "5 X 5",   isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '3', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 73,     displaySize: "5 X 5",   isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '4', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 89,     displaySize: "5 X 10",  isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '5', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 108,   displaySize: "5 X 10",  isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '6', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 95,    displaySize: "5 X 10",  isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '7', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 136,    displaySize: "7 X 10",  isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '8', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 146,   displaySize: "7 X 10",  isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '9', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 142,   displaySize: "7 X 10",  isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '10', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 146,  displaySize: "10 X 10", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '11', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 187, displaySize: "10 X 10", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '12', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 182, displaySize: "10 X 10", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '13', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 206,  displaySize: "10 X 15", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '14', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 252, displaySize: "10 X 15", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '15', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 246, displaySize: "10 X 15", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '16', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 245,  displaySize: "10 X 20", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '17', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 308, displaySize: "10 X 20", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '18', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 271, displaySize: "10 X 20", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '19', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 296,  displaySize: "10 X 25", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '20', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 312, displaySize: "10 X 25", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '21', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 297, displaySize: "10 X 25", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '22', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 354,  displaySize: "10 X 30", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '23', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: true, price: 399, displaySize: "10 X 30", isAvailable: true).save())
       site3.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '24', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: true, price: 394, displaySize: "10 X 30", isAvailable: true).save())

       site4.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '1', isUpper: true, isInterior: false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 62,     displaySize: "5 X 5",   isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '2', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 69,     displaySize: "5 X 5",   isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '3', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 65,     displaySize: "5 X 5",   isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '4', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 92,     displaySize: "5 X 10",  isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '5', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 105,   displaySize: "5 X 10",  isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '6', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 99,    displaySize: "5 X 10",  isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '7', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 139,    displaySize: "7 X 10",  isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '8', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 145,   displaySize: "7 X 10",  isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '9', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 149,   displaySize: "7 X 10",  isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '10', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 149,  displaySize: "10 X 10", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '11', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 190, displaySize: "10 X 10", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '12', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 185, displaySize: "10 X 10", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '13', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 209,  displaySize: "10 X 15", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '14', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 255, displaySize: "10 X 15", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '15', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 229, displaySize: "10 X 15", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '16', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 249,  displaySize: "10 X 20", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '17', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 305, displaySize: "10 X 20", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '18', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 275, displaySize: "10 X 20", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '19', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 299,  displaySize: "10 X 25", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '20', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 325, displaySize: "10 X 25", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '21', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 299, displaySize: "10 X 25", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '22', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 365,  displaySize: "10 X 30", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '23', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 420, displaySize: "10 X 30", isAvailable: true).save())
       site4.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '24', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 410, displaySize: "10 X 30", isAvailable: true).save())

       site5.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '1', isUpper: true, isInterior: false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 61,     displaySize: "5 X 5",   isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '2', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 59,     displaySize: "5 X 5",   isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '3', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 57,     displaySize: "5 X 5",   isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '4', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 82,     displaySize: "5 X 10",  isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '5', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 101,   displaySize: "5 X 10",  isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '6', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 88,    displaySize: "5 X 10",  isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '7', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 135,    displaySize: "7 X 10",  isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '8', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 139,   displaySize: "7 X 10",  isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '9', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 129,   displaySize: "7 X 10",  isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '10', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 139,  displaySize: "10 X 10", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '11', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 180, displaySize: "10 X 10", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '12', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 175, displaySize: "10 X 10", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '13', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 199,  displaySize: "10 X 15", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '14', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 245, displaySize: "10 X 15", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '15', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 219, displaySize: "10 X 15", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '16', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 239,  displaySize: "10 X 20", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '17', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 303, displaySize: "10 X 20", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '18', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 265, displaySize: "10 X 20", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '19', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 305,  displaySize: "10 X 25", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '20', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 289, displaySize: "10 X 25", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '21', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 289, displaySize: "10 X 25", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '22', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 345,  displaySize: "10 X 30", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '23', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 390, displaySize: "10 X 30", isAvailable: true).save())
       site5.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '24', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 388, displaySize: "10 X 30", isAvailable: true).save())

       site6.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '1', isUpper: true, isInterior: false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 71,     displaySize: "5 X 5",   isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '2', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 78,     displaySize: "5 X 5",   isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '3', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 73,     displaySize: "5 X 5",   isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '4', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 89,     displaySize: "5 X 10",  isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '5', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 108,   displaySize: "5 X 10",  isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '6', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 95,    displaySize: "5 X 10",  isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '7', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 136,    displaySize: "7 X 10",  isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '8', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 146,   displaySize: "7 X 10",  isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size7x10, unitNumber: '9', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 142,   displaySize: "7 X 10",  isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '10', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 146,  displaySize: "10 X 10", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '11', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 187, displaySize: "10 X 10", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '12', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 182, displaySize: "10 X 10", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '13', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 206,  displaySize: "10 X 15", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '14', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 252, displaySize: "10 X 15", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '15', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 246, displaySize: "10 X 15", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '16', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 245,  displaySize: "10 X 20", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '17', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 308, displaySize: "10 X 20", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '18', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 271, displaySize: "10 X 20", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '19', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 296,  displaySize: "10 X 25", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '20', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 312, displaySize: "10 X 25", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x25, unitNumber: '21', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 297, displaySize: "10 X 25", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '22', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 354,  displaySize: "10 X 30", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '23', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 399, displaySize: "10 X 30", isAvailable: true).save())
       site6.addToUnits(new StorageUnit( unitsize: size10x30, unitNumber: '24', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 394, displaySize: "10 X 30", isAvailable: true).save())

       site7.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '4', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 92,     displaySize: "5 X 5",    isAvailable: true).save())
       site7.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '5', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 105,   displaySize: "5 X 5",    isAvailable: true).save())
       site7.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '6', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 99,    displaySize: "5 X 5",    isAvailable: true).save())
       site7.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '10', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 149,  displaySize: "10 X 10",  isAvailable: true).save())
       site7.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '11', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 190, displaySize: "10 X 10",  isAvailable: true).save())
       site7.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '12', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 185, displaySize: "10 X 10",  isAvailable: true).save())
       site7.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '13', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 209,  displaySize: "10 X 15",  isAvailable: true).save())
       site7.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '14', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 255, displaySize: "10 X 15",  isAvailable: true).save())
       site7.addToUnits(new StorageUnit( unitsize: size10x15, unitNumber: '15', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 229, displaySize: "10 X 15",  isAvailable: true).save())

       site8.addToUnits(new StorageUnit( unitsize: size5x5, unitNumber: '2', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 72,      displaySize: "5 X 5",   isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '4', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 82,     displaySize: "5 X 10",   isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '5', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 101,   displaySize: "5 X 10",   isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size5x10, unitNumber: '6', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 88,    displaySize: "10 X 10", isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '10', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 139,  displaySize: "10 X 10", isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '11', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 180, displaySize: "10 X 10", isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size10x10, unitNumber: '12', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 175, displaySize: "10 X 10", isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '16', isUpper: true, isInterior:false, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 239,  displaySize: "10 X 20", isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '17', isUpper: false, isInterior: false, isAlarm: false, isDriveup: true, isSecure: false, isTempControlled: false, isPowered: false, price: 303, displaySize: "10 X 20", isAvailable: true).save())
       site8.addToUnits(new StorageUnit( unitsize: size10x20, unitNumber: '18', isUpper: false, isInterior: true, isAlarm: false, isDriveup: false, isSecure: false, isTempControlled: false, isPowered: false, price: 265, displaySize: "10 X 20", isAvailable: true).save())
       **/
     }

     def destroy = {
     }
} 